// Code generated by llcppg; DO NOT EDIT.

package llvm

import "github.com/goplus/lib/c"

// @defgroup LLVMCAnalysis Analysis
// @ingroup LLVMC
//
// @{
type VerifierFailureAction c.Uint

const (
	AbortProcessAction VerifierFailureAction = 0
	PrintMessageAction VerifierFailureAction = 1
	ReturnStatusAction VerifierFailureAction = 2
)

// llgo:link ModuleRef.VerifyModule C.LLVMVerifyModule
func (self ModuleRef) VerifyModule(Action VerifierFailureAction, OutMessage **c.Char) Bool {
	return 0
}

// llgo:link ValueRef.VerifyFunction C.LLVMVerifyFunction
func (self ValueRef) VerifyFunction(Action VerifierFailureAction) Bool {
	return 0
}

// llgo:link ValueRef.ViewFunctionCFG C.LLVMViewFunctionCFG
func (self ValueRef) ViewFunctionCFG() {
}

// llgo:link ValueRef.ViewFunctionCFGOnly C.LLVMViewFunctionCFGOnly
func (self ValueRef) ViewFunctionCFGOnly() {
}
