// Code generated by llcppg; DO NOT EDIT.

package llvm

import "github.com/goplus/lib/c"

// @defgroup LLVMCAnalysis Analysis
// @ingroup LLVMC
//
// @{
type VerifierFailureAction c.Int

const (
	AbortProcessAction VerifierFailureAction = 0
	PrintMessageAction VerifierFailureAction = 1
	ReturnStatusAction VerifierFailureAction = 2
)

// llgo:link (*OpaqueModule).VerifyModule C.LLVMVerifyModule
func (self *OpaqueModule) VerifyModule(Action VerifierFailureAction, OutMessage **c.Char) Bool {
	return 0
}

// llgo:link (*OpaqueValue).VerifyFunction C.LLVMVerifyFunction
func (self *OpaqueValue) VerifyFunction(Action VerifierFailureAction) Bool {
	return 0
}

// llgo:link (*OpaqueValue).ViewFunctionCFG C.LLVMViewFunctionCFG
func (self *OpaqueValue) ViewFunctionCFG() {
}

// llgo:link (*OpaqueValue).ViewFunctionCFGOnly C.LLVMViewFunctionCFGOnly
func (self *OpaqueValue) ViewFunctionCFGOnly() {
}
