// Code generated by llcppg; DO NOT EDIT.

package llvm

import _ "unsafe"

//go:linkname InitializeAArch64AsmPrinter C.LLVMInitializeAArch64AsmPrinter
func InitializeAArch64AsmPrinter()

//go:linkname InitializeAMDGPUAsmPrinter C.LLVMInitializeAMDGPUAsmPrinter
func InitializeAMDGPUAsmPrinter()

//go:linkname InitializeARMAsmPrinter C.LLVMInitializeARMAsmPrinter
func InitializeARMAsmPrinter()

//go:linkname InitializeAVRAsmPrinter C.LLVMInitializeAVRAsmPrinter
func InitializeAVRAsmPrinter()

//go:linkname InitializeBPFAsmPrinter C.LLVMInitializeBPFAsmPrinter
func InitializeBPFAsmPrinter()

//go:linkname InitializeHexagonAsmPrinter C.LLVMInitializeHexagonAsmPrinter
func InitializeHexagonAsmPrinter()

//go:linkname InitializeLanaiAsmPrinter C.LLVMInitializeLanaiAsmPrinter
func InitializeLanaiAsmPrinter()

//go:linkname InitializeLoongArchAsmPrinter C.LLVMInitializeLoongArchAsmPrinter
func InitializeLoongArchAsmPrinter()

//go:linkname InitializeMipsAsmPrinter C.LLVMInitializeMipsAsmPrinter
func InitializeMipsAsmPrinter()

//go:linkname InitializeMSP430AsmPrinter C.LLVMInitializeMSP430AsmPrinter
func InitializeMSP430AsmPrinter()

//go:linkname InitializeNVPTXAsmPrinter C.LLVMInitializeNVPTXAsmPrinter
func InitializeNVPTXAsmPrinter()

//go:linkname InitializePowerPCAsmPrinter C.LLVMInitializePowerPCAsmPrinter
func InitializePowerPCAsmPrinter()

//go:linkname InitializeRISCVAsmPrinter C.LLVMInitializeRISCVAsmPrinter
func InitializeRISCVAsmPrinter()

//go:linkname InitializeSparcAsmPrinter C.LLVMInitializeSparcAsmPrinter
func InitializeSparcAsmPrinter()

//go:linkname InitializeSPIRVAsmPrinter C.LLVMInitializeSPIRVAsmPrinter
func InitializeSPIRVAsmPrinter()

//go:linkname InitializeSystemZAsmPrinter C.LLVMInitializeSystemZAsmPrinter
func InitializeSystemZAsmPrinter()

//go:linkname InitializeVEAsmPrinter C.LLVMInitializeVEAsmPrinter
func InitializeVEAsmPrinter()

//go:linkname InitializeWebAssemblyAsmPrinter C.LLVMInitializeWebAssemblyAsmPrinter
func InitializeWebAssemblyAsmPrinter()

//go:linkname InitializeX86AsmPrinter C.LLVMInitializeX86AsmPrinter
func InitializeX86AsmPrinter()

//go:linkname InitializeXCoreAsmPrinter C.LLVMInitializeXCoreAsmPrinter
func InitializeXCoreAsmPrinter()
