// Code generated by llcppg; DO NOT EDIT.

package llvm

import _ "unsafe"

//go:linkname InitializeAArch64AsmParser C.LLVMInitializeAArch64AsmParser
func InitializeAArch64AsmParser()

//go:linkname InitializeAMDGPUAsmParser C.LLVMInitializeAMDGPUAsmParser
func InitializeAMDGPUAsmParser()

//go:linkname InitializeARMAsmParser C.LLVMInitializeARMAsmParser
func InitializeARMAsmParser()

//go:linkname InitializeAVRAsmParser C.LLVMInitializeAVRAsmParser
func InitializeAVRAsmParser()

//go:linkname InitializeBPFAsmParser C.LLVMInitializeBPFAsmParser
func InitializeBPFAsmParser()

//go:linkname InitializeHexagonAsmParser C.LLVMInitializeHexagonAsmParser
func InitializeHexagonAsmParser()

//go:linkname InitializeLanaiAsmParser C.LLVMInitializeLanaiAsmParser
func InitializeLanaiAsmParser()

//go:linkname InitializeLoongArchAsmParser C.LLVMInitializeLoongArchAsmParser
func InitializeLoongArchAsmParser()

//go:linkname InitializeMipsAsmParser C.LLVMInitializeMipsAsmParser
func InitializeMipsAsmParser()

//go:linkname InitializeMSP430AsmParser C.LLVMInitializeMSP430AsmParser
func InitializeMSP430AsmParser()

//go:linkname InitializePowerPCAsmParser C.LLVMInitializePowerPCAsmParser
func InitializePowerPCAsmParser()

//go:linkname InitializeRISCVAsmParser C.LLVMInitializeRISCVAsmParser
func InitializeRISCVAsmParser()

//go:linkname InitializeSparcAsmParser C.LLVMInitializeSparcAsmParser
func InitializeSparcAsmParser()

//go:linkname InitializeSystemZAsmParser C.LLVMInitializeSystemZAsmParser
func InitializeSystemZAsmParser()

//go:linkname InitializeVEAsmParser C.LLVMInitializeVEAsmParser
func InitializeVEAsmParser()

//go:linkname InitializeWebAssemblyAsmParser C.LLVMInitializeWebAssemblyAsmParser
func InitializeWebAssemblyAsmParser()

//go:linkname InitializeX86AsmParser C.LLVMInitializeX86AsmParser
func InitializeX86AsmParser()
