// Code generated by llcppg; DO NOT EDIT.

package llvm

import "github.com/goplus/lib/c"

// @defgroup LLVMCBitReader Bit Reader
// @ingroup LLVMC
//
// @{
//
// llgo:link (*OpaqueMemoryBuffer).ParseBitcode C.LLVMParseBitcode
func (self *OpaqueMemoryBuffer) ParseBitcode(OutModule *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}

// llgo:link (*OpaqueMemoryBuffer).ParseBitcode2 C.LLVMParseBitcode2
func (self *OpaqueMemoryBuffer) ParseBitcode2(OutModule *ModuleRef) Bool {
	return 0
}

// llgo:link (*OpaqueContext).ParseBitcodeInContext C.LLVMParseBitcodeInContext
func (self *OpaqueContext) ParseBitcodeInContext(MemBuf MemoryBufferRef, OutModule *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}

// llgo:link (*OpaqueContext).ParseBitcodeInContext2 C.LLVMParseBitcodeInContext2
func (self *OpaqueContext) ParseBitcodeInContext2(MemBuf MemoryBufferRef, OutModule *ModuleRef) Bool {
	return 0
}

// Reads a module from the specified path, returning via the OutMP parameter
// a module provider which performs lazy deserialization. Returns 0 on success.
// Optionally returns a human-readable error message via OutMessage.
// This is deprecated. Use LLVMGetBitcodeModuleInContext2.
//
// llgo:link (*OpaqueContext).BitcodeModuleInContext C.LLVMGetBitcodeModuleInContext
func (self *OpaqueContext) BitcodeModuleInContext(MemBuf MemoryBufferRef, OutM *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}

// Reads a module from the given memory buffer, returning via the OutMP
// parameter a module provider which performs lazy deserialization.
//
// Returns 0 on success.
//
// Takes ownership of \p MemBuf if (and only if) the module was read
// successfully.
//
// llgo:link (*OpaqueContext).BitcodeModuleInContext2 C.LLVMGetBitcodeModuleInContext2
func (self *OpaqueContext) BitcodeModuleInContext2(MemBuf MemoryBufferRef, OutM *ModuleRef) Bool {
	return 0
}

// llgo:link (*OpaqueMemoryBuffer).BitcodeModule C.LLVMGetBitcodeModule
func (self *OpaqueMemoryBuffer) BitcodeModule(OutM *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}

// llgo:link (*OpaqueMemoryBuffer).BitcodeModule2 C.LLVMGetBitcodeModule2
func (self *OpaqueMemoryBuffer) BitcodeModule2(OutM *ModuleRef) Bool {
	return 0
}
