// Code generated by llcppg; DO NOT EDIT.

package llvm

import "github.com/goplus/lib/c"

// Builds a module from the bitcode in the specified memory buffer, returning a
// reference to the module via the OutModule parameter. Returns 0 on success.
// Optionally returns a human-readable error message via OutMessage.
//
// This is deprecated. Use LLVMParseBitcode2.
//
// llgo:link MemoryBufferRef.ParseBitcode C.LLVMParseBitcode
func (self MemoryBufferRef) ParseBitcode(OutModule *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}

// Builds a module from the bitcode in the specified memory buffer, returning a
// reference to the module via the OutModule parameter. Returns 0 on success.
//
// llgo:link MemoryBufferRef.ParseBitcode2 C.LLVMParseBitcode2
func (self MemoryBufferRef) ParseBitcode2(OutModule *ModuleRef) Bool {
	return 0
}

// This is deprecated. Use LLVMParseBitcodeInContext2.
//
// llgo:link ContextRef.ParseBitcode C.LLVMParseBitcodeInContext
func (self ContextRef) ParseBitcode(MemBuf MemoryBufferRef, OutModule *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}

// llgo:link ContextRef.ParseBitcode2 C.LLVMParseBitcodeInContext2
func (self ContextRef) ParseBitcode2(MemBuf MemoryBufferRef, OutModule *ModuleRef) Bool {
	return 0
}

// Reads a module from the specified path, returning via the OutMP parameter
// a module provider which performs lazy deserialization. Returns 0 on success.
// Optionally returns a human-readable error message via OutMessage.
// This is deprecated. Use LLVMGetBitcodeModuleInContext2.
//
// llgo:link ContextRef.BitcodeModule C.LLVMGetBitcodeModuleInContext
func (self ContextRef) BitcodeModule(MemBuf MemoryBufferRef, OutM *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}

// Reads a module from the given memory buffer, returning via the OutMP
// parameter a module provider which performs lazy deserialization.
//
// Returns 0 on success.
//
// Takes ownership of \p MemBuf if (and only if) the module was read
// successfully.
//
// llgo:link ContextRef.BitcodeModuleInContext2 C.LLVMGetBitcodeModuleInContext2
func (self ContextRef) BitcodeModuleInContext2(MemBuf MemoryBufferRef, OutM *ModuleRef) Bool {
	return 0
}

// This is deprecated. Use LLVMGetBitcodeModule2.
//
// llgo:link MemoryBufferRef.BitcodeModule C.LLVMGetBitcodeModule
func (self MemoryBufferRef) BitcodeModule(OutM *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}

// llgo:link MemoryBufferRef.BitcodeModule2 C.LLVMGetBitcodeModule2
func (self MemoryBufferRef) BitcodeModule2(OutM *ModuleRef) Bool {
	return 0
}
