// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const BLAKE3_VERSION_STRING = "1.8.2"
const BLAKE3_KEY_LEN = 32
const BLAKE3_OUT_LEN = 32
const BLAKE3_BLOCK_LEN = 64
const BLAKE3_CHUNK_LEN = 1024
const BLAKE3_MAX_DEPTH = 54

// This struct is a private implementation detail. It has to be here because
// it's part of llvm_blake3_hasher below.
type Blake3ChunkState struct {
	Cv               [8]c.Uint32T
	ChunkCounter     c.Uint64T
	Buf              [64]c.Uint8T
	BufLen           c.Uint8T
	BlocksCompressed c.Uint8T
	Flags            c.Uint8T
}
type Blake3Hasher struct {
	Key        [8]c.Uint32T
	Chunk      Blake3ChunkState
	CvStackLen c.Uint8T
	CvStack    [1760]c.Uint8T
}

//go:linkname Blake3Version C.llvm_blake3_version
func Blake3Version() *c.Char

// llgo:link (*Blake3Hasher).Init C.llvm_blake3_hasher_init
func (self *Blake3Hasher) Init() {
}

// llgo:link (*Blake3Hasher).InitKeyed C.llvm_blake3_hasher_init_keyed
func (self *Blake3Hasher) InitKeyed(key *c.Uint8T) {
}

// llgo:link (*Blake3Hasher).InitDeriveKey C.llvm_blake3_hasher_init_derive_key
func (self *Blake3Hasher) InitDeriveKey(context *c.Char) {
}

// llgo:link (*Blake3Hasher).InitDeriveKeyRaw C.llvm_blake3_hasher_init_derive_key_raw
func (self *Blake3Hasher) InitDeriveKeyRaw(context unsafe.Pointer, context_len c.SizeT) {
}

// llgo:link (*Blake3Hasher).Update C.llvm_blake3_hasher_update
func (self *Blake3Hasher) Update(input unsafe.Pointer, input_len c.SizeT) {
}

// llgo:link (*Blake3Hasher).Finalize C.llvm_blake3_hasher_finalize
func (self *Blake3Hasher) Finalize(out *c.Uint8T, out_len c.SizeT) {
}

// llgo:link (*Blake3Hasher).FinalizeSeek C.llvm_blake3_hasher_finalize_seek
func (self *Blake3Hasher) FinalizeSeek(seek c.Uint64T, out *c.Uint8T, out_len c.SizeT) {
}

// llgo:link (*Blake3Hasher).Reset C.llvm_blake3_hasher_reset
func (self *Blake3Hasher) Reset() {
}
