// Code generated by llcppg; DO NOT EDIT.

package llvm

import "github.com/goplus/lib/c"

// @defgroup LLVMCCoreComdat Comdats
// @ingroup LLVMCCore
//
// @{
type ComdatSelectionKind c.Int

const (
	// < The linker may choose any COMDAT.
	AnyComdatSelectionKind ComdatSelectionKind = 0
	// < The data referenced by the COMDAT must
	// < be the same.
	ExactMatchComdatSelectionKind ComdatSelectionKind = 1
	// < The linker will choose the largest
	// < COMDAT.
	LargestComdatSelectionKind ComdatSelectionKind = 2
	// < No deduplication is performed.
	NoDeduplicateComdatSelectionKind ComdatSelectionKind = 3
	// < The data referenced by the COMDAT must be
	// < the same size.
	SameSizeComdatSelectionKind ComdatSelectionKind = 4
)

// Return the Comdat in the module with the specified name. It is created
// if it didn't already exist.
//
// @see llvm::Module::getOrInsertComdat()
//
// llgo:link (*OpaqueModule).OrInsertComdat C.LLVMGetOrInsertComdat
func (self *OpaqueModule) OrInsertComdat(Name *c.Char) ComdatRef {
	return nil
}

// Get the Comdat assigned to the given global object.
//
// @see llvm::GlobalObject::getComdat()
//
// llgo:link (*OpaqueValue).Comdat C.LLVMGetComdat
func (self *OpaqueValue) Comdat() ComdatRef {
	return nil
}

// Assign the Comdat to the given global object.
//
// @see llvm::GlobalObject::setComdat()
//
// llgo:link (*OpaqueValue).SetComdat C.LLVMSetComdat
func (self *OpaqueValue) SetComdat(C ComdatRef) {
}

// llgo:link (*Comdat).ComdatSelectionKind C.LLVMGetComdatSelectionKind
func (self *Comdat) ComdatSelectionKind() ComdatSelectionKind {
	return 0
}

// llgo:link (*Comdat).SetComdatSelectionKind C.LLVMSetComdatSelectionKind
func (self *Comdat) SetComdatSelectionKind(Kind ComdatSelectionKind) {
}
