// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// Debug info flags.
type DIFlags c.Uint

const (
	DIFlagZero                DIFlags = 0
	DIFlagPrivate             DIFlags = 1
	DIFlagProtected           DIFlags = 2
	DIFlagPublic              DIFlags = 3
	DIFlagFwdDecl             DIFlags = 4
	DIFlagAppleBlock          DIFlags = 8
	DIFlagReservedBit4        DIFlags = 16
	DIFlagVirtual             DIFlags = 32
	DIFlagArtificial          DIFlags = 64
	DIFlagExplicit            DIFlags = 128
	DIFlagPrototyped          DIFlags = 256
	DIFlagObjcClassComplete   DIFlags = 512
	DIFlagObjectPointer       DIFlags = 1024
	DIFlagVector              DIFlags = 2048
	DIFlagStaticMember        DIFlags = 4096
	DIFlagLValueReference     DIFlags = 8192
	DIFlagRValueReference     DIFlags = 16384
	DIFlagReserved            DIFlags = 32768
	DIFlagSingleInheritance   DIFlags = 65536
	DIFlagMultipleInheritance DIFlags = 131072
	DIFlagVirtualInheritance  DIFlags = 196608
	DIFlagIntroducedVirtual   DIFlags = 262144
	DIFlagBitField            DIFlags = 524288
	DIFlagNoReturn            DIFlags = 1048576
	DIFlagTypePassByValue     DIFlags = 4194304
	DIFlagTypePassByReference DIFlags = 8388608
	DIFlagEnumClass           DIFlags = 16777216
	// Deprecated.
	DIFlagFixedEnum           DIFlags = 16777216
	DIFlagThunk               DIFlags = 33554432
	DIFlagNonTrivial          DIFlags = 67108864
	DIFlagBigEndian           DIFlags = 134217728
	DIFlagLittleEndian        DIFlags = 268435456
	DIFlagIndirectVirtualBase DIFlags = 36
	DIFlagAccessibility       DIFlags = 3
	DIFlagPtrToMemberRep      DIFlags = 196608
)

// Source languages known by DWARF.
type DWARFSourceLanguage c.Uint

const (
	DWARFSourceLanguageC89       DWARFSourceLanguage = 0
	DWARFSourceLanguageC         DWARFSourceLanguage = 1
	DWARFSourceLanguageAda83     DWARFSourceLanguage = 2
	DWARFSourceLanguageCPlusPlus DWARFSourceLanguage = 3
	DWARFSourceLanguageCobol74   DWARFSourceLanguage = 4
	DWARFSourceLanguageCobol85   DWARFSourceLanguage = 5
	DWARFSourceLanguageFortran77 DWARFSourceLanguage = 6
	DWARFSourceLanguageFortran90 DWARFSourceLanguage = 7
	DWARFSourceLanguagePascal83  DWARFSourceLanguage = 8
	DWARFSourceLanguageModula2   DWARFSourceLanguage = 9
	// New in DWARF v3:
	DWARFSourceLanguageJava DWARFSourceLanguage = 10
	// New in DWARF v3:
	DWARFSourceLanguageC99 DWARFSourceLanguage = 11
	// New in DWARF v3:
	DWARFSourceLanguageAda95 DWARFSourceLanguage = 12
	// New in DWARF v3:
	DWARFSourceLanguageFortran95 DWARFSourceLanguage = 13
	// New in DWARF v3:
	DWARFSourceLanguagePLI DWARFSourceLanguage = 14
	// New in DWARF v3:
	DWARFSourceLanguageObjC DWARFSourceLanguage = 15
	// New in DWARF v3:
	DWARFSourceLanguageObjCPlusPlus DWARFSourceLanguage = 16
	// New in DWARF v3:
	DWARFSourceLanguageUPC DWARFSourceLanguage = 17
	// New in DWARF v3:
	DWARFSourceLanguageD DWARFSourceLanguage = 18
	// New in DWARF v4:
	DWARFSourceLanguagePython DWARFSourceLanguage = 19
	// New in DWARF v5:
	DWARFSourceLanguageOpenCL DWARFSourceLanguage = 20
	// New in DWARF v5:
	DWARFSourceLanguageGo DWARFSourceLanguage = 21
	// New in DWARF v5:
	DWARFSourceLanguageModula3 DWARFSourceLanguage = 22
	// New in DWARF v5:
	DWARFSourceLanguageHaskell DWARFSourceLanguage = 23
	// New in DWARF v5:
	DWARFSourceLanguageCPlusPlus03 DWARFSourceLanguage = 24
	// New in DWARF v5:
	DWARFSourceLanguageCPlusPlus11 DWARFSourceLanguage = 25
	// New in DWARF v5:
	DWARFSourceLanguageOCaml DWARFSourceLanguage = 26
	// New in DWARF v5:
	DWARFSourceLanguageRust DWARFSourceLanguage = 27
	// New in DWARF v5:
	DWARFSourceLanguageC11 DWARFSourceLanguage = 28
	// New in DWARF v5:
	DWARFSourceLanguageSwift DWARFSourceLanguage = 29
	// New in DWARF v5:
	DWARFSourceLanguageJulia DWARFSourceLanguage = 30
	// New in DWARF v5:
	DWARFSourceLanguageDylan DWARFSourceLanguage = 31
	// New in DWARF v5:
	DWARFSourceLanguageCPlusPlus14 DWARFSourceLanguage = 32
	// New in DWARF v5:
	DWARFSourceLanguageFortran03 DWARFSourceLanguage = 33
	// New in DWARF v5:
	DWARFSourceLanguageFortran08 DWARFSourceLanguage = 34
	// New in DWARF v5:
	DWARFSourceLanguageRenderScript DWARFSourceLanguage = 35
	// New in DWARF v5:
	DWARFSourceLanguageBLISS DWARFSourceLanguage = 36
	// New in DWARF v5:
	DWARFSourceLanguageKotlin DWARFSourceLanguage = 37
	// New in DWARF v5:
	DWARFSourceLanguageZig DWARFSourceLanguage = 38
	// New in DWARF v5:
	DWARFSourceLanguageCrystal DWARFSourceLanguage = 39
	// New in DWARF v5:
	DWARFSourceLanguageCPlusPlus17 DWARFSourceLanguage = 40
	// New in DWARF v5:
	DWARFSourceLanguageCPlusPlus20 DWARFSourceLanguage = 41
	// New in DWARF v5:
	DWARFSourceLanguageC17 DWARFSourceLanguage = 42
	// New in DWARF v5:
	DWARFSourceLanguageFortran18 DWARFSourceLanguage = 43
	// New in DWARF v5:
	DWARFSourceLanguageAda2005 DWARFSourceLanguage = 44
	// New in DWARF v5:
	DWARFSourceLanguageAda2012 DWARFSourceLanguage = 45
	// New in DWARF v5:
	DWARFSourceLanguageHIP DWARFSourceLanguage = 46
	// New in DWARF v5:
	DWARFSourceLanguageAssembly DWARFSourceLanguage = 47
	// New in DWARF v5:
	DWARFSourceLanguageCSharp DWARFSourceLanguage = 48
	// New in DWARF v5:
	DWARFSourceLanguageMojo DWARFSourceLanguage = 49
	// New in DWARF v5:
	DWARFSourceLanguageGLSL DWARFSourceLanguage = 50
	// New in DWARF v5:
	DWARFSourceLanguageGLSL_ES DWARFSourceLanguage = 51
	// New in DWARF v5:
	DWARFSourceLanguageHLSL DWARFSourceLanguage = 52
	// New in DWARF v5:
	DWARFSourceLanguageOpenCL_CPP DWARFSourceLanguage = 53
	// New in DWARF v5:
	DWARFSourceLanguageCPPForOpenCL DWARFSourceLanguage = 54
	// New in DWARF v5:
	DWARFSourceLanguageSYCL DWARFSourceLanguage = 55
	// New in DWARF v5:
	DWARFSourceLanguageRuby DWARFSourceLanguage = 56
	// New in DWARF v5:
	DWARFSourceLanguageMove DWARFSourceLanguage = 57
	// New in DWARF v5:
	DWARFSourceLanguageHylo DWARFSourceLanguage = 58
	// New in DWARF v5:
	DWARFSourceLanguageMetal DWARFSourceLanguage = 59
	// Vendor extensions:
	DWARFSourceLanguageMips_Assembler DWARFSourceLanguage = 60
	// Vendor extensions:
	DWARFSourceLanguageGOOGLE_RenderScript DWARFSourceLanguage = 61
	// Vendor extensions:
	DWARFSourceLanguageBORLAND_Delphi DWARFSourceLanguage = 62
)

// The amount of debug information to emit.
type DWARFEmissionKind c.Uint

const (
	DWARFEmissionNone           DWARFEmissionKind = 0
	DWARFEmissionFull           DWARFEmissionKind = 1
	DWARFEmissionLineTablesOnly DWARFEmissionKind = 2
)

// The kind of metadata nodes.
//
// NOTE: New entries should always be appended instead of matching the order
// in Metadata.def.
const (
	MDStringMetadataKind                     = 0
	ConstantAsMetadataMetadataKind           = 1
	LocalAsMetadataMetadataKind              = 2
	DistinctMDOperandPlaceholderMetadataKind = 3
	MDTupleMetadataKind                      = 4
	DILocationMetadataKind                   = 5
	DIExpressionMetadataKind                 = 6
	DIGlobalVariableExpressionMetadataKind   = 7
	GenericDINodeMetadataKind                = 8
	DISubrangeMetadataKind                   = 9
	DIEnumeratorMetadataKind                 = 10
	DIBasicTypeMetadataKind                  = 11
	DIDerivedTypeMetadataKind                = 12
	DICompositeTypeMetadataKind              = 13
	DISubroutineTypeMetadataKind             = 14
	DIFileMetadataKind                       = 15
	DICompileUnitMetadataKind                = 16
	DISubprogramMetadataKind                 = 17
	DILexicalBlockMetadataKind               = 18
	DILexicalBlockFileMetadataKind           = 19
	DINamespaceMetadataKind                  = 20
	DIModuleMetadataKind                     = 21
	DITemplateTypeParameterMetadataKind      = 22
	DITemplateValueParameterMetadataKind     = 23
	DIGlobalVariableMetadataKind             = 24
	DILocalVariableMetadataKind              = 25
	DILabelMetadataKind                      = 26
	DIObjCPropertyMetadataKind               = 27
	DIImportedEntityMetadataKind             = 28
	DIMacroMetadataKind                      = 29
	DIMacroFileMetadataKind                  = 30
	DICommonBlockMetadataKind                = 31
	DIStringTypeMetadataKind                 = 32
	DIGenericSubrangeMetadataKind            = 33
	DIArgListMetadataKind                    = 34
	DIAssignIDMetadataKind                   = 35
	DISubrangeTypeMetadataKind               = 36
	DIFixedPointTypeMetadataKind             = 37
)

// The kind of checksum to emit.
type ChecksumKind c.Uint

const (
	CSK_MD5    ChecksumKind = 0
	CSK_SHA1   ChecksumKind = 1
	CSK_SHA256 ChecksumKind = 2
)

// Describes the kind of macro declaration used for LLVMDIBuilderCreateMacro.
// @see llvm::dwarf::MacinfoRecordType
// @note Values are from DW_MACINFO_* constants in the DWARF specification.
type DWARFMacinfoRecordType c.Uint

const (
	DWARFMacinfoRecordTypeDefine    DWARFMacinfoRecordType = 1
	DWARFMacinfoRecordTypeMacro     DWARFMacinfoRecordType = 2
	DWARFMacinfoRecordTypeStartFile DWARFMacinfoRecordType = 3
	DWARFMacinfoRecordTypeEndFile   DWARFMacinfoRecordType = 4
	DWARFMacinfoRecordTypeVendorExt DWARFMacinfoRecordType = 255
)

type MetadataKind = c.Uint

// An LLVM DWARF type encoding.
type DWARFTypeEncoding = c.Uint

// The current debug metadata version number.
//
//go:linkname DebugMetadataVersion C.LLVMDebugMetadataVersion
func DebugMetadataVersion() c.Uint

// The version of debug metadata that's present in the provided \c Module.
//
// llgo:link ModuleRef.DebugMetadataVersion C.LLVMGetModuleDebugMetadataVersion
func (self ModuleRef) DebugMetadataVersion() c.Uint {
	return 0
}

// Strip debug info in the module if it exists.
// To do this, we remove all calls to the debugger intrinsics and any named
// metadata for debugging. We also remove debug locations for instructions.
// Return true if module is modified.
//
// llgo:link ModuleRef.StripModuleDebugInfo C.LLVMStripModuleDebugInfo
func (self ModuleRef) StripModuleDebugInfo() Bool {
	return 0
}

// Construct a builder for a module, and do not allow for unresolved nodes
// attached to the module.
//
// llgo:link ModuleRef.CreateDIBuilderDisallowUnresolved C.LLVMCreateDIBuilderDisallowUnresolved
func (self ModuleRef) CreateDIBuilderDisallowUnresolved() DIBuilderRef {
	return nil
}

// Construct a builder for a module and collect unresolved nodes attached
// to the module in order to resolve cycles during a call to
// \c LLVMDIBuilderFinalize.
//
// llgo:link ModuleRef.CreateDIBuilder C.LLVMCreateDIBuilder
func (self ModuleRef) CreateDIBuilder() DIBuilderRef {
	return nil
}

// Deallocates the \c DIBuilder and everything it owns.
// @note You must call \c LLVMDIBuilderFinalize before this
//
// llgo:link DIBuilderRef.Dispose C.LLVMDisposeDIBuilder
func (self DIBuilderRef) Dispose() {
}

// Construct any deferred debug info descriptors.
//
// llgo:link DIBuilderRef.Finalize C.LLVMDIBuilderFinalize
func (self DIBuilderRef) Finalize() {
}

// Finalize a specific subprogram.
// No new variables may be added to this subprogram afterwards.
//
// llgo:link DIBuilderRef.FinalizeSubprogram C.LLVMDIBuilderFinalizeSubprogram
func (self DIBuilderRef) FinalizeSubprogram(Subprogram MetadataRef) {
}

// A CompileUnit provides an anchor for all debugging
// information generated during this instance of compilation.
// \param Lang          Source programming language, eg.
//                      \c LLVMDWARFSourceLanguageC99
// \param FileRef       File info.
// \param Producer      Identify the producer of debugging information
//                      and code.  Usually this is a compiler
//                      version string.
// \param ProducerLen   The length of the C string passed to \c Producer.
// \param isOptimized   A boolean flag which indicates whether optimization
//                      is enabled or not.
// \param Flags         This string lists command line options. This
//                      string is directly embedded in debug info
//                      output which may be used by a tool
//                      analyzing generated debugging information.
// \param FlagsLen      The length of the C string passed to \c Flags.
// \param RuntimeVer    This indicates runtime version for languages like
//                      Objective-C.
// \param SplitName     The name of the file that we'll split debug info
//                      out into.
// \param SplitNameLen  The length of the C string passed to \c SplitName.
// \param Kind          The kind of debug information to generate.
// \param DWOId         The DWOId if this is a split skeleton compile unit.
// \param SplitDebugInlining    Whether to emit inline debug info.
// \param DebugInfoForProfiling Whether to emit extra debug info for
//                              profile collection.
// \param SysRoot         The Clang system root (value of -isysroot).
// \param SysRootLen      The length of the C string passed to \c SysRoot.
// \param SDK           The SDK. On Darwin, the last component of the sysroot.
// \param SDKLen        The length of the C string passed to \c SDK.
//
// llgo:link DIBuilderRef.CreateCompileUnit C.LLVMDIBuilderCreateCompileUnit
func (self DIBuilderRef) CreateCompileUnit(Lang DWARFSourceLanguage, FileRef MetadataRef, Producer *c.Char, ProducerLen c.SizeT, isOptimized Bool, Flags *c.Char, FlagsLen c.SizeT, RuntimeVer c.Uint, SplitName *c.Char, SplitNameLen c.SizeT, Kind DWARFEmissionKind, DWOId c.Uint, SplitDebugInlining Bool, DebugInfoForProfiling Bool, SysRoot *c.Char, SysRootLen c.SizeT, SDK *c.Char, SDKLen c.SizeT) MetadataRef {
	return nil
}

// Create a file descriptor to hold debugging information for a file.
// \param Builder      The \c DIBuilder.
// \param Filename     File name.
// \param FilenameLen  The length of the C string passed to \c Filename.
// \param Directory    Directory.
// \param DirectoryLen The length of the C string passed to \c Directory.
//
// llgo:link DIBuilderRef.CreateFile C.LLVMDIBuilderCreateFile
func (self DIBuilderRef) CreateFile(Filename *c.Char, FilenameLen c.SizeT, Directory *c.Char, DirectoryLen c.SizeT) MetadataRef {
	return nil
}

// Create a file descriptor to hold debugging information for a file.
// \param Builder      The \c DIBuilder.
// \param Filename     File name.
// \param FilenameLen  The length of the C string passed to \c Filename.
// \param Directory    Directory.
// \param DirectoryLen The length of the C string passed to \c Directory.
// \param ChecksumKind The kind of checksum. eg MD5, SHA256
// \param Checksum     The checksum.
// \param ChecksumLen  The length of the checksum.
// \param Souce        The embedded source.
// \param SourceLen    The length of the source.
//
// llgo:link DIBuilderRef.CreateFileWithChecksum C.LLVMDIBuilderCreateFileWithChecksum
func (self DIBuilderRef) CreateFileWithChecksum(Filename *c.Char, FilenameLen c.SizeT, Directory *c.Char, DirectoryLen c.SizeT, ChecksumKind ChecksumKind, Checksum *c.Char, ChecksumLen c.SizeT, Source *c.Char, SourceLen c.SizeT) MetadataRef {
	return nil
}

// Creates a new descriptor for a module with the specified parent scope.
// \param Builder         The \c DIBuilder.
// \param ParentScope     The parent scope containing this module declaration.
// \param Name            Module name.
// \param NameLen         The length of the C string passed to \c Name.
// \param ConfigMacros    A space-separated shell-quoted list of -D macro
// definitions as they would appear on a command line.
// \param ConfigMacrosLen The length of the C string passed to \c ConfigMacros.
// \param IncludePath     The path to the module map file.
// \param IncludePathLen  The length of the C string passed to \c IncludePath.
// \param APINotesFile    The path to an API notes file for the module.
// \param APINotesFileLen The length of the C string passed to \c APINotestFile.
//
// llgo:link DIBuilderRef.CreateModule C.LLVMDIBuilderCreateModule
func (self DIBuilderRef) CreateModule(ParentScope MetadataRef, Name *c.Char, NameLen c.SizeT, ConfigMacros *c.Char, ConfigMacrosLen c.SizeT, IncludePath *c.Char, IncludePathLen c.SizeT, APINotesFile *c.Char, APINotesFileLen c.SizeT) MetadataRef {
	return nil
}

// Creates a new descriptor for a namespace with the specified parent scope.
// \param Builder          The \c DIBuilder.
// \param ParentScope      The parent scope containing this module declaration.
// \param Name             NameSpace name.
// \param NameLen          The length of the C string passed to \c Name.
// \param ExportSymbols    Whether or not the namespace exports symbols, e.g.
//                         this is true of C++ inline namespaces.
//
// llgo:link DIBuilderRef.CreateNameSpace C.LLVMDIBuilderCreateNameSpace
func (self DIBuilderRef) CreateNameSpace(ParentScope MetadataRef, Name *c.Char, NameLen c.SizeT, ExportSymbols Bool) MetadataRef {
	return nil
}

// Create a new descriptor for the specified subprogram.
// \param Builder         The \c DIBuilder.
// \param Scope           Function scope.
// \param Name            Function name.
// \param NameLen         Length of enumeration name.
// \param LinkageName     Mangled function name.
// \param LinkageNameLen  Length of linkage name.
// \param File            File where this variable is defined.
// \param LineNo          Line number.
// \param Ty              Function type.
// \param IsLocalToUnit   True if this function is not externally visible.
// \param IsDefinition    True if this is a function definition.
// \param ScopeLine       Set to the beginning of the scope this starts
// \param Flags           E.g.: \c LLVMDIFlagLValueReference. These flags are
//                        used to emit dwarf attributes.
// \param IsOptimized     True if optimization is ON.
//
// llgo:link DIBuilderRef.CreateFunction C.LLVMDIBuilderCreateFunction
func (self DIBuilderRef) CreateFunction(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, LinkageName *c.Char, LinkageNameLen c.SizeT, File MetadataRef, LineNo c.Uint, Ty MetadataRef, IsLocalToUnit Bool, IsDefinition Bool, ScopeLine c.Uint, Flags DIFlags, IsOptimized Bool) MetadataRef {
	return nil
}

// Create a descriptor for a lexical block with the specified parent context.
// \param Builder      The \c DIBuilder.
// \param Scope        Parent lexical block.
// \param File         Source file.
// \param Line         The line in the source file.
// \param Column       The column in the source file.
//
// llgo:link DIBuilderRef.CreateLexicalBlock C.LLVMDIBuilderCreateLexicalBlock
func (self DIBuilderRef) CreateLexicalBlock(Scope MetadataRef, File MetadataRef, Line c.Uint, Column c.Uint) MetadataRef {
	return nil
}

// Create a descriptor for a lexical block with a new file attached.
// \param Builder        The \c DIBuilder.
// \param Scope          Lexical block.
// \param File           Source file.
// \param Discriminator  DWARF path discriminator value.
//
// llgo:link DIBuilderRef.CreateLexicalBlockFile C.LLVMDIBuilderCreateLexicalBlockFile
func (self DIBuilderRef) CreateLexicalBlockFile(Scope MetadataRef, File MetadataRef, Discriminator c.Uint) MetadataRef {
	return nil
}

// Create a descriptor for an imported namespace. Suitable for e.g. C++
// using declarations.
// \param Builder    The \c DIBuilder.
// \param Scope      The scope this module is imported into
// \param File       File where the declaration is located.
// \param Line       Line number of the declaration.
//
// llgo:link DIBuilderRef.CreateImportedModuleFromNamespace C.LLVMDIBuilderCreateImportedModuleFromNamespace
func (self DIBuilderRef) CreateImportedModuleFromNamespace(Scope MetadataRef, NS MetadataRef, File MetadataRef, Line c.Uint) MetadataRef {
	return nil
}

// Create a descriptor for an imported module that aliases another
// imported entity descriptor.
// \param Builder        The \c DIBuilder.
// \param Scope          The scope this module is imported into
// \param ImportedEntity Previous imported entity to alias.
// \param File           File where the declaration is located.
// \param Line           Line number of the declaration.
// \param Elements       Renamed elements.
// \param NumElements    Number of renamed elements.
//
// llgo:link DIBuilderRef.CreateImportedModuleFromAlias C.LLVMDIBuilderCreateImportedModuleFromAlias
func (self DIBuilderRef) CreateImportedModuleFromAlias(Scope MetadataRef, ImportedEntity MetadataRef, File MetadataRef, Line c.Uint, Elements *MetadataRef, NumElements c.Uint) MetadataRef {
	return nil
}

// Create a descriptor for an imported module.
// \param Builder        The \c DIBuilder.
// \param Scope          The scope this module is imported into
// \param M              The module being imported here
// \param File           File where the declaration is located.
// \param Line           Line number of the declaration.
// \param Elements       Renamed elements.
// \param NumElements    Number of renamed elements.
//
// llgo:link DIBuilderRef.CreateImportedModuleFromModule C.LLVMDIBuilderCreateImportedModuleFromModule
func (self DIBuilderRef) CreateImportedModuleFromModule(Scope MetadataRef, M MetadataRef, File MetadataRef, Line c.Uint, Elements *MetadataRef, NumElements c.Uint) MetadataRef {
	return nil
}

// Create a descriptor for an imported function, type, or variable.  Suitable
// for e.g. FORTRAN-style USE declarations.
// \param Builder        The DIBuilder.
// \param Scope          The scope this module is imported into.
// \param Decl           The declaration (or definition) of a function, type,
// or variable.
// \param File           File where the declaration is located.
// \param Line           Line number of the declaration.
// \param Name           A name that uniquely identifies this imported
// declaration.
// \param NameLen        The length of the C string passed to \c Name.
// \param Elements       Renamed elements.
// \param NumElements    Number of renamed elements.
//
// llgo:link DIBuilderRef.CreateImportedDeclaration C.LLVMDIBuilderCreateImportedDeclaration
func (self DIBuilderRef) CreateImportedDeclaration(Scope MetadataRef, Decl MetadataRef, File MetadataRef, Line c.Uint, Name *c.Char, NameLen c.SizeT, Elements *MetadataRef, NumElements c.Uint) MetadataRef {
	return nil
}

// Creates a new DebugLocation that describes a source location.
// \param Line The line in the source file.
// \param Column The column in the source file.
// \param Scope The scope in which the location resides.
// \param InlinedAt The scope where this location was inlined, if at all.
//                  (optional).
// \note If the item to which this location is attached cannot be
//       attributed to a source line, pass 0 for the line and column.
//
// llgo:link ContextRef.DIBuilderCreateDebugLocation C.LLVMDIBuilderCreateDebugLocation
func (self ContextRef) DIBuilderCreateDebugLocation(Line c.Uint, Column c.Uint, Scope MetadataRef, InlinedAt MetadataRef) MetadataRef {
	return nil
}

// Get the line number of this debug location.
// \param Location     The debug location.
//
// @see DILocation::getLine()
//
// llgo:link MetadataRef.DILocationGetLine C.LLVMDILocationGetLine
func (self MetadataRef) DILocationGetLine() c.Uint {
	return 0
}

// Get the column number of this debug location.
// \param Location     The debug location.
//
// @see DILocation::getColumn()
//
// llgo:link MetadataRef.DILocationGetColumn C.LLVMDILocationGetColumn
func (self MetadataRef) DILocationGetColumn() c.Uint {
	return 0
}

// Get the local scope associated with this debug location.
// \param Location     The debug location.
//
// @see DILocation::getScope()
//
// llgo:link MetadataRef.DILocationGetScope C.LLVMDILocationGetScope
func (self MetadataRef) DILocationGetScope() MetadataRef {
	return self
}

// Get the "inline at" location associated with this debug location.
// \param Location     The debug location.
//
// @see DILocation::getInlinedAt()
//
// llgo:link MetadataRef.DILocationGetInlinedAt C.LLVMDILocationGetInlinedAt
func (self MetadataRef) DILocationGetInlinedAt() MetadataRef {
	return self
}

// Get the metadata of the file associated with a given scope.
// \param Scope     The scope object.
//
// @see DIScope::getFile()
//
// llgo:link MetadataRef.DIScopeGetFile C.LLVMDIScopeGetFile
func (self MetadataRef) DIScopeGetFile() MetadataRef {
	return self
}

// Get the directory of a given file.
// \param File     The file object.
// \param Len      The length of the returned string.
//
// @see DIFile::getDirectory()
//
// llgo:link MetadataRef.DIFileGetDirectory C.LLVMDIFileGetDirectory
func (self MetadataRef) DIFileGetDirectory(Len *c.Uint) *c.Char {
	return nil
}

// Get the name of a given file.
// \param File     The file object.
// \param Len      The length of the returned string.
//
// @see DIFile::getFilename()
//
// llgo:link MetadataRef.DIFileGetFilename C.LLVMDIFileGetFilename
func (self MetadataRef) DIFileGetFilename(Len *c.Uint) *c.Char {
	return nil
}

// Get the source of a given file.
// \param File     The file object.
// \param Len      The length of the returned string.
//
// @see DIFile::getSource()
//
// llgo:link MetadataRef.DIFileGetSource C.LLVMDIFileGetSource
func (self MetadataRef) DIFileGetSource(Len *c.Uint) *c.Char {
	return nil
}

// Create a type array.
// \param Builder        The DIBuilder.
// \param Data           The type elements.
// \param NumElements    Number of type elements.
//
// llgo:link DIBuilderRef.OrCreateTypeArray C.LLVMDIBuilderGetOrCreateTypeArray
func (self DIBuilderRef) OrCreateTypeArray(Data *MetadataRef, NumElements c.SizeT) MetadataRef {
	return nil
}

// Create subroutine type.
// \param Builder        The DIBuilder.
// \param File            The file in which the subroutine resides.
// \param ParameterTypes  An array of subroutine parameter types. This
//                        includes return type at 0th index.
// \param NumParameterTypes The number of parameter types in \c ParameterTypes
// \param Flags           E.g.: \c LLVMDIFlagLValueReference.
//                        These flags are used to emit dwarf attributes.
//
// llgo:link DIBuilderRef.CreateSubroutineType C.LLVMDIBuilderCreateSubroutineType
func (self DIBuilderRef) CreateSubroutineType(File MetadataRef, ParameterTypes *MetadataRef, NumParameterTypes c.Uint, Flags DIFlags) MetadataRef {
	return nil
}

// Create debugging information entry for a macro.
// @param Builder         The DIBuilder.
// @param ParentMacroFile Macro parent (could be NULL).
// @param Line            Source line number where the macro is defined.
// @param RecordType      DW_MACINFO_define or DW_MACINFO_undef.
// @param Name            Macro name.
// @param NameLen         Macro name length.
// @param Value           Macro value.
// @param ValueLen        Macro value length.
//
// llgo:link DIBuilderRef.CreateMacro C.LLVMDIBuilderCreateMacro
func (self DIBuilderRef) CreateMacro(ParentMacroFile MetadataRef, Line c.Uint, RecordType DWARFMacinfoRecordType, Name *c.Char, NameLen c.SizeT, Value *c.Char, ValueLen c.SizeT) MetadataRef {
	return nil
}

// Create debugging information temporary entry for a macro file.
// List of macro node direct children will be calculated by DIBuilder,
// using the \p ParentMacroFile relationship.
// @param Builder         The DIBuilder.
// @param ParentMacroFile Macro parent (could be NULL).
// @param Line            Source line number where the macro file is included.
// @param File            File descriptor containing the name of the macro file.
//
// llgo:link DIBuilderRef.CreateTempMacroFile C.LLVMDIBuilderCreateTempMacroFile
func (self DIBuilderRef) CreateTempMacroFile(ParentMacroFile MetadataRef, Line c.Uint, File MetadataRef) MetadataRef {
	return nil
}

// Create debugging information entry for an enumerator.
// @param Builder        The DIBuilder.
// @param Name           Enumerator name.
// @param NameLen        Length of enumerator name.
// @param Value          Enumerator value.
// @param IsUnsigned     True if the value is unsigned.
//
// llgo:link DIBuilderRef.CreateEnumerator C.LLVMDIBuilderCreateEnumerator
func (self DIBuilderRef) CreateEnumerator(Name *c.Char, NameLen c.SizeT, Value c.Int64T, IsUnsigned Bool) MetadataRef {
	return nil
}

// Create debugging information entry for an enumerator of arbitrary precision.
// @param Builder        The DIBuilder.
// @param Name           Enumerator name.
// @param NameLen        Length of enumerator name.
// @param SizeInBits     Number of bits of the value.
// @param Words          The words that make up the value.
// @param IsUnsigned     True if the value is unsigned.
//
// llgo:link DIBuilderRef.CreateEnumeratorOfArbitraryPrecision C.LLVMDIBuilderCreateEnumeratorOfArbitraryPrecision
func (self DIBuilderRef) CreateEnumeratorOfArbitraryPrecision(Name *c.Char, NameLen c.SizeT, SizeInBits c.Uint64T, Words *c.Uint64T, IsUnsigned Bool) MetadataRef {
	return nil
}

// Create debugging information entry for an enumeration.
// \param Builder        The DIBuilder.
// \param Scope          Scope in which this enumeration is defined.
// \param Name           Enumeration name.
// \param NameLen        Length of enumeration name.
// \param File           File where this member is defined.
// \param LineNumber     Line number.
// \param SizeInBits     Member size.
// \param AlignInBits    Member alignment.
// \param Elements       Enumeration elements.
// \param NumElements    Number of enumeration elements.
// \param ClassTy        Underlying type of a C++11/ObjC fixed enum.
//
// llgo:link DIBuilderRef.CreateEnumerationType C.LLVMDIBuilderCreateEnumerationType
func (self DIBuilderRef) CreateEnumerationType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNumber c.Uint, SizeInBits c.Uint64T, AlignInBits c.Uint32T, Elements *MetadataRef, NumElements c.Uint, ClassTy MetadataRef) MetadataRef {
	return nil
}

// Create debugging information entry for a union.
// \param Builder      The DIBuilder.
// \param Scope        Scope in which this union is defined.
// \param Name         Union name.
// \param NameLen      Length of union name.
// \param File         File where this member is defined.
// \param LineNumber   Line number.
// \param SizeInBits   Member size.
// \param AlignInBits  Member alignment.
// \param Flags        Flags to encode member attribute, e.g. private
// \param Elements     Union elements.
// \param NumElements  Number of union elements.
// \param RunTimeLang  Optional parameter, Objective-C runtime version.
// \param UniqueId     A unique identifier for the union.
// \param UniqueIdLen  Length of unique identifier.
//
// llgo:link DIBuilderRef.CreateUnionType C.LLVMDIBuilderCreateUnionType
func (self DIBuilderRef) CreateUnionType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNumber c.Uint, SizeInBits c.Uint64T, AlignInBits c.Uint32T, Flags DIFlags, Elements *MetadataRef, NumElements c.Uint, RunTimeLang c.Uint, UniqueId *c.Char, UniqueIdLen c.SizeT) MetadataRef {
	return nil
}

// Create debugging information entry for an array.
// \param Builder      The DIBuilder.
// \param Size         Array size.
// \param AlignInBits  Alignment.
// \param Ty           Element type.
// \param Subscripts   Subscripts.
// \param NumSubscripts Number of subscripts.
//
// llgo:link DIBuilderRef.CreateArrayType C.LLVMDIBuilderCreateArrayType
func (self DIBuilderRef) CreateArrayType(Size c.Uint64T, AlignInBits c.Uint32T, Ty MetadataRef, Subscripts *MetadataRef, NumSubscripts c.Uint) MetadataRef {
	return nil
}

// Create debugging information entry for a set.
// \param Builder        The DIBuilder.
// \param Scope          The scope in which the set is defined.
// \param Name           A name that uniquely identifies this set.
// \param NameLen        The length of the C string passed to \c Name.
// \param File           File where the set is located.
// \param Line           Line number of the declaration.
// \param SizeInBits     Set size.
// \param AlignInBits    Set alignment.
// \param BaseTy         The base type of the set.
//
// llgo:link DIBuilderRef.CreateSetType C.LLVMDIBuilderCreateSetType
func (self DIBuilderRef) CreateSetType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNumber c.Uint, SizeInBits c.Uint64T, AlignInBits c.Uint32T, BaseTy MetadataRef) MetadataRef {
	return nil
}

// Create a descriptor for a subrange with dynamic bounds.
// \param Builder    The DIBuilder.
// \param Scope      The scope in which the subrange is defined.
// \param Name       A name that uniquely identifies this subrange.
// \param NameLen    The length of the C string passed to \c Name.
// \param LineNo     Line number.
// \param File       File where the subrange is located.
// \param SizeInBits Member size.
// \param AlignInBits Member alignment.
// \param Flags      Flags.
// \param BaseTy     The base type of the subrange. eg integer or enumeration
// \param LowerBound Lower bound of the subrange.
// \param UpperBound Upper bound of the subrange.
// \param Stride     Stride of the subrange.
// \param Bias       Bias of the subrange.
//
// llgo:link DIBuilderRef.CreateSubrangeType C.LLVMDIBuilderCreateSubrangeType
func (self DIBuilderRef) CreateSubrangeType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, LineNo c.Uint, File MetadataRef, SizeInBits c.Uint64T, AlignInBits c.Uint32T, Flags DIFlags, BaseTy MetadataRef, LowerBound MetadataRef, UpperBound MetadataRef, Stride MetadataRef, Bias MetadataRef) MetadataRef {
	return nil
}

// Create debugging information entry for a dynamic array.
// \param Builder      The DIBuilder.
// \param Size         Array size.
// \param AlignInBits  Alignment.
// \param Ty           Element type.
// \param Subscripts   Subscripts.
// \param NumSubscripts Number of subscripts.
// \param DataLocation DataLocation. (DIVariable, DIExpression or NULL)
// \param Associated   Associated. (DIVariable, DIExpression or NULL)
// \param Allocated    Allocated. (DIVariable, DIExpression or NULL)
// \param Rank         Rank. (DIVariable, DIExpression or NULL)
// \param BitStride    BitStride.
//
// llgo:link DIBuilderRef.CreateDynamicArrayType C.LLVMDIBuilderCreateDynamicArrayType
func (self DIBuilderRef) CreateDynamicArrayType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, LineNo c.Uint, File MetadataRef, Size c.Uint64T, AlignInBits c.Uint32T, Ty MetadataRef, Subscripts *MetadataRef, NumSubscripts c.Uint, DataLocation MetadataRef, Associated MetadataRef, Allocated MetadataRef, Rank MetadataRef, BitStride MetadataRef) MetadataRef {
	return nil
}

// Replace arrays.
//
// @see DIBuilder::replaceArrays()
//
// llgo:link DIBuilderRef.ReplaceArrays C.LLVMReplaceArrays
func (self DIBuilderRef) ReplaceArrays(T *MetadataRef, Elements *MetadataRef, NumElements c.Uint) {
}

// Create debugging information entry for a vector type.
// \param Builder      The DIBuilder.
// \param Size         Vector size.
// \param AlignInBits  Alignment.
// \param Ty           Element type.
// \param Subscripts   Subscripts.
// \param NumSubscripts Number of subscripts.
//
// llgo:link DIBuilderRef.CreateVectorType C.LLVMDIBuilderCreateVectorType
func (self DIBuilderRef) CreateVectorType(Size c.Uint64T, AlignInBits c.Uint32T, Ty MetadataRef, Subscripts *MetadataRef, NumSubscripts c.Uint) MetadataRef {
	return nil
}

// Create a DWARF unspecified type.
// \param Builder   The DIBuilder.
// \param Name      The unspecified type's name.
// \param NameLen   Length of type name.
//
// llgo:link DIBuilderRef.CreateUnspecifiedType C.LLVMDIBuilderCreateUnspecifiedType
func (self DIBuilderRef) CreateUnspecifiedType(Name *c.Char, NameLen c.SizeT) MetadataRef {
	return nil
}

// Create debugging information entry for a basic
// type.
// \param Builder     The DIBuilder.
// \param Name        Type name.
// \param NameLen     Length of type name.
// \param SizeInBits  Size of the type.
// \param Encoding    DWARF encoding code, e.g. \c LLVMDWARFTypeEncoding_float.
// \param Flags       Flags to encode optional attribute like endianity
//
// llgo:link DIBuilderRef.CreateBasicType C.LLVMDIBuilderCreateBasicType
func (self DIBuilderRef) CreateBasicType(Name *c.Char, NameLen c.SizeT, SizeInBits c.Uint64T, Encoding DWARFTypeEncoding, Flags DIFlags) MetadataRef {
	return nil
}

// Create debugging information entry for a pointer.
// \param Builder     The DIBuilder.
// \param PointeeTy         Type pointed by this pointer.
// \param SizeInBits        Size.
// \param AlignInBits       Alignment. (optional, pass 0 to ignore)
// \param AddressSpace      DWARF address space. (optional, pass 0 to ignore)
// \param Name              Pointer type name. (optional)
// \param NameLen           Length of pointer type name. (optional)
//
// llgo:link DIBuilderRef.CreatePointerType C.LLVMDIBuilderCreatePointerType
func (self DIBuilderRef) CreatePointerType(PointeeTy MetadataRef, SizeInBits c.Uint64T, AlignInBits c.Uint32T, AddressSpace c.Uint, Name *c.Char, NameLen c.SizeT) MetadataRef {
	return nil
}

// Create debugging information entry for a struct.
// \param Builder     The DIBuilder.
// \param Scope        Scope in which this struct is defined.
// \param Name         Struct name.
// \param NameLen      Struct name length.
// \param File         File where this member is defined.
// \param LineNumber   Line number.
// \param SizeInBits   Member size.
// \param AlignInBits  Member alignment.
// \param Flags        Flags to encode member attribute, e.g. private
// \param Elements     Struct elements.
// \param NumElements  Number of struct elements.
// \param RunTimeLang  Optional parameter, Objective-C runtime version.
// \param VTableHolder The object containing the vtable for the struct.
// \param UniqueId     A unique identifier for the struct.
// \param UniqueIdLen  Length of the unique identifier for the struct.
//
// llgo:link DIBuilderRef.CreateStructType C.LLVMDIBuilderCreateStructType
func (self DIBuilderRef) CreateStructType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNumber c.Uint, SizeInBits c.Uint64T, AlignInBits c.Uint32T, Flags DIFlags, DerivedFrom MetadataRef, Elements *MetadataRef, NumElements c.Uint, RunTimeLang c.Uint, VTableHolder MetadataRef, UniqueId *c.Char, UniqueIdLen c.SizeT) MetadataRef {
	return nil
}

// Create debugging information entry for a member.
// \param Builder      The DIBuilder.
// \param Scope        Member scope.
// \param Name         Member name.
// \param NameLen      Length of member name.
// \param File         File where this member is defined.
// \param LineNo       Line number.
// \param SizeInBits   Member size.
// \param AlignInBits  Member alignment.
// \param OffsetInBits Member offset.
// \param Flags        Flags to encode member attribute, e.g. private
// \param Ty           Parent type.
//
// llgo:link DIBuilderRef.CreateMemberType C.LLVMDIBuilderCreateMemberType
func (self DIBuilderRef) CreateMemberType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNo c.Uint, SizeInBits c.Uint64T, AlignInBits c.Uint32T, OffsetInBits c.Uint64T, Flags DIFlags, Ty MetadataRef) MetadataRef {
	return nil
}

// Create debugging information entry for a
// C++ static data member.
// \param Builder      The DIBuilder.
// \param Scope        Member scope.
// \param Name         Member name.
// \param NameLen      Length of member name.
// \param File         File where this member is declared.
// \param LineNumber   Line number.
// \param Type         Type of the static member.
// \param Flags        Flags to encode member attribute, e.g. private.
// \param ConstantVal  Const initializer of the member.
// \param AlignInBits  Member alignment.
//
// llgo:link DIBuilderRef.CreateStaticMemberType C.LLVMDIBuilderCreateStaticMemberType
func (self DIBuilderRef) CreateStaticMemberType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNumber c.Uint, Type MetadataRef, Flags DIFlags, ConstantVal ValueRef, AlignInBits c.Uint32T) MetadataRef {
	return nil
}

// Create debugging information entry for a pointer to member.
// \param Builder      The DIBuilder.
// \param PointeeType  Type pointed to by this pointer.
// \param ClassType    Type for which this pointer points to members of.
// \param SizeInBits   Size.
// \param AlignInBits  Alignment.
// \param Flags        Flags.
//
// llgo:link DIBuilderRef.CreateMemberPointerType C.LLVMDIBuilderCreateMemberPointerType
func (self DIBuilderRef) CreateMemberPointerType(PointeeType MetadataRef, ClassType MetadataRef, SizeInBits c.Uint64T, AlignInBits c.Uint32T, Flags DIFlags) MetadataRef {
	return nil
}

// Create debugging information entry for Objective-C instance variable.
// \param Builder      The DIBuilder.
// \param Name         Member name.
// \param NameLen      The length of the C string passed to \c Name.
// \param File         File where this member is defined.
// \param LineNo       Line number.
// \param SizeInBits   Member size.
// \param AlignInBits  Member alignment.
// \param OffsetInBits Member offset.
// \param Flags        Flags to encode member attribute, e.g. private
// \param Ty           Parent type.
// \param PropertyNode Property associated with this ivar.
//
// llgo:link DIBuilderRef.CreateObjCIVar C.LLVMDIBuilderCreateObjCIVar
func (self DIBuilderRef) CreateObjCIVar(Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNo c.Uint, SizeInBits c.Uint64T, AlignInBits c.Uint32T, OffsetInBits c.Uint64T, Flags DIFlags, Ty MetadataRef, PropertyNode MetadataRef) MetadataRef {
	return nil
}

// Create debugging information entry for Objective-C property.
// \param Builder            The DIBuilder.
// \param Name               Property name.
// \param NameLen            The length of the C string passed to \c Name.
// \param File               File where this property is defined.
// \param LineNo             Line number.
// \param GetterName         Name of the Objective C property getter selector.
// \param GetterNameLen      The length of the C string passed to \c GetterName.
// \param SetterName         Name of the Objective C property setter selector.
// \param SetterNameLen      The length of the C string passed to \c SetterName.
// \param PropertyAttributes Objective C property attributes.
// \param Ty                 Type.
//
// llgo:link DIBuilderRef.CreateObjCProperty C.LLVMDIBuilderCreateObjCProperty
func (self DIBuilderRef) CreateObjCProperty(Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNo c.Uint, GetterName *c.Char, GetterNameLen c.SizeT, SetterName *c.Char, SetterNameLen c.SizeT, PropertyAttributes c.Uint, Ty MetadataRef) MetadataRef {
	return nil
}

// Create a uniqued DIType* clone with FlagObjectPointer. If \c Implicit
// is true, then also set FlagArtificial.
// \param Builder   The DIBuilder.
// \param Type      The underlying type to which this pointer points.
// \param Implicit  Indicates whether this pointer was implicitly generated
//                  (i.e., not spelled out in source).
//
// llgo:link DIBuilderRef.CreateObjectPointerType C.LLVMDIBuilderCreateObjectPointerType
func (self DIBuilderRef) CreateObjectPointerType(Type MetadataRef, Implicit Bool) MetadataRef {
	return nil
}

// Create debugging information entry for a qualified
// type, e.g. 'const int'.
// \param Builder     The DIBuilder.
// \param Tag         Tag identifying type,
//                    e.g. LLVMDWARFTypeQualifier_volatile_type
// \param Type        Base Type.
//
// llgo:link DIBuilderRef.CreateQualifiedType C.LLVMDIBuilderCreateQualifiedType
func (self DIBuilderRef) CreateQualifiedType(Tag c.Uint, Type MetadataRef) MetadataRef {
	return nil
}

// Create debugging information entry for a c++
// style reference or rvalue reference type.
// \param Builder   The DIBuilder.
// \param Tag       Tag identifying type,
// \param Type      Base Type.
//
// llgo:link DIBuilderRef.CreateReferenceType C.LLVMDIBuilderCreateReferenceType
func (self DIBuilderRef) CreateReferenceType(Tag c.Uint, Type MetadataRef) MetadataRef {
	return nil
}

// Create C++11 nullptr type.
// \param Builder   The DIBuilder.
//
// llgo:link DIBuilderRef.CreateNullPtrType C.LLVMDIBuilderCreateNullPtrType
func (self DIBuilderRef) CreateNullPtrType() MetadataRef {
	return nil
}

// Create debugging information entry for a typedef.
// \param Builder    The DIBuilder.
// \param Type       Original type.
// \param Name       Typedef name.
// \param File       File where this type is defined.
// \param LineNo     Line number.
// \param Scope      The surrounding context for the typedef.
//
// llgo:link DIBuilderRef.CreateTypedef C.LLVMDIBuilderCreateTypedef
func (self DIBuilderRef) CreateTypedef(Type MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNo c.Uint, Scope MetadataRef, AlignInBits c.Uint32T) MetadataRef {
	return nil
}

// Create debugging information entry to establish inheritance relationship
// between two types.
// \param Builder       The DIBuilder.
// \param Ty            Original type.
// \param BaseTy        Base type. Ty is inherits from base.
// \param BaseOffset    Base offset.
// \param VBPtrOffset  Virtual base pointer offset.
// \param Flags         Flags to describe inheritance attribute, e.g. private
//
// llgo:link DIBuilderRef.CreateInheritance C.LLVMDIBuilderCreateInheritance
func (self DIBuilderRef) CreateInheritance(Ty MetadataRef, BaseTy MetadataRef, BaseOffset c.Uint64T, VBPtrOffset c.Uint32T, Flags DIFlags) MetadataRef {
	return nil
}

// Create a permanent forward-declared type.
// \param Builder             The DIBuilder.
// \param Tag                 A unique tag for this type.
// \param Name                Type name.
// \param NameLen             Length of type name.
// \param Scope               Type scope.
// \param File                File where this type is defined.
// \param Line                Line number where this type is defined.
// \param RuntimeLang         Indicates runtime version for languages like
//                            Objective-C.
// \param SizeInBits          Member size.
// \param AlignInBits         Member alignment.
// \param UniqueIdentifier    A unique identifier for the type.
// \param UniqueIdentifierLen Length of the unique identifier.
//
// llgo:link DIBuilderRef.CreateForwardDecl C.LLVMDIBuilderCreateForwardDecl
func (self DIBuilderRef) CreateForwardDecl(Tag c.Uint, Name *c.Char, NameLen c.SizeT, Scope MetadataRef, File MetadataRef, Line c.Uint, RuntimeLang c.Uint, SizeInBits c.Uint64T, AlignInBits c.Uint32T, UniqueIdentifier *c.Char, UniqueIdentifierLen c.SizeT) MetadataRef {
	return nil
}

// Create a temporary forward-declared type.
// \param Builder             The DIBuilder.
// \param Tag                 A unique tag for this type.
// \param Name                Type name.
// \param NameLen             Length of type name.
// \param Scope               Type scope.
// \param File                File where this type is defined.
// \param Line                Line number where this type is defined.
// \param RuntimeLang         Indicates runtime version for languages like
//                            Objective-C.
// \param SizeInBits          Member size.
// \param AlignInBits         Member alignment.
// \param Flags               Flags.
// \param UniqueIdentifier    A unique identifier for the type.
// \param UniqueIdentifierLen Length of the unique identifier.
//
// llgo:link DIBuilderRef.CreateReplaceableCompositeType C.LLVMDIBuilderCreateReplaceableCompositeType
func (self DIBuilderRef) CreateReplaceableCompositeType(Tag c.Uint, Name *c.Char, NameLen c.SizeT, Scope MetadataRef, File MetadataRef, Line c.Uint, RuntimeLang c.Uint, SizeInBits c.Uint64T, AlignInBits c.Uint32T, Flags DIFlags, UniqueIdentifier *c.Char, UniqueIdentifierLen c.SizeT) MetadataRef {
	return nil
}

// Create debugging information entry for a bit field member.
// \param Builder             The DIBuilder.
// \param Scope               Member scope.
// \param Name                Member name.
// \param NameLen             Length of member name.
// \param File                File where this member is defined.
// \param LineNumber          Line number.
// \param SizeInBits          Member size.
// \param OffsetInBits        Member offset.
// \param StorageOffsetInBits Member storage offset.
// \param Flags               Flags to encode member attribute.
// \param Type                Parent type.
//
// llgo:link DIBuilderRef.CreateBitFieldMemberType C.LLVMDIBuilderCreateBitFieldMemberType
func (self DIBuilderRef) CreateBitFieldMemberType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNumber c.Uint, SizeInBits c.Uint64T, OffsetInBits c.Uint64T, StorageOffsetInBits c.Uint64T, Flags DIFlags, Type MetadataRef) MetadataRef {
	return nil
}

// Create debugging information entry for a class.
// \param Scope               Scope in which this class is defined.
// \param Name                Class name.
// \param NameLen             The length of the C string passed to \c Name.
// \param File                File where this member is defined.
// \param LineNumber          Line number.
// \param SizeInBits          Member size.
// \param AlignInBits         Member alignment.
// \param OffsetInBits        Member offset.
// \param Flags               Flags to encode member attribute, e.g. private.
// \param DerivedFrom         Debug info of the base class of this type.
// \param Elements            Class members.
// \param NumElements         Number of class elements.
// \param VTableHolder        Debug info of the base class that contains vtable
//                            for this type. This is used in
//                            DW_AT_containing_type. See DWARF documentation
//                            for more info.
// \param TemplateParamsNode  Template type parameters.
// \param UniqueIdentifier    A unique identifier for the type.
// \param UniqueIdentifierLen Length of the unique identifier.
//
// llgo:link DIBuilderRef.CreateClassType C.LLVMDIBuilderCreateClassType
func (self DIBuilderRef) CreateClassType(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNumber c.Uint, SizeInBits c.Uint64T, AlignInBits c.Uint32T, OffsetInBits c.Uint64T, Flags DIFlags, DerivedFrom MetadataRef, Elements *MetadataRef, NumElements c.Uint, VTableHolder MetadataRef, TemplateParamsNode MetadataRef, UniqueIdentifier *c.Char, UniqueIdentifierLen c.SizeT) MetadataRef {
	return nil
}

// Create a uniqued DIType* clone with FlagArtificial set.
// \param Builder     The DIBuilder.
// \param Type        The underlying type.
//
// llgo:link DIBuilderRef.CreateArtificialType C.LLVMDIBuilderCreateArtificialType
func (self DIBuilderRef) CreateArtificialType(Type MetadataRef) MetadataRef {
	return nil
}

// Get the name of this DIType.
// \param DType     The DIType.
// \param Length    The length of the returned string.
//
// @see DIType::getName()
//
// llgo:link MetadataRef.DITypeGetName C.LLVMDITypeGetName
func (self MetadataRef) DITypeGetName(Length *c.SizeT) *c.Char {
	return nil
}

// Get the size of this DIType in bits.
// \param DType     The DIType.
//
// @see DIType::getSizeInBits()
//
// llgo:link MetadataRef.DITypeGetSizeInBits C.LLVMDITypeGetSizeInBits
func (self MetadataRef) DITypeGetSizeInBits() c.Uint64T {
	return 0
}

// Get the offset of this DIType in bits.
// \param DType     The DIType.
//
// @see DIType::getOffsetInBits()
//
// llgo:link MetadataRef.DITypeGetOffsetInBits C.LLVMDITypeGetOffsetInBits
func (self MetadataRef) DITypeGetOffsetInBits() c.Uint64T {
	return 0
}

// Get the alignment of this DIType in bits.
// \param DType     The DIType.
//
// @see DIType::getAlignInBits()
//
// llgo:link MetadataRef.DITypeGetAlignInBits C.LLVMDITypeGetAlignInBits
func (self MetadataRef) DITypeGetAlignInBits() c.Uint32T {
	return 0
}

// Get the source line where this DIType is declared.
// \param DType     The DIType.
//
// @see DIType::getLine()
//
// llgo:link MetadataRef.DITypeGetLine C.LLVMDITypeGetLine
func (self MetadataRef) DITypeGetLine() c.Uint {
	return 0
}

// Get the flags associated with this DIType.
// \param DType     The DIType.
//
// @see DIType::getFlags()
//
// llgo:link MetadataRef.DITypeGetFlags C.LLVMDITypeGetFlags
func (self MetadataRef) DITypeGetFlags() DIFlags {
	return 0
}

// Create a descriptor for a value range.
// \param Builder    The DIBuilder.
// \param LowerBound Lower bound of the subrange, e.g. 0 for C, 1 for Fortran.
// \param Count      Count of elements in the subrange.
//
// llgo:link DIBuilderRef.OrCreateSubrange C.LLVMDIBuilderGetOrCreateSubrange
func (self DIBuilderRef) OrCreateSubrange(LowerBound c.Int64T, Count c.Int64T) MetadataRef {
	return nil
}

// Create an array of DI Nodes.
// \param Builder        The DIBuilder.
// \param Data           The DI Node elements.
// \param NumElements    Number of DI Node elements.
//
// llgo:link DIBuilderRef.OrCreateArray C.LLVMDIBuilderGetOrCreateArray
func (self DIBuilderRef) OrCreateArray(Data *MetadataRef, NumElements c.SizeT) MetadataRef {
	return nil
}

// Create a new descriptor for the specified variable which has a complex
// address expression for its address.
// \param Builder     The DIBuilder.
// \param Addr        An array of complex address operations.
// \param Length      Length of the address operation array.
//
// llgo:link DIBuilderRef.CreateExpression C.LLVMDIBuilderCreateExpression
func (self DIBuilderRef) CreateExpression(Addr *c.Uint64T, Length c.SizeT) MetadataRef {
	return nil
}

// Create a new descriptor for the specified variable that does not have an
// address, but does have a constant value.
// \param Builder     The DIBuilder.
// \param Value       The constant value.
//
// llgo:link DIBuilderRef.CreateConstantValueExpression C.LLVMDIBuilderCreateConstantValueExpression
func (self DIBuilderRef) CreateConstantValueExpression(Value c.Uint64T) MetadataRef {
	return nil
}

// Create a new descriptor for the specified variable.
// \param Scope       Variable scope.
// \param Name        Name of the variable.
// \param NameLen     The length of the C string passed to \c Name.
// \param Linkage     Mangled  name of the variable.
// \param LinkLen     The length of the C string passed to \c Linkage.
// \param File        File where this variable is defined.
// \param LineNo      Line number.
// \param Ty          Variable Type.
// \param LocalToUnit Boolean flag indicate whether this variable is
//                    externally visible or not.
// \param Expr        The location of the global relative to the attached
//                    GlobalVariable.
// \param Decl        Reference to the corresponding declaration.
//                    variables.
// \param AlignInBits Variable alignment(or 0 if no alignment attr was
//                    specified)
//
// llgo:link DIBuilderRef.CreateGlobalVariableExpression C.LLVMDIBuilderCreateGlobalVariableExpression
func (self DIBuilderRef) CreateGlobalVariableExpression(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, Linkage *c.Char, LinkLen c.SizeT, File MetadataRef, LineNo c.Uint, Ty MetadataRef, LocalToUnit Bool, Expr MetadataRef, Decl MetadataRef, AlignInBits c.Uint32T) MetadataRef {
	return nil
}

// Get the dwarf::Tag of a DINode
//
// llgo:link MetadataRef.DINodeTag C.LLVMGetDINodeTag
func (self MetadataRef) DINodeTag() c.Uint16T {
	return 0
}

// Retrieves the \c DIVariable associated with this global variable expression.
// \param GVE    The global variable expression.
//
// @see llvm::DIGlobalVariableExpression::getVariable()
//
// llgo:link MetadataRef.DIGlobalVariableExpressionGetVariable C.LLVMDIGlobalVariableExpressionGetVariable
func (self MetadataRef) DIGlobalVariableExpressionGetVariable() MetadataRef {
	return self
}

// Retrieves the \c DIExpression associated with this global variable expression.
// \param GVE    The global variable expression.
//
// @see llvm::DIGlobalVariableExpression::getExpression()
//
// llgo:link MetadataRef.DIGlobalVariableExpressionGetExpression C.LLVMDIGlobalVariableExpressionGetExpression
func (self MetadataRef) DIGlobalVariableExpressionGetExpression() MetadataRef {
	return self
}

// Get the metadata of the file associated with a given variable.
// \param Var     The variable object.
//
// @see DIVariable::getFile()
//
// llgo:link MetadataRef.DIVariableGetFile C.LLVMDIVariableGetFile
func (self MetadataRef) DIVariableGetFile() MetadataRef {
	return self
}

// Get the metadata of the scope associated with a given variable.
// \param Var     The variable object.
//
// @see DIVariable::getScope()
//
// llgo:link MetadataRef.DIVariableGetScope C.LLVMDIVariableGetScope
func (self MetadataRef) DIVariableGetScope() MetadataRef {
	return self
}

// Get the source line where this \c DIVariable is declared.
// \param Var     The DIVariable.
//
// @see DIVariable::getLine()
//
// llgo:link MetadataRef.DIVariableGetLine C.LLVMDIVariableGetLine
func (self MetadataRef) DIVariableGetLine() c.Uint {
	return 0
}

// Create a new temporary \c MDNode.  Suitable for use in constructing cyclic
// \c MDNode structures. A temporary \c MDNode is not uniqued, may be RAUW'd,
// and must be manually deleted with \c LLVMDisposeTemporaryMDNode.
// \param Ctx            The context in which to construct the temporary node.
// \param Data           The metadata elements.
// \param NumElements    Number of metadata elements.
//
// llgo:link ContextRef.TemporaryMDNode C.LLVMTemporaryMDNode
func (self ContextRef) TemporaryMDNode(Data *MetadataRef, NumElements c.SizeT) MetadataRef {
	return nil
}

// Deallocate a temporary node.
//
// Calls \c replaceAllUsesWith(nullptr) before deleting, so any remaining
// references will be reset.
// \param TempNode    The temporary metadata node.
//
// llgo:link MetadataRef.DisposeTemporaryMDNode C.LLVMDisposeTemporaryMDNode
func (self MetadataRef) DisposeTemporaryMDNode() {
}

// Replace all uses of temporary metadata.
// \param TempTargetMetadata    The temporary metadata node.
// \param Replacement           The replacement metadata node.
//
//go:linkname MetadataReplaceAllUsesWith C.LLVMMetadataReplaceAllUsesWith
func MetadataReplaceAllUsesWith(TempTargetMetadata MetadataRef, Replacement MetadataRef)

// Create a new descriptor for the specified global variable that is temporary
// and meant to be RAUWed.
// \param Scope       Variable scope.
// \param Name        Name of the variable.
// \param NameLen     The length of the C string passed to \c Name.
// \param Linkage     Mangled  name of the variable.
// \param LnkLen      The length of the C string passed to \c Linkage.
// \param File        File where this variable is defined.
// \param LineNo      Line number.
// \param Ty          Variable Type.
// \param LocalToUnit Boolean flag indicate whether this variable is
//                    externally visible or not.
// \param Decl        Reference to the corresponding declaration.
// \param AlignInBits Variable alignment(or 0 if no alignment attr was
//                    specified)
//
// llgo:link DIBuilderRef.CreateTempGlobalVariableFwdDecl C.LLVMDIBuilderCreateTempGlobalVariableFwdDecl
func (self DIBuilderRef) CreateTempGlobalVariableFwdDecl(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, Linkage *c.Char, LnkLen c.SizeT, File MetadataRef, LineNo c.Uint, Ty MetadataRef, LocalToUnit Bool, Decl MetadataRef, AlignInBits c.Uint32T) MetadataRef {
	return nil
}

// Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
// See https://llvm.org/docs/RemoveDIsDebugInfo.html#c-api-changes
//
// The debug format can be switched later after inserting the records using
// LLVMSetIsNewDbgInfoFormat, if needed for legacy or transitionary reasons.
//
// Insert a Declare DbgRecord before the given instruction.
// \param Builder     The DIBuilder.
// \param Storage     The storage of the variable to declare.
// \param VarInfo     The variable's debug info descriptor.
// \param Expr        A complex location expression for the variable.
// \param DebugLoc    Debug info location.
// \param Instr       Instruction acting as a location for the new record.
//
// llgo:link DIBuilderRef.InsertDeclareRecordBefore C.LLVMDIBuilderInsertDeclareRecordBefore
func (self DIBuilderRef) InsertDeclareRecordBefore(Storage ValueRef, VarInfo MetadataRef, Expr MetadataRef, DebugLoc MetadataRef, Instr ValueRef) DbgRecordRef {
	return nil
}

// Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
// See https://llvm.org/docs/RemoveDIsDebugInfo.html#c-api-changes
//
// The debug format can be switched later after inserting the records using
// LLVMSetIsNewDbgInfoFormat, if needed for legacy or transitionary reasons.
//
// Insert a Declare DbgRecord at the end of the given basic block. If the basic
// block has a terminator instruction, the record is inserted before that
// terminator instruction.
// \param Builder     The DIBuilder.
// \param Storage     The storage of the variable to declare.
// \param VarInfo     The variable's debug info descriptor.
// \param Expr        A complex location expression for the variable.
// \param DebugLoc    Debug info location.
// \param Block       Basic block acting as a location for the new record.
//
// llgo:link DIBuilderRef.InsertDeclareRecordAtEnd C.LLVMDIBuilderInsertDeclareRecordAtEnd
func (self DIBuilderRef) InsertDeclareRecordAtEnd(Storage ValueRef, VarInfo MetadataRef, Expr MetadataRef, DebugLoc MetadataRef, Block BasicBlockRef) DbgRecordRef {
	return nil
}

// Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
// See https://llvm.org/docs/RemoveDIsDebugInfo.html#c-api-changes
//
// The debug format can be switched later after inserting the records using
// LLVMSetIsNewDbgInfoFormat, if needed for legacy or transitionary reasons.
//
// Insert a new debug record before the given instruction.
// \param Builder     The DIBuilder.
// \param Val         The value of the variable.
// \param VarInfo     The variable's debug info descriptor.
// \param Expr        A complex location expression for the variable.
// \param DebugLoc    Debug info location.
// \param Instr       Instruction acting as a location for the new record.
//
// llgo:link DIBuilderRef.InsertDbgValueRecordBefore C.LLVMDIBuilderInsertDbgValueRecordBefore
func (self DIBuilderRef) InsertDbgValueRecordBefore(Val ValueRef, VarInfo MetadataRef, Expr MetadataRef, DebugLoc MetadataRef, Instr ValueRef) DbgRecordRef {
	return nil
}

// Only use in "new debug format" (LLVMIsNewDbgInfoFormat() is true).
// See https://llvm.org/docs/RemoveDIsDebugInfo.html#c-api-changes
//
// The debug format can be switched later after inserting the records using
// LLVMSetIsNewDbgInfoFormat, if needed for legacy or transitionary reasons.
//
// Insert a new debug record at the end of the given basic block. If the
// basic block has a terminator instruction, the record is inserted before
// that terminator instruction.
// \param Builder     The DIBuilder.
// \param Val         The value of the variable.
// \param VarInfo     The variable's debug info descriptor.
// \param Expr        A complex location expression for the variable.
// \param DebugLoc    Debug info location.
// \param Block       Basic block acting as a location for the new record.
//
// llgo:link DIBuilderRef.InsertDbgValueRecordAtEnd C.LLVMDIBuilderInsertDbgValueRecordAtEnd
func (self DIBuilderRef) InsertDbgValueRecordAtEnd(Val ValueRef, VarInfo MetadataRef, Expr MetadataRef, DebugLoc MetadataRef, Block BasicBlockRef) DbgRecordRef {
	return nil
}

// Create a new descriptor for a local auto variable.
// \param Builder         The DIBuilder.
// \param Scope           The local scope the variable is declared in.
// \param Name            Variable name.
// \param NameLen         Length of variable name.
// \param File            File where this variable is defined.
// \param LineNo          Line number.
// \param Ty              Metadata describing the type of the variable.
// \param AlwaysPreserve  If true, this descriptor will survive optimizations.
// \param Flags           Flags.
// \param AlignInBits     Variable alignment.
//
// llgo:link DIBuilderRef.CreateAutoVariable C.LLVMDIBuilderCreateAutoVariable
func (self DIBuilderRef) CreateAutoVariable(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNo c.Uint, Ty MetadataRef, AlwaysPreserve Bool, Flags DIFlags, AlignInBits c.Uint32T) MetadataRef {
	return nil
}

// Create a new descriptor for a function parameter variable.
// \param Builder         The DIBuilder.
// \param Scope           The local scope the variable is declared in.
// \param Name            Variable name.
// \param NameLen         Length of variable name.
// \param ArgNo           Unique argument number for this variable; starts at 1.
// \param File            File where this variable is defined.
// \param LineNo          Line number.
// \param Ty              Metadata describing the type of the variable.
// \param AlwaysPreserve  If true, this descriptor will survive optimizations.
// \param Flags           Flags.
//
// llgo:link DIBuilderRef.CreateParameterVariable C.LLVMDIBuilderCreateParameterVariable
func (self DIBuilderRef) CreateParameterVariable(Scope MetadataRef, Name *c.Char, NameLen c.SizeT, ArgNo c.Uint, File MetadataRef, LineNo c.Uint, Ty MetadataRef, AlwaysPreserve Bool, Flags DIFlags) MetadataRef {
	return nil
}

// Get the metadata of the subprogram attached to a function.
//
// @see llvm::Function::getSubprogram()
//
// llgo:link ValueRef.Subprogram C.LLVMGetSubprogram
func (self ValueRef) Subprogram() MetadataRef {
	return nil
}

// Set the subprogram attached to a function.
//
// @see llvm::Function::setSubprogram()
//
// llgo:link ValueRef.SetSubprogram C.LLVMSetSubprogram
func (self ValueRef) SetSubprogram(SP MetadataRef) {
}

// Get the line associated with a given subprogram.
// \param Subprogram     The subprogram object.
//
// @see DISubprogram::getLine()
//
// llgo:link MetadataRef.DISubprogramGetLine C.LLVMDISubprogramGetLine
func (self MetadataRef) DISubprogramGetLine() c.Uint {
	return 0
}

// Replace the subprogram subroutine type.
// \param Subprogram        The subprogram object.
// \param SubroutineType    The new subroutine type.
//
// @see DISubprogram::replaceType()
//
//go:linkname DISubprogramReplaceType C.LLVMDISubprogramReplaceType
func DISubprogramReplaceType(Subprogram MetadataRef, SubroutineType MetadataRef)

// Get the debug location for the given instruction.
//
// @see llvm::Instruction::getDebugLoc()
//
// llgo:link ValueRef.InstructionGetDebugLoc C.LLVMInstructionGetDebugLoc
func (self ValueRef) InstructionGetDebugLoc() MetadataRef {
	return nil
}

// Set the debug location for the given instruction.
//
// To clear the location metadata of the given instruction, pass NULL to \p Loc.
//
// @see llvm::Instruction::setDebugLoc()
//
// llgo:link ValueRef.InstructionSetDebugLoc C.LLVMInstructionSetDebugLoc
func (self ValueRef) InstructionSetDebugLoc(Loc MetadataRef) {
}

// Create a new descriptor for a label
//
// \param Builder         The DIBuilder.
// \param Scope           The scope to create the label in.
// \param Name            Variable name.
// \param NameLen         Length of variable name.
// \param File            The file to create the label in.
// \param LineNo          Line Number.
// \param AlwaysPreserve  Preserve the label regardless of optimization.
//
// @see llvm::DIBuilder::createLabel()
//
// llgo:link DIBuilderRef.CreateLabel C.LLVMDIBuilderCreateLabel
func (self DIBuilderRef) CreateLabel(Context MetadataRef, Name *c.Char, NameLen c.SizeT, File MetadataRef, LineNo c.Uint, AlwaysPreserve Bool) MetadataRef {
	return nil
}

// Insert a new llvm.dbg.label intrinsic call
//
// \param Builder         The DIBuilder.
// \param LabelInfo       The Label's debug info descriptor
// \param Location        The debug info location
// \param InsertBefore    Location for the new intrinsic.
//
// @see llvm::DIBuilder::insertLabel()
//
// llgo:link DIBuilderRef.InsertLabelBefore C.LLVMDIBuilderInsertLabelBefore
func (self DIBuilderRef) InsertLabelBefore(LabelInfo MetadataRef, Location MetadataRef, InsertBefore ValueRef) DbgRecordRef {
	return nil
}

// Insert a new llvm.dbg.label intrinsic call
//
// \param Builder         The DIBuilder.
// \param LabelInfo       The Label's debug info descriptor
// \param Location        The debug info location
// \param InsertAtEnd     Location for the new intrinsic.
//
// @see llvm::DIBuilder::insertLabel()
//
// llgo:link DIBuilderRef.InsertLabelAtEnd C.LLVMDIBuilderInsertLabelAtEnd
func (self DIBuilderRef) InsertLabelAtEnd(LabelInfo MetadataRef, Location MetadataRef, InsertAtEnd BasicBlockRef) DbgRecordRef {
	return nil
}

// Obtain the enumerated type of a Metadata instance.
//
// @see llvm::Metadata::getMetadataID()
//
// llgo:link MetadataRef.Kind C.LLVMGetMetadataKind
func (self MetadataRef) Kind() MetadataKind {
	return 0
}
