// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const Disassembler_Option_UseMarkup = 1
const Disassembler_Option_PrintImmHex = 2
const Disassembler_Option_AsmPrinterVariant = 4
const Disassembler_Option_SetInstrComments = 8
const Disassembler_Option_PrintLatency = 16
const Disassembler_Option_Color = 32

// Create a disassembler for the TripleName.  Symbolic disassembly is supported
// by passing a block of information in the DisInfo parameter and specifying the
// TagType and callback functions as described above.  These can all be passed
// as NULL.  If successful, this returns a disassembler context.  If not, it
// returns NULL. This function is equivalent to calling
// LLVMCreateDisasmCPUFeatures() with an empty CPU name and feature set.
//
//go:linkname CreateDisasm C.LLVMCreateDisasm
func CreateDisasm(TripleName *c.Char, DisInfo unsafe.Pointer, TagType c.Int, GetOpInfo OpInfoCallback, SymbolLookUp SymbolLookupCallback) DisasmContextRef

// Create a disassembler for the TripleName and a specific CPU.  Symbolic
// disassembly is supported by passing a block of information in the DisInfo
// parameter and specifying the TagType and callback functions as described
// above.  These can all be passed * as NULL.  If successful, this returns a
// disassembler context.  If not, it returns NULL. This function is equivalent
// to calling LLVMCreateDisasmCPUFeatures() with an empty feature set.
//
//go:linkname CreateDisasmCPU C.LLVMCreateDisasmCPU
func CreateDisasmCPU(Triple *c.Char, CPU *c.Char, DisInfo unsafe.Pointer, TagType c.Int, GetOpInfo OpInfoCallback, SymbolLookUp SymbolLookupCallback) DisasmContextRef

// Create a disassembler for the TripleName, a specific CPU and specific feature
// string.  Symbolic disassembly is supported by passing a block of information
// in the DisInfo parameter and specifying the TagType and callback functions as
// described above.  These can all be passed * as NULL.  If successful, this
// returns a disassembler context.  If not, it returns NULL.
//
//go:linkname CreateDisasmCPUFeatures C.LLVMCreateDisasmCPUFeatures
func CreateDisasmCPUFeatures(Triple *c.Char, CPU *c.Char, Features *c.Char, DisInfo unsafe.Pointer, TagType c.Int, GetOpInfo OpInfoCallback, SymbolLookUp SymbolLookupCallback) DisasmContextRef

// Set the disassembler's options.  Returns 1 if it can set the Options and 0
// otherwise.
//
// llgo:link DisasmContextRef.SetDisasmOptions C.LLVMSetDisasmOptions
func (self DisasmContextRef) SetDisasmOptions(Options c.Uint64T) c.Int {
	return 0
}

// Dispose of a disassembler context.
//
// llgo:link DisasmContextRef.DisasmDispose C.LLVMDisasmDispose
func (self DisasmContextRef) DisasmDispose() {
}

// Disassemble a single instruction using the disassembler context specified in
// the parameter DC.  The bytes of the instruction are specified in the
// parameter Bytes, and contains at least BytesSize number of bytes.  The
// instruction is at the address specified by the PC parameter.  If a valid
// instruction can be disassembled, its string is returned indirectly in
// OutString whose size is specified in the parameter OutStringSize.  This
// function returns the number of bytes in the instruction or zero if there was
// no valid instruction.
//
// llgo:link DisasmContextRef.DisasmInstruction C.LLVMDisasmInstruction
func (self DisasmContextRef) DisasmInstruction(Bytes *c.Uint8T, BytesSize c.Uint64T, PC c.Uint64T, OutString *c.Char, OutStringSize c.SizeT) c.SizeT {
	return 0
}
