// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const Disassembler_VariantKind_None = 0
const Disassembler_VariantKind_ARM_HI16 = 1
const Disassembler_VariantKind_ARM_LO16 = 2
const Disassembler_VariantKind_ARM64_PAGE = 1
const Disassembler_VariantKind_ARM64_PAGEOFF = 2
const Disassembler_VariantKind_ARM64_GOTPAGE = 3
const Disassembler_VariantKind_ARM64_GOTPAGEOFF = 4
const Disassembler_VariantKind_ARM64_TLVP = 5
const Disassembler_VariantKind_ARM64_TLVOFF = 6
const Disassembler_ReferenceType_InOut_None = 0
const Disassembler_ReferenceType_In_Branch = 1
const Disassembler_ReferenceType_In_PCrel_Load = 2
const Disassembler_ReferenceType_In_ARM64_ADRP = 4294967297
const Disassembler_ReferenceType_In_ARM64_ADDXri = 4294967298
const Disassembler_ReferenceType_In_ARM64_LDRXui = 4294967299
const Disassembler_ReferenceType_In_ARM64_LDRXl = 4294967300
const Disassembler_ReferenceType_In_ARM64_ADR = 4294967301
const Disassembler_ReferenceType_Out_SymbolStub = 1
const Disassembler_ReferenceType_Out_LitPool_SymAddr = 2
const Disassembler_ReferenceType_Out_LitPool_CstrAddr = 3
const Disassembler_ReferenceType_Out_Objc_CFString_Ref = 4
const Disassembler_ReferenceType_Out_Objc_Message = 5
const Disassembler_ReferenceType_Out_Objc_Message_Ref = 6
const Disassembler_ReferenceType_Out_Objc_Selector_Ref = 7
const Disassembler_ReferenceType_Out_Objc_Class_Ref = 8
const Disassembler_ReferenceType_DeMangled_Name = 9

// An opaque reference to a disassembler context.
type DisasmContextRef uintptr

// The type for the operand information call back function.  This is called to
// get the symbolic information for an operand of an instruction.  Typically
// this is from the relocation information, symbol table, etc.  That block of
// information is saved when the disassembler context is created and passed to
// the call back in the DisInfo parameter.  The instruction containing operand
// is at the PC parameter.  For some instruction sets, there can be more than
// one operand with symbolic information.  To determine the symbolic operand
// information for each operand, the bytes for the specific operand in the
// instruction are specified by the Offset parameter and its byte widith is the
// OpSize parameter.  For instructions sets with fixed widths and one symbolic
// operand per instruction, the Offset parameter will be zero and InstSize
// parameter will be the instruction width.  The information is returned in
// TagBuf and is Triple specific with its specific information defined by the
// value of TagType for that Triple.  If symbolic information is returned the
// function * returns 1, otherwise it returns 0.
//
// llgo:type C
type OpInfoCallback = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.Uint64T, _llcppg_param3 c.Uint64T, _llcppg_param4 c.Uint64T, _llcppg_param5 c.Uint64T, _llcppg_param6 c.Int, _llcppg_param7 unsafe.Pointer) c.Int

// The initial support in LLVM MC for the most general form of a relocatable
// expression is "AddSymbol - SubtractSymbol + Offset".  For some Darwin targets
// this full form is encoded in the relocation information so that AddSymbol and
// SubtractSymbol can be link edited independent of each other.  Many other
// platforms only allow a relocatable expression of the form AddSymbol + Offset
// to be encoded.
//
// The LLVMOpInfoCallback() for the TagType value of 1 uses the struct
// LLVMOpInfo1.  The value of the relocatable expression for the operand,
// including any PC adjustment, is passed in to the call back in the Value
// field.  The symbolic information about the operand is returned using all
// the fields of the structure with the Offset of the relocatable expression
// returned in the Value field.  It is possible that some symbols in the
// relocatable expression were assembly temporary symbols, for example
// "Ldata - LpicBase + constant", and only the Values of the symbols without
// symbol names are present in the relocation information.  The VariantKind
// type is one of the Target specific #defines below and is used to print
// operands like "_foo@GOT", ":lower16:_foo", etc.
type OpInfoSymbol1 struct {
	Present c.Uint64T
	Name    *c.Char
	Value   c.Uint64T
}
type OpInfo1 struct {
	AddSymbol      OpInfoSymbol1
	SubtractSymbol OpInfoSymbol1
	Value          c.Uint64T
	VariantKind    c.Uint64T
}

// The type for the symbol lookup function.  This may be called by the
// disassembler for things like adding a comment for a PC plus a constant
// offset load instruction to use a symbol name instead of a load address value.
// It is passed the block information is saved when the disassembler context is
// created and the ReferenceValue to look up as a symbol.  If no symbol is found
// for the ReferenceValue NULL is returned.  The ReferenceType of the
// instruction is passed indirectly as is the PC of the instruction in
// ReferencePC.  If the output reference can be determined its type is returned
// indirectly in ReferenceType along with ReferenceName if any, or that is set
// to NULL.
//
// llgo:type C
type SymbolLookupCallback = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.Uint64T, _llcppg_param3 *c.Uint64T, _llcppg_param4 c.Uint64T, _llcppg_param5 **c.Char) *c.Char
