// Code generated by llcppg; DO NOT EDIT.

package llvm

import _ "unsafe"

//go:linkname InitializeAArch64Disassembler C.LLVMInitializeAArch64Disassembler
func InitializeAArch64Disassembler()

//go:linkname InitializeAMDGPUDisassembler C.LLVMInitializeAMDGPUDisassembler
func InitializeAMDGPUDisassembler()

//go:linkname InitializeARMDisassembler C.LLVMInitializeARMDisassembler
func InitializeARMDisassembler()

//go:linkname InitializeAVRDisassembler C.LLVMInitializeAVRDisassembler
func InitializeAVRDisassembler()

//go:linkname InitializeBPFDisassembler C.LLVMInitializeBPFDisassembler
func InitializeBPFDisassembler()

//go:linkname InitializeHexagonDisassembler C.LLVMInitializeHexagonDisassembler
func InitializeHexagonDisassembler()

//go:linkname InitializeLanaiDisassembler C.LLVMInitializeLanaiDisassembler
func InitializeLanaiDisassembler()

//go:linkname InitializeLoongArchDisassembler C.LLVMInitializeLoongArchDisassembler
func InitializeLoongArchDisassembler()

//go:linkname InitializeMipsDisassembler C.LLVMInitializeMipsDisassembler
func InitializeMipsDisassembler()

//go:linkname InitializeMSP430Disassembler C.LLVMInitializeMSP430Disassembler
func InitializeMSP430Disassembler()

//go:linkname InitializePowerPCDisassembler C.LLVMInitializePowerPCDisassembler
func InitializePowerPCDisassembler()

//go:linkname InitializeRISCVDisassembler C.LLVMInitializeRISCVDisassembler
func InitializeRISCVDisassembler()

//go:linkname InitializeSparcDisassembler C.LLVMInitializeSparcDisassembler
func InitializeSparcDisassembler()

//go:linkname InitializeSystemZDisassembler C.LLVMInitializeSystemZDisassembler
func InitializeSystemZDisassembler()

//go:linkname InitializeVEDisassembler C.LLVMInitializeVEDisassembler
func InitializeVEDisassembler()

//go:linkname InitializeWebAssemblyDisassembler C.LLVMInitializeWebAssemblyDisassembler
func InitializeWebAssemblyDisassembler()

//go:linkname InitializeX86Disassembler C.LLVMInitializeX86Disassembler
func InitializeX86Disassembler()

//go:linkname InitializeXCoreDisassembler C.LLVMInitializeXCoreDisassembler
func InitializeXCoreDisassembler()
