// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

const ErrorSuccess = 0

type OpaqueError struct {
}

// Opaque reference to an error instance. Null serves as the 'success' value.
type ErrorRef = *OpaqueError

// Error type identifier.
type ErrorTypeId uintptr

// Returns the type id for the given error instance, which must be a failure
// value (i.e. non-null).
//
// llgo:link (*OpaqueError).ErrorTypeId C.LLVMGetErrorTypeId
func (self *OpaqueError) ErrorTypeId() ErrorTypeId {
	return 0
}

// Dispose of the given error without handling it. This operation consumes the
// error, and the given LLVMErrorRef value is not usable once this call returns.
// Note: This method *only* needs to be called if the error is not being passed
// to some other consuming operation, e.g. LLVMGetErrorMessage.
//
// llgo:link (*OpaqueError).ConsumeError C.LLVMConsumeError
func (self *OpaqueError) ConsumeError() {
}

// Report a fatal error if Err is a failure value.
//
// This function can be used to wrap calls to fallible functions ONLY when it is
// known that the Error will always be a success value.
//
// llgo:link (*OpaqueError).CantFail C.LLVMCantFail
func (self *OpaqueError) CantFail() {
}

// Returns the given string's error message. This operation consumes the error,
// and the given LLVMErrorRef value is not usable once this call returns.
// The caller is responsible for disposing of the string by calling
// LLVMDisposeErrorMessage.
//
// llgo:link (*OpaqueError).ErrorMessage C.LLVMGetErrorMessage
func (self *OpaqueError) ErrorMessage() *c.Char {
	return nil
}

// Dispose of the given error message.
//
//go:linkname DisposeErrorMessage C.LLVMDisposeErrorMessage
func DisposeErrorMessage(ErrMsg *c.Char)

// Returns the type id for llvm StringError.
//
//go:linkname GetStringErrorTypeId C.LLVMGetStringErrorTypeId
func GetStringErrorTypeId() ErrorTypeId

// Create a StringError.
//
//go:linkname CreateStringError C.LLVMCreateStringError
func CreateStringError(ErrMsg *c.Char) ErrorRef
