// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// @addtogroup LLVMCError
//
// @{
//
// llgo:type C
type FatalErrorHandler = func(_llcppg_param1 *c.Char)

// Install a fatal error handler. By default, if LLVM detects a fatal error, it
// will call exit(1). This may not be appropriate in many contexts. For example,
// doing exit(1) will bypass many crash reporting/tracing system tools. This
// function allows you to install a callback that will be invoked prior to the
// call to exit(1).
//
//go:linkname InstallFatalErrorHandler C.LLVMInstallFatalErrorHandler
func InstallFatalErrorHandler(Handler FatalErrorHandler)

// Reset the fatal error handler. This resets LLVM's fatal error handling
// behavior to the default.
//
//go:linkname ResetFatalErrorHandler C.LLVMResetFatalErrorHandler
func ResetFatalErrorHandler()

// Enable LLVM's built-in stack trace code. This intercepts the OS's crash
// signals and prints which component of LLVM you were in at the time if the
// crash.
//
//go:linkname EnablePrettyStackTrace C.LLVMEnablePrettyStackTrace
func EnablePrettyStackTrace()
