// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type OpaqueGenericValue struct {
}
type GenericValueRef = *OpaqueGenericValue
type OpaqueExecutionEngine struct {
}
type ExecutionEngineRef = *OpaqueExecutionEngine
type OpaqueMCJITMemoryManager struct {
}
type MCJITMemoryManagerRef = *OpaqueMCJITMemoryManager
type MCJITCompilerOptions struct {
	OptLevel           c.Uint
	CodeModel          CodeModel
	NoFramePointerElim Bool
	EnableFastISel     Bool
	MCJMM              MCJITMemoryManagerRef
}

// ===-- Operations on memory managers -------------------------------------===
//
// llgo:type C
type MemoryManagerAllocateCodeSectionCallback = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.UintptrT, _llcppg_param3 c.Uint, _llcppg_param4 c.Uint, _llcppg_param5 *c.Char) *c.Uint8T

// llgo:type C
type MemoryManagerAllocateDataSectionCallback = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.UintptrT, _llcppg_param3 c.Uint, _llcppg_param4 c.Uint, _llcppg_param5 *c.Char, _llcppg_param6 Bool) *c.Uint8T

// llgo:type C
type MemoryManagerFinalizeMemoryCallback = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 **c.Char) Bool

// llgo:type C
type MemoryManagerDestroyCallback = func(_llcppg_param1 unsafe.Pointer)

// Empty function used to force the linker to link MCJIT.
// Has no effect when called on a pre-built library (dylib interface).
//
//go:linkname LinkInMCJIT C.LLVMLinkInMCJIT
func LinkInMCJIT()

// Empty function used to force the linker to link the LLVM interpreter.
// Has no effect when called on a pre-built library (dylib interface).
//
//go:linkname LinkInInterpreter C.LLVMLinkInInterpreter
func LinkInInterpreter()

// ===-- Operations on generic values --------------------------------------===
//
// llgo:link TypeRef.CreateGenericValueOfInt C.LLVMCreateGenericValueOfInt
func (self TypeRef) CreateGenericValueOfInt(N c.UlongLong, IsSigned Bool) GenericValueRef {
	return nil
}

//go:linkname CreateGenericValueOfPointer C.LLVMCreateGenericValueOfPointer
func CreateGenericValueOfPointer(P unsafe.Pointer) GenericValueRef

// llgo:link TypeRef.CreateGenericValueOfFloat C.LLVMCreateGenericValueOfFloat
func (self TypeRef) CreateGenericValueOfFloat(N c.Double) GenericValueRef {
	return nil
}

// llgo:link GenericValueRef.IntWidth C.LLVMGenericValueIntWidth
func (self GenericValueRef) IntWidth() c.Uint {
	return 0
}

// llgo:link GenericValueRef.ToInt C.LLVMGenericValueToInt
func (self GenericValueRef) ToInt(IsSigned Bool) c.UlongLong {
	return 0
}

// llgo:link GenericValueRef.ToPointer C.LLVMGenericValueToPointer
func (self GenericValueRef) ToPointer() unsafe.Pointer {
	return nil
}

// llgo:link TypeRef.GenericValueToFloat C.LLVMGenericValueToFloat
func (self TypeRef) GenericValueToFloat(GenVal GenericValueRef) c.Double {
	return 0
}

// llgo:link GenericValueRef.Dispose C.LLVMDisposeGenericValue
func (self GenericValueRef) Dispose() {
}

// ===-- Operations on execution engines -----------------------------------===
//
//go:linkname CreateExecutionEngineForModule C.LLVMCreateExecutionEngineForModule
func CreateExecutionEngineForModule(OutEE *ExecutionEngineRef, M ModuleRef, OutError **c.Char) Bool

//go:linkname CreateInterpreterForModule C.LLVMCreateInterpreterForModule
func CreateInterpreterForModule(OutInterp *ExecutionEngineRef, M ModuleRef, OutError **c.Char) Bool

//go:linkname CreateJITCompilerForModule C.LLVMCreateJITCompilerForModule
func CreateJITCompilerForModule(OutJIT *ExecutionEngineRef, M ModuleRef, OptLevel c.Uint, OutError **c.Char) Bool

// llgo:link (*MCJITCompilerOptions).Initialize C.LLVMInitializeMCJITCompilerOptions
func (self *MCJITCompilerOptions) Initialize(SizeOfOptions c.SizeT) {
}

// Create an MCJIT execution engine for a module, with the given options. It is
// the responsibility of the caller to ensure that all fields in Options up to
// the given SizeOfOptions are initialized. It is correct to pass a smaller
// value of SizeOfOptions that omits some fields. The canonical way of using
// this is:
//
// LLVMMCJITCompilerOptions options;
// LLVMInitializeMCJITCompilerOptions(&options, sizeof(options));
// ... fill in those options you care about
// LLVMCreateMCJITCompilerForModule(&jit, mod, &options, sizeof(options),
//                                  &error);
//
// Note that this is also correct, though possibly suboptimal:
//
// LLVMCreateMCJITCompilerForModule(&jit, mod, 0, 0, &error);
//
//go:linkname CreateMCJITCompilerForModule C.LLVMCreateMCJITCompilerForModule
func CreateMCJITCompilerForModule(OutJIT *ExecutionEngineRef, M ModuleRef, Options *MCJITCompilerOptions, SizeOfOptions c.SizeT, OutError **c.Char) Bool

// llgo:link ExecutionEngineRef.Dispose C.LLVMDisposeExecutionEngine
func (self ExecutionEngineRef) Dispose() {
}

// llgo:link ExecutionEngineRef.RunStaticConstructors C.LLVMRunStaticConstructors
func (self ExecutionEngineRef) RunStaticConstructors() {
}

// llgo:link ExecutionEngineRef.RunStaticDestructors C.LLVMRunStaticDestructors
func (self ExecutionEngineRef) RunStaticDestructors() {
}

// llgo:link ExecutionEngineRef.RunFunctionAsMain C.LLVMRunFunctionAsMain
func (self ExecutionEngineRef) RunFunctionAsMain(F ValueRef, ArgC c.Uint, ArgV **c.Char, EnvP **c.Char) c.Int {
	return 0
}

// llgo:link ExecutionEngineRef.RunFunction C.LLVMRunFunction
func (self ExecutionEngineRef) RunFunction(F ValueRef, NumArgs c.Uint, Args *GenericValueRef) GenericValueRef {
	return nil
}

// llgo:link ExecutionEngineRef.FreeMachineCodeForFunction C.LLVMFreeMachineCodeForFunction
func (self ExecutionEngineRef) FreeMachineCodeForFunction(F ValueRef) {
}

// llgo:link ExecutionEngineRef.AddModule C.LLVMAddModule
func (self ExecutionEngineRef) AddModule(M ModuleRef) {
}

// llgo:link ExecutionEngineRef.RemoveModule C.LLVMRemoveModule
func (self ExecutionEngineRef) RemoveModule(M ModuleRef, OutMod *ModuleRef, OutError **c.Char) Bool {
	return 0
}

// llgo:link ExecutionEngineRef.FindFunction C.LLVMFindFunction
func (self ExecutionEngineRef) FindFunction(Name *c.Char, OutFn *ValueRef) Bool {
	return 0
}

// llgo:link ExecutionEngineRef.RecompileAndRelinkFunction C.LLVMRecompileAndRelinkFunction
func (self ExecutionEngineRef) RecompileAndRelinkFunction(Fn ValueRef) unsafe.Pointer {
	return nil
}

// llgo:link ExecutionEngineRef.TargetData C.LLVMGetExecutionEngineTargetData
func (self ExecutionEngineRef) TargetData() TargetDataRef {
	return nil
}

// llgo:link ExecutionEngineRef.TargetMachine C.LLVMGetExecutionEngineTargetMachine
func (self ExecutionEngineRef) TargetMachine() TargetMachineRef {
	return nil
}

// llgo:link ExecutionEngineRef.AddGlobalMapping C.LLVMAddGlobalMapping
func (self ExecutionEngineRef) AddGlobalMapping(Global ValueRef, Addr unsafe.Pointer) {
}

// llgo:link ExecutionEngineRef.PointerToGlobal C.LLVMGetPointerToGlobal
func (self ExecutionEngineRef) PointerToGlobal(Global ValueRef) unsafe.Pointer {
	return nil
}

// llgo:link ExecutionEngineRef.GlobalValueAddress C.LLVMGetGlobalValueAddress
func (self ExecutionEngineRef) GlobalValueAddress(Name *c.Char) c.Uint64T {
	return 0
}

// llgo:link ExecutionEngineRef.FunctionAddress C.LLVMGetFunctionAddress
func (self ExecutionEngineRef) FunctionAddress(Name *c.Char) c.Uint64T {
	return 0
}

// Returns true on error, false on success. If true is returned then the error
// message is copied to OutStr and cleared in the ExecutionEngine instance.
//
// llgo:link ExecutionEngineRef.ErrMsg C.LLVMExecutionEngineGetErrMsg
func (self ExecutionEngineRef) ErrMsg(OutError **c.Char) Bool {
	return 0
}

// Create a simple custom MCJIT memory manager. This memory manager can
// intercept allocations in a module-oblivious way. This will return NULL
// if any of the passed functions are NULL.
//
// @param Opaque An opaque client object to pass back to the callbacks.
// @param AllocateCodeSection Allocate a block of memory for executable code.
// @param AllocateDataSection Allocate a block of memory for data.
// @param FinalizeMemory Set page permissions and flush cache. Return 0 on
//   success, 1 on error.
//
//go:linkname CreateSimpleMCJITMemoryManager C.LLVMCreateSimpleMCJITMemoryManager
func CreateSimpleMCJITMemoryManager(Opaque unsafe.Pointer, AllocateCodeSection MemoryManagerAllocateCodeSectionCallback, AllocateDataSection MemoryManagerAllocateDataSectionCallback, FinalizeMemory MemoryManagerFinalizeMemoryCallback, Destroy MemoryManagerDestroyCallback) MCJITMemoryManagerRef

// llgo:link MCJITMemoryManagerRef.Dispose C.LLVMDisposeMCJITMemoryManager
func (self MCJITMemoryManagerRef) Dispose() {
}

// ===-- JIT Event Listener functions -------------------------------------===
//
//go:linkname CreateGDBRegistrationListener C.LLVMCreateGDBRegistrationListener
func CreateGDBRegistrationListener() JITEventListenerRef

//go:linkname CreateIntelJITEventListener C.LLVMCreateIntelJITEventListener
func CreateIntelJITEventListener() JITEventListenerRef

//go:linkname CreateOProfileJITEventListener C.LLVMCreateOProfileJITEventListener
func CreateOProfileJITEventListener() JITEventListenerRef

//go:linkname CreatePerfJITEventListener C.LLVMCreatePerfJITEventListener
func CreatePerfJITEventListener() JITEventListenerRef
