// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

type OpaqueGenericValue struct {
}
type GenericValueRef = *OpaqueGenericValue
type OpaqueExecutionEngine struct {
}
type ExecutionEngineRef = *OpaqueExecutionEngine
type OpaqueMCJITMemoryManager struct {
}
type MCJITMemoryManagerRef = *OpaqueMCJITMemoryManager
type MCJITCompilerOptions struct {
	OptLevel           c.Uint
	CodeModel          CodeModel
	NoFramePointerElim Bool
	EnableFastISel     Bool
	MCJMM              MCJITMemoryManagerRef
}

// llgo:type C
type MemoryManagerAllocateCodeSectionCallback = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.UintptrT, _llcppg_param3 c.Uint, _llcppg_param4 c.Uint, _llcppg_param5 *c.Char) *c.Uint8T

// llgo:type C
type MemoryManagerAllocateDataSectionCallback = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 c.UintptrT, _llcppg_param3 c.Uint, _llcppg_param4 c.Uint, _llcppg_param5 *c.Char, _llcppg_param6 Bool) *c.Uint8T

// llgo:type C
type MemoryManagerFinalizeMemoryCallback = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 **c.Char) Bool

// llgo:type C
type MemoryManagerDestroyCallback = func(_llcppg_param1 unsafe.Pointer)

// Empty function used to force the linker to link MCJIT.
// Has no effect when called on a pre-built library (dylib interface).
//
//go:linkname LinkInMCJIT C.LLVMLinkInMCJIT
func LinkInMCJIT()

// Empty function used to force the linker to link the LLVM interpreter.
// Has no effect when called on a pre-built library (dylib interface).
//
//go:linkname LinkInInterpreter C.LLVMLinkInInterpreter
func LinkInInterpreter()

// llgo:link (*OpaqueType).CreateGenericValueOfInt C.LLVMCreateGenericValueOfInt
func (self *OpaqueType) CreateGenericValueOfInt(N c.UlongLong, IsSigned Bool) GenericValueRef {
	return nil
}

//go:linkname CreateGenericValueOfPointer C.LLVMCreateGenericValueOfPointer
func CreateGenericValueOfPointer(P unsafe.Pointer) GenericValueRef

// llgo:link (*OpaqueType).CreateGenericValueOfFloat C.LLVMCreateGenericValueOfFloat
func (self *OpaqueType) CreateGenericValueOfFloat(N c.Double) GenericValueRef {
	return nil
}

// llgo:link (*OpaqueGenericValue).GenericValueIntWidth C.LLVMGenericValueIntWidth
func (self *OpaqueGenericValue) GenericValueIntWidth() c.Uint {
	return 0
}

// llgo:link (*OpaqueGenericValue).GenericValueToInt C.LLVMGenericValueToInt
func (self *OpaqueGenericValue) GenericValueToInt(IsSigned Bool) c.UlongLong {
	return 0
}

// llgo:link (*OpaqueGenericValue).GenericValueToPointer C.LLVMGenericValueToPointer
func (self *OpaqueGenericValue) GenericValueToPointer() unsafe.Pointer {
	return nil
}

// llgo:link (*OpaqueType).GenericValueToFloat C.LLVMGenericValueToFloat
func (self *OpaqueType) GenericValueToFloat(GenVal GenericValueRef) c.Double {
	return 0
}

// llgo:link (*OpaqueGenericValue).DisposeGenericValue C.LLVMDisposeGenericValue
func (self *OpaqueGenericValue) DisposeGenericValue() {
}

// llgo:link (*OpaqueExecutionEngine).CreateExecutionEngineForModule C.LLVMCreateExecutionEngineForModule
func (self *OpaqueExecutionEngine) CreateExecutionEngineForModule(M ModuleRef, OutError **c.Char) Bool {
	return 0
}

// llgo:link (*OpaqueExecutionEngine).CreateInterpreterForModule C.LLVMCreateInterpreterForModule
func (self *OpaqueExecutionEngine) CreateInterpreterForModule(M ModuleRef, OutError **c.Char) Bool {
	return 0
}

// llgo:link (*OpaqueExecutionEngine).CreateJITCompilerForModule C.LLVMCreateJITCompilerForModule
func (self *OpaqueExecutionEngine) CreateJITCompilerForModule(M ModuleRef, OptLevel c.Uint, OutError **c.Char) Bool {
	return 0
}

// llgo:link (*MCJITCompilerOptions).Initialize C.LLVMInitializeMCJITCompilerOptions
func (self *MCJITCompilerOptions) Initialize(SizeOfOptions c.SizeT) {
}

// Create an MCJIT execution engine for a module, with the given options. It is
// the responsibility of the caller to ensure that all fields in Options up to
// the given SizeOfOptions are initialized. It is correct to pass a smaller
// value of SizeOfOptions that omits some fields. The canonical way of using
// this is:
//
// LLVMMCJITCompilerOptions options;
// LLVMInitializeMCJITCompilerOptions(&options, sizeof(options));
// ... fill in those options you care about
// LLVMCreateMCJITCompilerForModule(&jit, mod, &options, sizeof(options),
//                                  &error);
//
// Note that this is also correct, though possibly suboptimal:
//
// LLVMCreateMCJITCompilerForModule(&jit, mod, 0, 0, &error);
//
// llgo:link (*OpaqueExecutionEngine).CreateMCJITCompilerForModule C.LLVMCreateMCJITCompilerForModule
func (self *OpaqueExecutionEngine) CreateMCJITCompilerForModule(M ModuleRef, Options *MCJITCompilerOptions, SizeOfOptions c.SizeT, OutError **c.Char) Bool {
	return 0
}

// llgo:link (*OpaqueExecutionEngine).DisposeExecutionEngine C.LLVMDisposeExecutionEngine
func (self *OpaqueExecutionEngine) DisposeExecutionEngine() {
}

// llgo:link (*OpaqueExecutionEngine).RunStaticConstructors C.LLVMRunStaticConstructors
func (self *OpaqueExecutionEngine) RunStaticConstructors() {
}

// llgo:link (*OpaqueExecutionEngine).RunStaticDestructors C.LLVMRunStaticDestructors
func (self *OpaqueExecutionEngine) RunStaticDestructors() {
}

// llgo:link (*OpaqueExecutionEngine).RunFunctionAsMain C.LLVMRunFunctionAsMain
func (self *OpaqueExecutionEngine) RunFunctionAsMain(F ValueRef, ArgC c.Uint, ArgV **c.Char, EnvP **c.Char) c.Int {
	return 0
}

// llgo:link (*OpaqueExecutionEngine).RunFunction C.LLVMRunFunction
func (self *OpaqueExecutionEngine) RunFunction(F ValueRef, NumArgs c.Uint, Args *GenericValueRef) GenericValueRef {
	return nil
}

// llgo:link (*OpaqueExecutionEngine).FreeMachineCodeForFunction C.LLVMFreeMachineCodeForFunction
func (self *OpaqueExecutionEngine) FreeMachineCodeForFunction(F ValueRef) {
}

// llgo:link (*OpaqueExecutionEngine).AddModule C.LLVMAddModule
func (self *OpaqueExecutionEngine) AddModule(M ModuleRef) {
}

// llgo:link (*OpaqueExecutionEngine).RemoveModule C.LLVMRemoveModule
func (self *OpaqueExecutionEngine) RemoveModule(M ModuleRef, OutMod *ModuleRef, OutError **c.Char) Bool {
	return 0
}

// llgo:link (*OpaqueExecutionEngine).FindFunction C.LLVMFindFunction
func (self *OpaqueExecutionEngine) FindFunction(Name *c.Char, OutFn *ValueRef) Bool {
	return 0
}

// llgo:link (*OpaqueExecutionEngine).RecompileAndRelinkFunction C.LLVMRecompileAndRelinkFunction
func (self *OpaqueExecutionEngine) RecompileAndRelinkFunction(Fn ValueRef) unsafe.Pointer {
	return nil
}

// llgo:link (*OpaqueExecutionEngine).ExecutionEngineTargetData C.LLVMGetExecutionEngineTargetData
func (self *OpaqueExecutionEngine) ExecutionEngineTargetData() TargetDataRef {
	return nil
}

// llgo:link (*OpaqueExecutionEngine).ExecutionEngineTargetMachine C.LLVMGetExecutionEngineTargetMachine
func (self *OpaqueExecutionEngine) ExecutionEngineTargetMachine() TargetMachineRef {
	return nil
}

// llgo:link (*OpaqueExecutionEngine).AddGlobalMapping C.LLVMAddGlobalMapping
func (self *OpaqueExecutionEngine) AddGlobalMapping(Global ValueRef, Addr unsafe.Pointer) {
}

// llgo:link (*OpaqueExecutionEngine).PointerToGlobal C.LLVMGetPointerToGlobal
func (self *OpaqueExecutionEngine) PointerToGlobal(Global ValueRef) unsafe.Pointer {
	return nil
}

// llgo:link (*OpaqueExecutionEngine).GlobalValueAddress C.LLVMGetGlobalValueAddress
func (self *OpaqueExecutionEngine) GlobalValueAddress(Name *c.Char) c.Uint64T {
	return 0
}

// llgo:link (*OpaqueExecutionEngine).FunctionAddress C.LLVMGetFunctionAddress
func (self *OpaqueExecutionEngine) FunctionAddress(Name *c.Char) c.Uint64T {
	return 0
}

// Returns true on error, false on success. If true is returned then the error
// message is copied to OutStr and cleared in the ExecutionEngine instance.
//
// llgo:link (*OpaqueExecutionEngine).ExecutionEngineGetErrMsg C.LLVMExecutionEngineGetErrMsg
func (self *OpaqueExecutionEngine) ExecutionEngineGetErrMsg(OutError **c.Char) Bool {
	return 0
}

// Create a simple custom MCJIT memory manager. This memory manager can
// intercept allocations in a module-oblivious way. This will return NULL
// if any of the passed functions are NULL.
//
// @param Opaque An opaque client object to pass back to the callbacks.
// @param AllocateCodeSection Allocate a block of memory for executable code.
// @param AllocateDataSection Allocate a block of memory for data.
// @param FinalizeMemory Set page permissions and flush cache. Return 0 on
//   success, 1 on error.
//
//go:linkname CreateSimpleMCJITMemoryManager C.LLVMCreateSimpleMCJITMemoryManager
func CreateSimpleMCJITMemoryManager(Opaque unsafe.Pointer, AllocateCodeSection MemoryManagerAllocateCodeSectionCallback, AllocateDataSection MemoryManagerAllocateDataSectionCallback, FinalizeMemory MemoryManagerFinalizeMemoryCallback, Destroy MemoryManagerDestroyCallback) MCJITMemoryManagerRef

// llgo:link (*OpaqueMCJITMemoryManager).DisposeMCJITMemoryManager C.LLVMDisposeMCJITMemoryManager
func (self *OpaqueMCJITMemoryManager) DisposeMCJITMemoryManager() {
}

//go:linkname CreateGDBRegistrationListener C.LLVMCreateGDBRegistrationListener
func CreateGDBRegistrationListener() JITEventListenerRef

//go:linkname CreateIntelJITEventListener C.LLVMCreateIntelJITEventListener
func CreateIntelJITEventListener() JITEventListenerRef

//go:linkname CreateOProfileJITEventListener C.LLVMCreateOProfileJITEventListener
func CreateOProfileJITEventListener() JITEventListenerRef

//go:linkname CreatePerfJITEventListener C.LLVMCreatePerfJITEventListener
func CreatePerfJITEventListener() JITEventListenerRef
