// Code generated by llcppg; DO NOT EDIT.

package llvm

import "github.com/goplus/lib/c"

// Read LLVM IR from a memory buffer and convert it into an in-memory Module
// object. Returns 0 on success.
// Optionally returns a human-readable description of any errors that
// occurred during parsing IR. OutMessage must be disposed with
// LLVMDisposeMessage.
// The memory buffer is consumed by this function.
// This is deprecated. Use LLVMParseIRInContext2 instead.
//
// @see llvm::ParseIR()
//
// llgo:link ContextRef.ParseIR C.LLVMParseIRInContext
func (self ContextRef) ParseIR(MemBuf MemoryBufferRef, OutM *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}

// Read LLVM IR from a memory buffer and convert it into an in-memory Module
// object. Returns 0 on success.
// Optionally returns a human-readable description of any errors that
// occurred during parsing IR. OutMessage must be disposed with
// LLVMDisposeMessage.
// The memory buffer is not consumed by this function. It is the responsibility
// of the caller to free it with \c LLVMDisposeMemoryBuffer.
//
// @see llvm::ParseIR()
//
// llgo:link ContextRef.ParseIR2 C.LLVMParseIRInContext2
func (self ContextRef) ParseIR2(MemBuf MemoryBufferRef, OutM *ModuleRef, OutMessage **c.Char) Bool {
	return 0
}
