// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// @defgroup LLVMCCoreLinker Linker
// @ingroup LLVMCCore
//
// @{
type LinkerMode c.Uint

const (
	LinkerDestroySource          LinkerMode = 0
	LinkerPreserveSource_Removed LinkerMode = 1
)

//go:linkname LinkModules2 C.LLVMLinkModules2
func LinkModules2(Dest ModuleRef, Src ModuleRef) Bool
