// Code generated by llcppg; DO NOT EDIT.

package llvm

// Install the plugin that submits debug objects to the executor. Executors must
// expose the llvm_orc_registerJITLoaderGDBAllocAction symbol.
//
// llgo:link OrcLLJITRef.EnableDebugSupport C.LLVMOrcLLJITEnableDebugSupport
func (self OrcLLJITRef) EnableDebugSupport() ErrorRef {
	return nil
}
