// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// A function for constructing an ObjectLinkingLayer instance to be used
// by an LLJIT instance.
//
// Clients can call LLVMOrcLLJITBuilderSetObjectLinkingLayerCreator to
// set the creator function to use when constructing an LLJIT instance.
// This can be used to override the default linking layer implementation
// that would otherwise be chosen by LLJITBuilder.
//
// Object linking layers returned by this function will become owned by the
// LLJIT instance. The client is not responsible for managing their lifetimes
// after the function returns.
//
// llgo:type C
type OrcLLJITBuilderObjectLinkingLayerCreatorFunction = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 OrcExecutionSessionRef, _llcppg_param3 *c.Char) OrcObjectLayerRef
type OrcOpaqueLLJITBuilder struct {
}

// A reference to an orc::LLJITBuilder instance.
type OrcLLJITBuilderRef = *OrcOpaqueLLJITBuilder
type OrcOpaqueLLJIT struct {
}

// A reference to an orc::LLJIT instance.
type OrcLLJITRef = *OrcOpaqueLLJIT

// Create an LLVMOrcLLJITBuilder.
//
// The client owns the resulting LLJITBuilder and should dispose of it using
// LLVMOrcDisposeLLJITBuilder once they are done with it.
//
//go:linkname OrcCreateLLJITBuilder C.LLVMOrcCreateLLJITBuilder
func OrcCreateLLJITBuilder() OrcLLJITBuilderRef

// Dispose of an LLVMOrcLLJITBuilderRef. This should only be called if ownership
// has not been passed to LLVMOrcCreateLLJIT (e.g. because some error prevented
// that function from being called).
//
// llgo:link OrcLLJITBuilderRef.OrcDisposeLLJITBuilder C.LLVMOrcDisposeLLJITBuilder
func (self OrcLLJITBuilderRef) OrcDisposeLLJITBuilder() {
}

// Set the JITTargetMachineBuilder to be used when constructing the LLJIT
// instance. Calling this function is optional: if it is not called then the
// LLJITBuilder will use JITTargeTMachineBuilder::detectHost to construct a
// JITTargetMachineBuilder.
//
// This function takes ownership of the JTMB argument: clients should not
// dispose of the JITTargetMachineBuilder after calling this function.
//
// llgo:link OrcLLJITBuilderRef.OrcLLJITBuilderSetJITTargetMachineBuilder C.LLVMOrcLLJITBuilderSetJITTargetMachineBuilder
func (self OrcLLJITBuilderRef) OrcLLJITBuilderSetJITTargetMachineBuilder(JTMB OrcJITTargetMachineBuilderRef) {
}

// Set an ObjectLinkingLayer creator function for this LLJIT instance.
//
// llgo:link OrcLLJITBuilderRef.OrcLLJITBuilderSetObjectLinkingLayerCreator C.LLVMOrcLLJITBuilderSetObjectLinkingLayerCreator
func (self OrcLLJITBuilderRef) OrcLLJITBuilderSetObjectLinkingLayerCreator(F OrcLLJITBuilderObjectLinkingLayerCreatorFunction, Ctx unsafe.Pointer) {
}

// Create an LLJIT instance from an LLJITBuilder.
//
// This operation takes ownership of the Builder argument: clients should not
// dispose of the builder after calling this function (even if the function
// returns an error). If a null Builder argument is provided then a
// default-constructed LLJITBuilder will be used.
//
// On success the resulting LLJIT instance is uniquely owned by the client and
// automatically manages the memory of all JIT'd code and all modules that are
// transferred to it (e.g. via LLVMOrcLLJITAddLLVMIRModule). Disposing of the
// LLJIT instance will free all memory managed by the JIT, including JIT'd code
// and not-yet compiled modules.
//
//go:linkname OrcCreateLLJIT C.LLVMOrcCreateLLJIT
func OrcCreateLLJIT(Result *OrcLLJITRef, Builder OrcLLJITBuilderRef) ErrorRef

// Dispose of an LLJIT instance.
//
// llgo:link OrcLLJITRef.OrcDisposeLLJIT C.LLVMOrcDisposeLLJIT
func (self OrcLLJITRef) OrcDisposeLLJIT() ErrorRef {
	return nil
}

// Get a reference to the ExecutionSession for this LLJIT instance.
//
// The ExecutionSession is owned by the LLJIT instance. The client is not
// responsible for managing its memory.
//
// llgo:link OrcLLJITRef.OrcLLJITGetExecutionSession C.LLVMOrcLLJITGetExecutionSession
func (self OrcLLJITRef) OrcLLJITGetExecutionSession() OrcExecutionSessionRef {
	return nil
}

// Return a reference to the Main JITDylib.
//
// The JITDylib is owned by the LLJIT instance. The client is not responsible
// for managing its memory.
//
// llgo:link OrcLLJITRef.OrcLLJITGetMainJITDylib C.LLVMOrcLLJITGetMainJITDylib
func (self OrcLLJITRef) OrcLLJITGetMainJITDylib() OrcJITDylibRef {
	return nil
}

// Return the target triple for this LLJIT instance. This string is owned by
// the LLJIT instance and should not be freed by the client.
//
// llgo:link OrcLLJITRef.OrcLLJITGetTripleString C.LLVMOrcLLJITGetTripleString
func (self OrcLLJITRef) OrcLLJITGetTripleString() *c.Char {
	return nil
}

// Returns the global prefix character according to the LLJIT's DataLayout.
//
// llgo:link OrcLLJITRef.OrcLLJITGetGlobalPrefix C.LLVMOrcLLJITGetGlobalPrefix
func (self OrcLLJITRef) OrcLLJITGetGlobalPrefix() c.Char {
	return 0
}

// Mangles the given string according to the LLJIT instance's DataLayout, then
// interns the result in the SymbolStringPool and returns a reference to the
// pool entry. Clients should call LLVMOrcReleaseSymbolStringPoolEntry to
// decrement the ref-count on the pool entry once they are finished with this
// value.
//
// llgo:link OrcLLJITRef.OrcLLJITMangleAndIntern C.LLVMOrcLLJITMangleAndIntern
func (self OrcLLJITRef) OrcLLJITMangleAndIntern(UnmangledName *c.Char) OrcSymbolStringPoolEntryRef {
	return nil
}

// Add a buffer representing an object file to the given JITDylib in the given
// LLJIT instance. This operation transfers ownership of the buffer to the
// LLJIT instance. The buffer should not be disposed of or referenced once this
// function returns.
//
// Resources associated with the given object will be tracked by the given
// JITDylib's default resource tracker.
//
// llgo:link OrcLLJITRef.OrcLLJITAddObjectFile C.LLVMOrcLLJITAddObjectFile
func (self OrcLLJITRef) OrcLLJITAddObjectFile(JD OrcJITDylibRef, ObjBuffer MemoryBufferRef) ErrorRef {
	return nil
}

// Add a buffer representing an object file to the given ResourceTracker's
// JITDylib in the given LLJIT instance. This operation transfers ownership of
// the buffer to the LLJIT instance. The buffer should not be disposed of or
// referenced once this function returns.
//
// Resources associated with the given object will be tracked by ResourceTracker
// RT.
//
// llgo:link OrcLLJITRef.OrcLLJITAddObjectFileWithRT C.LLVMOrcLLJITAddObjectFileWithRT
func (self OrcLLJITRef) OrcLLJITAddObjectFileWithRT(RT OrcResourceTrackerRef, ObjBuffer MemoryBufferRef) ErrorRef {
	return nil
}

// Add an IR module to the given JITDylib in the given LLJIT instance. This
// operation transfers ownership of the TSM argument to the LLJIT instance.
// The TSM argument should not be disposed of or referenced once this
// function returns.
//
// Resources associated with the given Module will be tracked by the given
// JITDylib's default resource tracker.
//
// llgo:link OrcLLJITRef.OrcLLJITAddLLVMIRModule C.LLVMOrcLLJITAddLLVMIRModule
func (self OrcLLJITRef) OrcLLJITAddLLVMIRModule(JD OrcJITDylibRef, TSM OrcThreadSafeModuleRef) ErrorRef {
	return nil
}

// Add an IR module to the given ResourceTracker's JITDylib in the given LLJIT
// instance. This operation transfers ownership of the TSM argument to the LLJIT
// instance. The TSM argument should not be disposed of or referenced once this
// function returns.
//
// Resources associated with the given Module will be tracked by ResourceTracker
// RT.
//
// llgo:link OrcLLJITRef.OrcLLJITAddLLVMIRModuleWithRT C.LLVMOrcLLJITAddLLVMIRModuleWithRT
func (self OrcLLJITRef) OrcLLJITAddLLVMIRModuleWithRT(JD OrcResourceTrackerRef, TSM OrcThreadSafeModuleRef) ErrorRef {
	return nil
}

// Look up the given symbol in the main JITDylib of the given LLJIT instance.
//
// This operation does not take ownership of the Name argument.
//
// llgo:link OrcLLJITRef.OrcLLJITLookup C.LLVMOrcLLJITLookup
func (self OrcLLJITRef) OrcLLJITLookup(Result *OrcExecutorAddress, Name *c.Char) ErrorRef {
	return nil
}

// Returns a non-owning reference to the LLJIT instance's object linking layer.
//
// llgo:link OrcLLJITRef.OrcLLJITGetObjLinkingLayer C.LLVMOrcLLJITGetObjLinkingLayer
func (self OrcLLJITRef) OrcLLJITGetObjLinkingLayer() OrcObjectLayerRef {
	return nil
}

// Returns a non-owning reference to the LLJIT instance's object linking layer.
//
// llgo:link OrcLLJITRef.OrcLLJITGetObjTransformLayer C.LLVMOrcLLJITGetObjTransformLayer
func (self OrcLLJITRef) OrcLLJITGetObjTransformLayer() OrcObjectTransformLayerRef {
	return nil
}

// Returns a non-owning reference to the LLJIT instance's IR transform layer.
//
// llgo:link OrcLLJITRef.OrcLLJITGetIRTransformLayer C.LLVMOrcLLJITGetIRTransformLayer
func (self OrcLLJITRef) OrcLLJITGetIRTransformLayer() OrcIRTransformLayerRef {
	return nil
}

// Get the LLJIT instance's default data layout string.
//
// This string is owned by the LLJIT instance and does not need to be freed
// by the caller.
//
// llgo:link OrcLLJITRef.OrcLLJITGetDataLayoutStr C.LLVMOrcLLJITGetDataLayoutStr
func (self OrcLLJITRef) OrcLLJITGetDataLayoutStr() *c.Char {
	return nil
}
