// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"github.com/goplus/lib/c/os"
	"unsafe"
)

const LTO_API_VERSION = 30

type LtoBoolT = bool

// \since prior to LTO_API_VERSION=3
type LtoSymbolAttributes c.Uint

const (
	LTO_SYMBOL_ALIGNMENT_MASK              LtoSymbolAttributes = 31
	LTO_SYMBOL_PERMISSIONS_MASK            LtoSymbolAttributes = 224
	LTO_SYMBOL_PERMISSIONS_CODE            LtoSymbolAttributes = 160
	LTO_SYMBOL_PERMISSIONS_DATA            LtoSymbolAttributes = 192
	LTO_SYMBOL_PERMISSIONS_RODATA          LtoSymbolAttributes = 128
	LTO_SYMBOL_DEFINITION_MASK             LtoSymbolAttributes = 1792
	LTO_SYMBOL_DEFINITION_REGULAR          LtoSymbolAttributes = 256
	LTO_SYMBOL_DEFINITION_TENTATIVE        LtoSymbolAttributes = 512
	LTO_SYMBOL_DEFINITION_WEAK             LtoSymbolAttributes = 768
	LTO_SYMBOL_DEFINITION_UNDEFINED        LtoSymbolAttributes = 1024
	LTO_SYMBOL_DEFINITION_WEAKUNDEF        LtoSymbolAttributes = 1280
	LTO_SYMBOL_SCOPE_MASK                  LtoSymbolAttributes = 14336
	LTO_SYMBOL_SCOPE_INTERNAL              LtoSymbolAttributes = 2048
	LTO_SYMBOL_SCOPE_HIDDEN                LtoSymbolAttributes = 4096
	LTO_SYMBOL_SCOPE_PROTECTED             LtoSymbolAttributes = 8192
	LTO_SYMBOL_SCOPE_DEFAULT               LtoSymbolAttributes = 6144
	LTO_SYMBOL_SCOPE_DEFAULT_CAN_BE_HIDDEN LtoSymbolAttributes = 10240
	LTO_SYMBOL_COMDAT                      LtoSymbolAttributes = 16384
	LTO_SYMBOL_ALIAS                       LtoSymbolAttributes = 32768
)

// \since prior to LTO_API_VERSION=3
type LtoDebugModel c.Uint

const (
	LTO_DEBUG_MODEL_NONE  LtoDebugModel = 0
	LTO_DEBUG_MODEL_DWARF LtoDebugModel = 1
)

// \since prior to LTO_API_VERSION=3
type LtoCodegenModel c.Uint

const (
	LTO_CODEGEN_PIC_MODEL_STATIC         LtoCodegenModel = 0
	LTO_CODEGEN_PIC_MODEL_DYNAMIC        LtoCodegenModel = 1
	LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC LtoCodegenModel = 2
	LTO_CODEGEN_PIC_MODEL_DEFAULT        LtoCodegenModel = 3
)

type OpaqueLTOModule struct {
}

// opaque reference to a loaded object module
type LtoModuleT = *OpaqueLTOModule
type OpaqueLTOCodeGenerator struct {
}

// opaque reference to a code generator
type LtoCodeGenT = *OpaqueLTOCodeGenerator
type OpaqueThinLTOCodeGenerator struct {
}

// opaque reference to a thin code generator
type ThinltoCodeGenT = *OpaqueThinLTOCodeGenerator

// Diagnostic severity.
//
// \since LTO_API_VERSION=7
type LtoCodegenDiagnosticSeverityT c.Uint

const (
	LTO_DS_ERROR   LtoCodegenDiagnosticSeverityT = 0
	LTO_DS_WARNING LtoCodegenDiagnosticSeverityT = 1
	LTO_DS_REMARK  LtoCodegenDiagnosticSeverityT = 3
	LTO_DS_NOTE    LtoCodegenDiagnosticSeverityT = 2
)

// Diagnostic handler type.
// \p severity defines the severity.
// \p diag is the actual diagnostic.
// The diagnostic is not prefixed by any of severity keyword, e.g., 'error: '.
// \p ctxt is used to pass the context set with the diagnostic handler.
//
// \since LTO_API_VERSION=7
//
// llgo:type C
type LtoDiagnosticHandlerT = func(_llcppg_param1 LtoCodegenDiagnosticSeverityT, _llcppg_param2 *c.Char, _llcppg_param3 unsafe.Pointer)
type OpaqueLTOInput struct {
}

// Opaque reference to an LTO input file
type LtoInputT = *OpaqueLTOInput

// Type to wrap a single object returned by ThinLTO.
//
// \since LTO_API_VERSION=18
type LTOObjectBuffer struct {
	Buffer *c.Char
	Size   c.SizeT
}

// Returns a printable string.
//
// \since prior to LTO_API_VERSION=3
//
//go:linkname LtoGetVersion C.lto_get_version
func LtoGetVersion() *c.Char

// Returns the last error string or NULL if last operation was successful.
//
// \since prior to LTO_API_VERSION=3
//
//go:linkname LtoGetErrorMessage C.lto_get_error_message
func LtoGetErrorMessage() *c.Char

// Checks if a file is a loadable object file.
//
// \since prior to LTO_API_VERSION=3
//
//go:linkname LtoModuleIsObjectFile C.lto_module_is_object_file
func LtoModuleIsObjectFile(path *c.Char) LtoBoolT

// Checks if a file is a loadable object compiled for requested target.
//
// \since prior to LTO_API_VERSION=3
//
//go:linkname LtoModuleIsObjectFileForTarget C.lto_module_is_object_file_for_target
func LtoModuleIsObjectFileForTarget(path *c.Char, target_triple_prefix *c.Char) LtoBoolT

// Return true if \p Buffer contains a bitcode file with ObjC code (category
// or class) in it.
//
// \since LTO_API_VERSION=20
//
//go:linkname LtoModuleHasObjcCategory C.lto_module_has_objc_category
func LtoModuleHasObjcCategory(mem unsafe.Pointer, length c.SizeT) LtoBoolT

// Checks if a buffer is a loadable object file.
//
// \since prior to LTO_API_VERSION=3
//
//go:linkname LtoModuleIsObjectFileInMemory C.lto_module_is_object_file_in_memory
func LtoModuleIsObjectFileInMemory(mem unsafe.Pointer, length c.SizeT) LtoBoolT

// Checks if a buffer is a loadable object compiled for requested target.
//
// \since prior to LTO_API_VERSION=3
//
//go:linkname LtoModuleIsObjectFileInMemoryForTarget C.lto_module_is_object_file_in_memory_for_target
func LtoModuleIsObjectFileInMemoryForTarget(mem unsafe.Pointer, length c.SizeT, target_triple_prefix *c.Char) LtoBoolT

// Loads an object file from disk.
// Returns NULL on error (check lto_get_error_message() for details).
//
// \since prior to LTO_API_VERSION=3
//
//go:linkname LtoModuleCreate C.lto_module_create
func LtoModuleCreate(path *c.Char) LtoModuleT

// Loads an object file from memory.
// Returns NULL on error (check lto_get_error_message() for details).
//
// \since prior to LTO_API_VERSION=3
//
//go:linkname LtoModuleCreateFromMemory C.lto_module_create_from_memory
func LtoModuleCreateFromMemory(mem unsafe.Pointer, length c.SizeT) LtoModuleT

// Loads an object file from memory with an extra path argument.
// Returns NULL on error (check lto_get_error_message() for details).
//
// \since LTO_API_VERSION=9
//
//go:linkname LtoModuleCreateFromMemoryWithPath C.lto_module_create_from_memory_with_path
func LtoModuleCreateFromMemoryWithPath(mem unsafe.Pointer, length c.SizeT, path *c.Char) LtoModuleT

// Loads an object file in its own context.
//
// Loads an object file in its own LLVMContext.  This function call is
// thread-safe.  However, modules created this way should not be merged into an
// lto_code_gen_t using \a lto_codegen_add_module().
//
// Returns NULL on error (check lto_get_error_message() for details).
//
// \since LTO_API_VERSION=11
//
//go:linkname LtoModuleCreateInLocalContext C.lto_module_create_in_local_context
func LtoModuleCreateInLocalContext(mem unsafe.Pointer, length c.SizeT, path *c.Char) LtoModuleT

// Loads an object file in the codegen context.
//
// Loads an object file into the same context as \c cg.  The module is safe to
// add using \a lto_codegen_add_module().
//
// Returns NULL on error (check lto_get_error_message() for details).
//
// \since LTO_API_VERSION=11
//
//go:linkname LtoModuleCreateInCodegenContext C.lto_module_create_in_codegen_context
func LtoModuleCreateInCodegenContext(mem unsafe.Pointer, length c.SizeT, path *c.Char, cg LtoCodeGenT) LtoModuleT

// Loads an object file from disk. The seek point of fd is not preserved.
// Returns NULL on error (check lto_get_error_message() for details).
//
// \since LTO_API_VERSION=5
//
//go:linkname LtoModuleCreateFromFd C.lto_module_create_from_fd
func LtoModuleCreateFromFd(fd c.Int, path *c.Char, file_size c.SizeT) LtoModuleT

// Loads an object file from disk. The seek point of fd is not preserved.
// Returns NULL on error (check lto_get_error_message() for details).
//
// \since LTO_API_VERSION=5
//
//go:linkname LtoModuleCreateFromFdAtOffset C.lto_module_create_from_fd_at_offset
func LtoModuleCreateFromFdAtOffset(fd c.Int, path *c.Char, file_size c.SizeT, map_size c.SizeT, offset os.OffT) LtoModuleT

// Frees all memory internally allocated by the module.
// Upon return the lto_module_t is no longer valid.
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoModuleT.LtoModuleDispose C.lto_module_dispose
func (self LtoModuleT) LtoModuleDispose() {
}

// Returns triple string which the object module was compiled under.
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoModuleT.LtoModuleGetTargetTriple C.lto_module_get_target_triple
func (self LtoModuleT) LtoModuleGetTargetTriple() *c.Char {
	return nil
}

// Sets triple string with which the object will be codegened.
//
// \since LTO_API_VERSION=4
//
// llgo:link LtoModuleT.LtoModuleSetTargetTriple C.lto_module_set_target_triple
func (self LtoModuleT) LtoModuleSetTargetTriple(triple *c.Char) {
}

// Returns the number of symbols in the object module.
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoModuleT.LtoModuleGetNumSymbols C.lto_module_get_num_symbols
func (self LtoModuleT) LtoModuleGetNumSymbols() c.Uint {
	return 0
}

// Returns the name of the ith symbol in the object module.
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoModuleT.LtoModuleGetSymbolName C.lto_module_get_symbol_name
func (self LtoModuleT) LtoModuleGetSymbolName(index c.Uint) *c.Char {
	return nil
}

// Returns the attributes of the ith symbol in the object module.
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoModuleT.LtoModuleGetSymbolAttribute C.lto_module_get_symbol_attribute
func (self LtoModuleT) LtoModuleGetSymbolAttribute(index c.Uint) LtoSymbolAttributes {
	return 0
}

// Returns the number of asm undefined symbols in the object module.
//
// \since prior to LTO_API_VERSION=30
//
// llgo:link LtoModuleT.LtoModuleGetNumAsmUndefSymbols C.lto_module_get_num_asm_undef_symbols
func (self LtoModuleT) LtoModuleGetNumAsmUndefSymbols() c.Uint {
	return 0
}

// Returns the name of the ith asm undefined symbol in the object module.
//
// \since prior to LTO_API_VERSION=30
//
// llgo:link LtoModuleT.LtoModuleGetAsmUndefSymbolName C.lto_module_get_asm_undef_symbol_name
func (self LtoModuleT) LtoModuleGetAsmUndefSymbolName(index c.Uint) *c.Char {
	return nil
}

// Returns the module's linker options.
//
// The linker options may consist of multiple flags. It is the linker's
// responsibility to split the flags using a platform-specific mechanism.
//
// \since LTO_API_VERSION=16
//
// llgo:link LtoModuleT.LtoModuleGetLinkeropts C.lto_module_get_linkeropts
func (self LtoModuleT) LtoModuleGetLinkeropts() *c.Char {
	return nil
}

// If targeting mach-o on darwin, this function gets the CPU type and subtype
// that will end up being encoded in the mach-o header. These are the values
// that can be found in mach/machine.h.
//
// \p out_cputype and \p out_cpusubtype must be non-NULL.
//
// Returns true on error (check lto_get_error_message() for details).
//
// \since LTO_API_VERSION=27
//
// llgo:link LtoModuleT.LtoModuleGetMachoCputype C.lto_module_get_macho_cputype
func (self LtoModuleT) LtoModuleGetMachoCputype(out_cputype *c.Uint, out_cpusubtype *c.Uint) LtoBoolT {
	return false
}

// This function can be used by the linker to check if a given module has
// any constructor or destructor functions.
//
// Returns true if the module has either the @llvm.global_ctors or the
// @llvm.global_dtors symbol. Otherwise returns false.
//
// \since LTO_API_VERSION=29
//
// llgo:link LtoModuleT.LtoModuleHasCtorDtor C.lto_module_has_ctor_dtor
func (self LtoModuleT) LtoModuleHasCtorDtor() LtoBoolT {
	return false
}

// Set a diagnostic handler and the related context (void *).
// This is more general than lto_get_error_message, as the diagnostic handler
// can be called at anytime within lto.
//
// \since LTO_API_VERSION=7
//
// llgo:link LtoCodeGenT.LtoCodegenSetDiagnosticHandler C.lto_codegen_set_diagnostic_handler
func (self LtoCodeGenT) LtoCodegenSetDiagnosticHandler(_llcppg_param2 LtoDiagnosticHandlerT, _llcppg_param3 unsafe.Pointer) {
}

// Instantiates a code generator.
// Returns NULL on error (check lto_get_error_message() for details).
//
// All modules added using \a lto_codegen_add_module() must have been created
// in the same context as the codegen.
//
// \since prior to LTO_API_VERSION=3
//
//go:linkname LtoCodegenCreate C.lto_codegen_create
func LtoCodegenCreate() LtoCodeGenT

// Instantiate a code generator in its own context.
//
// Instantiates a code generator in its own context.  Modules added via \a
// lto_codegen_add_module() must have all been created in the same context,
// using \a lto_module_create_in_codegen_context().
//
// \since LTO_API_VERSION=11
//
//go:linkname LtoCodegenCreateInLocalContext C.lto_codegen_create_in_local_context
func LtoCodegenCreateInLocalContext() LtoCodeGenT

// Frees all code generator and all memory it internally allocated.
// Upon return the lto_code_gen_t is no longer valid.
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoCodeGenT.LtoCodegenDispose C.lto_codegen_dispose
func (self LtoCodeGenT) LtoCodegenDispose() {
}

// Add an object module to the set of modules for which code will be generated.
// Returns true on error (check lto_get_error_message() for details).
//
// \c cg and \c mod must both be in the same context.  See \a
// lto_codegen_create_in_local_context() and \a
// lto_module_create_in_codegen_context().
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoCodeGenT.LtoCodegenAddModule C.lto_codegen_add_module
func (self LtoCodeGenT) LtoCodegenAddModule(mod LtoModuleT) LtoBoolT {
	return false
}

// Sets the object module for code generation. This will transfer the ownership
// of the module to the code generator.
//
// \c cg and \c mod must both be in the same context.
//
// \since LTO_API_VERSION=13
//
// llgo:link LtoCodeGenT.LtoCodegenSetModule C.lto_codegen_set_module
func (self LtoCodeGenT) LtoCodegenSetModule(mod LtoModuleT) {
}

// Sets if debug info should be generated.
// Returns true on error (check lto_get_error_message() for details).
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoCodeGenT.LtoCodegenSetDebugModel C.lto_codegen_set_debug_model
func (self LtoCodeGenT) LtoCodegenSetDebugModel(_llcppg_param2 LtoDebugModel) LtoBoolT {
	return false
}

// Sets which PIC code model to generated.
// Returns true on error (check lto_get_error_message() for details).
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoCodeGenT.LtoCodegenSetPicModel C.lto_codegen_set_pic_model
func (self LtoCodeGenT) LtoCodegenSetPicModel(_llcppg_param2 LtoCodegenModel) LtoBoolT {
	return false
}

// Sets the cpu to generate code for.
//
// \since LTO_API_VERSION=4
//
// llgo:link LtoCodeGenT.LtoCodegenSetCpu C.lto_codegen_set_cpu
func (self LtoCodeGenT) LtoCodegenSetCpu(cpu *c.Char) {
}

// Sets the location of the assembler tool to run. If not set, libLTO
// will use gcc to invoke the assembler.
//
// \since LTO_API_VERSION=3
//
// llgo:link LtoCodeGenT.LtoCodegenSetAssemblerPath C.lto_codegen_set_assembler_path
func (self LtoCodeGenT) LtoCodegenSetAssemblerPath(path *c.Char) {
}

// Sets extra arguments that libLTO should pass to the assembler.
//
// \since LTO_API_VERSION=4
//
// llgo:link LtoCodeGenT.LtoCodegenSetAssemblerArgs C.lto_codegen_set_assembler_args
func (self LtoCodeGenT) LtoCodegenSetAssemblerArgs(args **c.Char, nargs c.Int) {
}

// Adds to a list of all global symbols that must exist in the final generated
// code. If a function is not listed there, it might be inlined into every usage
// and optimized away.
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoCodeGenT.LtoCodegenAddMustPreserveSymbol C.lto_codegen_add_must_preserve_symbol
func (self LtoCodeGenT) LtoCodegenAddMustPreserveSymbol(symbol *c.Char) {
}

// Writes a new object file at the specified path that contains the
// merged contents of all modules added so far.
// Returns true on error (check lto_get_error_message() for details).
//
// \since LTO_API_VERSION=5
//
// llgo:link LtoCodeGenT.LtoCodegenWriteMergedModules C.lto_codegen_write_merged_modules
func (self LtoCodeGenT) LtoCodegenWriteMergedModules(path *c.Char) LtoBoolT {
	return false
}

// Generates code for all added modules into one native object file.
// This calls lto_codegen_optimize then lto_codegen_compile_optimized.
//
// On success returns a pointer to a generated mach-o/ELF buffer and
// length set to the buffer size.  The buffer is owned by the
// lto_code_gen_t and will be freed when lto_codegen_dispose()
// is called, or lto_codegen_compile() is called again.
// On failure, returns NULL (check lto_get_error_message() for details).
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoCodeGenT.LtoCodegenCompile C.lto_codegen_compile
func (self LtoCodeGenT) LtoCodegenCompile(length *c.SizeT) unsafe.Pointer {
	return nil
}

// Generates code for all added modules into one native object file.
// This calls lto_codegen_optimize then lto_codegen_compile_optimized (instead
// of returning a generated mach-o/ELF buffer, it writes to a file).
//
// The name of the file is written to name. Returns true on error.
//
// \since LTO_API_VERSION=5
//
// llgo:link LtoCodeGenT.LtoCodegenCompileToFile C.lto_codegen_compile_to_file
func (self LtoCodeGenT) LtoCodegenCompileToFile(name **c.Char) LtoBoolT {
	return false
}

// Runs optimization for the merged module. Returns true on error.
//
// \since LTO_API_VERSION=12
//
// llgo:link LtoCodeGenT.LtoCodegenOptimize C.lto_codegen_optimize
func (self LtoCodeGenT) LtoCodegenOptimize() LtoBoolT {
	return false
}

// Generates code for the optimized merged module into one native object file.
// It will not run any IR optimizations on the merged module.
//
// On success returns a pointer to a generated mach-o/ELF buffer and length set
// to the buffer size.  The buffer is owned by the lto_code_gen_t and will be
// freed when lto_codegen_dispose() is called, or
// lto_codegen_compile_optimized() is called again. On failure, returns NULL
// (check lto_get_error_message() for details).
//
// \since LTO_API_VERSION=12
//
// llgo:link LtoCodeGenT.LtoCodegenCompileOptimized C.lto_codegen_compile_optimized
func (self LtoCodeGenT) LtoCodegenCompileOptimized(length *c.SizeT) unsafe.Pointer {
	return nil
}

// Returns the runtime API version.
//
// \since LTO_API_VERSION=12
//
//go:linkname LtoApiVersion C.lto_api_version
func LtoApiVersion() c.Uint

// Parses options immediately, making them available as early as possible. For
// example during executing codegen::InitTargetOptionsFromCodeGenFlags. Since
// parsing shud only happen once, only one of lto_codegen_debug_options or
// lto_set_debug_options should be called.
//
// This function takes one or more options separated by spaces.
// Warning: passing file paths through this function may confuse the argument
// parser if the paths contain spaces.
//
// \since LTO_API_VERSION=28
//
//go:linkname LtoSetDebugOptions C.lto_set_debug_options
func LtoSetDebugOptions(options **c.Char, number c.Int)

// Sets options to help debug codegen bugs. Since parsing shud only happen once,
// only one of lto_codegen_debug_options or lto_set_debug_options
// should be called.
//
// This function takes one or more options separated by spaces.
// Warning: passing file paths through this function may confuse the argument
// parser if the paths contain spaces.
//
// \since prior to LTO_API_VERSION=3
//
// llgo:link LtoCodeGenT.LtoCodegenDebugOptions C.lto_codegen_debug_options
func (self LtoCodeGenT) LtoCodegenDebugOptions(_llcppg_param2 *c.Char) {
}

// Same as the previous function, but takes every option separately through an
// array.
//
// \since prior to LTO_API_VERSION=26
//
// llgo:link LtoCodeGenT.LtoCodegenDebugOptionsArray C.lto_codegen_debug_options_array
func (self LtoCodeGenT) LtoCodegenDebugOptionsArray(_llcppg_param2 **c.Char, number c.Int) {
}

// Initializes LLVM disassemblers.
// FIXME: This doesn't really belong here.
//
// \since LTO_API_VERSION=5
//
//go:linkname LtoInitializeDisassembler C.lto_initialize_disassembler
func LtoInitializeDisassembler()

// Sets if we should run internalize pass during optimization and code
// generation.
//
// \since LTO_API_VERSION=14
//
// llgo:link LtoCodeGenT.LtoCodegenSetShouldInternalize C.lto_codegen_set_should_internalize
func (self LtoCodeGenT) LtoCodegenSetShouldInternalize(ShouldInternalize LtoBoolT) {
}

// Set whether to embed uselists in bitcode.
//
// Sets whether \a lto_codegen_write_merged_modules() should embed uselists in
// output bitcode.  This should be turned on for all -save-temps output.
//
// \since LTO_API_VERSION=15
//
// llgo:link LtoCodeGenT.LtoCodegenSetShouldEmbedUselists C.lto_codegen_set_should_embed_uselists
func (self LtoCodeGenT) LtoCodegenSetShouldEmbedUselists(ShouldEmbedUselists LtoBoolT) {
}

// Creates an LTO input file from a buffer. The path
// argument is used for diagnotics as this function
// otherwise does not know which file the given buffer
// is associated with.
//
// \since LTO_API_VERSION=24
//
//go:linkname LtoInputCreate C.lto_input_create
func LtoInputCreate(buffer unsafe.Pointer, buffer_size c.SizeT, path *c.Char) LtoInputT

// Frees all memory internally allocated by the LTO input file.
// Upon return the lto_module_t is no longer valid.
//
// \since LTO_API_VERSION=24
//
// llgo:link LtoInputT.LtoInputDispose C.lto_input_dispose
func (self LtoInputT) LtoInputDispose() {
}

// Returns the number of dependent library specifiers
// for the given LTO input file.
//
// \since LTO_API_VERSION=24
//
// llgo:link LtoInputT.LtoInputGetNumDependentLibraries C.lto_input_get_num_dependent_libraries
func (self LtoInputT) LtoInputGetNumDependentLibraries() c.Uint {
	return 0
}

// Returns the ith dependent library specifier
// for the given LTO input file. The returned
// string is not null-terminated.
//
// \since LTO_API_VERSION=24
//
// llgo:link LtoInputT.LtoInputGetDependentLibrary C.lto_input_get_dependent_library
func (self LtoInputT) LtoInputGetDependentLibrary(index c.SizeT, size *c.SizeT) *c.Char {
	return nil
}

// Returns the list of libcall symbols that can be generated by LTO
// that might not be visible from the symbol table of bitcode files.
//
// \since prior to LTO_API_VERSION=25
//
//go:linkname LtoRuntimeLibSymbolsList C.lto_runtime_lib_symbols_list
func LtoRuntimeLibSymbolsList(size *c.SizeT) **c.Char

// Instantiates a ThinLTO code generator.
// Returns NULL on error (check lto_get_error_message() for details).
//
//
// The ThinLTOCodeGenerator is not intended to be reuse for multiple
// compilation: the model is that the client adds modules to the generator and
// ask to perform the ThinLTO optimizations / codegen, and finally destroys the
// codegenerator.
//
// \since LTO_API_VERSION=18
//
//go:linkname ThinltoCreateCodegen C.thinlto_create_codegen
func ThinltoCreateCodegen() ThinltoCodeGenT

// Frees the generator and all memory it internally allocated.
// Upon return the thinlto_code_gen_t is no longer valid.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenDispose C.thinlto_codegen_dispose
func (self ThinltoCodeGenT) ThinltoCodegenDispose() {
}

// Add a module to a ThinLTO code generator. Identifier has to be unique among
// all the modules in a code generator. The data buffer stays owned by the
// client, and is expected to be available for the entire lifetime of the
// thinlto_code_gen_t it is added to.
//
// On failure, returns NULL (check lto_get_error_message() for details).
//
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenAddModule C.thinlto_codegen_add_module
func (self ThinltoCodeGenT) ThinltoCodegenAddModule(identifier *c.Char, data *c.Char, length c.Int) {
}

// Optimize and codegen all the modules added to the codegenerator using
// ThinLTO. Resulting objects are accessible using thinlto_module_get_object().
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenProcess C.thinlto_codegen_process
func (self ThinltoCodeGenT) ThinltoCodegenProcess() {
}

// Returns the number of object files produced by the ThinLTO CodeGenerator.
//
// It usually matches the number of input files, but this is not a guarantee of
// the API and may change in future implementation, so the client should not
// assume it.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoModuleGetNumObjects C.thinlto_module_get_num_objects
func (self ThinltoCodeGenT) ThinltoModuleGetNumObjects() c.Uint {
	return 0
}

// Returns a reference to the ith object file produced by the ThinLTO
// CodeGenerator.
//
// Client should use \p thinlto_module_get_num_objects() to get the number of
// available objects.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoModuleGetObject C.thinlto_module_get_object
func (self ThinltoCodeGenT) ThinltoModuleGetObject(index c.Uint) LTOObjectBuffer {
	return LTOObjectBuffer{}
}

// Returns the number of object files produced by the ThinLTO CodeGenerator.
//
// It usually matches the number of input files, but this is not a guarantee of
// the API and may change in future implementation, so the client should not
// assume it.
//
// \since LTO_API_VERSION=21
//
// llgo:link ThinltoCodeGenT.ThinltoModuleGetNumObjectFiles C.thinlto_module_get_num_object_files
func (self ThinltoCodeGenT) ThinltoModuleGetNumObjectFiles() c.Uint {
	return 0
}

// Returns the path to the ith object file produced by the ThinLTO
// CodeGenerator.
//
// Client should use \p thinlto_module_get_num_object_files() to get the number
// of available objects.
//
// \since LTO_API_VERSION=21
//
// llgo:link ThinltoCodeGenT.ThinltoModuleGetObjectFile C.thinlto_module_get_object_file
func (self ThinltoCodeGenT) ThinltoModuleGetObjectFile(index c.Uint) *c.Char {
	return nil
}

// Sets which PIC code model to generate.
// Returns true on error (check lto_get_error_message() for details).
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetPicModel C.thinlto_codegen_set_pic_model
func (self ThinltoCodeGenT) ThinltoCodegenSetPicModel(_llcppg_param2 LtoCodegenModel) LtoBoolT {
	return false
}

// Sets the path to a directory to use as a storage for temporary bitcode files.
// The intention is to make the bitcode files available for debugging at various
// stage of the pipeline.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetSavetempsDir C.thinlto_codegen_set_savetemps_dir
func (self ThinltoCodeGenT) ThinltoCodegenSetSavetempsDir(save_temps_dir *c.Char) {
}

// Set the path to a directory where to save generated object files. This
// path can be used by a linker to request on-disk files instead of in-memory
// buffers. When set, results are available through
// thinlto_module_get_object_file() instead of thinlto_module_get_object().
//
// \since LTO_API_VERSION=21
//
// llgo:link ThinltoCodeGenT.ThinltoSetGeneratedObjectsDir C.thinlto_set_generated_objects_dir
func (self ThinltoCodeGenT) ThinltoSetGeneratedObjectsDir(save_temps_dir *c.Char) {
}

// Sets the cpu to generate code for.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetCpu C.thinlto_codegen_set_cpu
func (self ThinltoCodeGenT) ThinltoCodegenSetCpu(cpu *c.Char) {
}

// Disable CodeGen, only run the stages till codegen and stop. The output will
// be bitcode.
//
// \since LTO_API_VERSION=19
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenDisableCodegen C.thinlto_codegen_disable_codegen
func (self ThinltoCodeGenT) ThinltoCodegenDisableCodegen(disable LtoBoolT) {
}

// Perform CodeGen only: disable all other stages.
//
// \since LTO_API_VERSION=19
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetCodegenOnly C.thinlto_codegen_set_codegen_only
func (self ThinltoCodeGenT) ThinltoCodegenSetCodegenOnly(codegen_only LtoBoolT) {
}

// Parse -mllvm style debug options.
//
// \since LTO_API_VERSION=18
//
//go:linkname ThinltoDebugOptions C.thinlto_debug_options
func ThinltoDebugOptions(options **c.Char, number c.Int)

// Test if a module has support for ThinLTO linking.
//
// \since LTO_API_VERSION=18
//
// llgo:link LtoModuleT.LtoModuleIsThinlto C.lto_module_is_thinlto
func (self LtoModuleT) LtoModuleIsThinlto() LtoBoolT {
	return false
}

// Adds a symbol to the list of global symbols that must exist in the final
// generated code. If a function is not listed there, it might be inlined into
// every usage and optimized away. For every single module, the functions
// referenced from code outside of the ThinLTO modules need to be added here.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenAddMustPreserveSymbol C.thinlto_codegen_add_must_preserve_symbol
func (self ThinltoCodeGenT) ThinltoCodegenAddMustPreserveSymbol(name *c.Char, length c.Int) {
}

// Adds a symbol to the list of global symbols that are cross-referenced between
// ThinLTO files. If the ThinLTO CodeGenerator can ensure that every
// references from a ThinLTO module to this symbol is optimized away, then
// the symbol can be discarded.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenAddCrossReferencedSymbol C.thinlto_codegen_add_cross_referenced_symbol
func (self ThinltoCodeGenT) ThinltoCodegenAddCrossReferencedSymbol(name *c.Char, length c.Int) {
}

// Sets the path to a directory to use as a cache storage for incremental build.
// Setting this activates caching.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetCacheDir C.thinlto_codegen_set_cache_dir
func (self ThinltoCodeGenT) ThinltoCodegenSetCacheDir(cache_dir *c.Char) {
}

// Sets the cache pruning interval (in seconds). A negative value disables the
// pruning. An unspecified default value will be applied, and a value of 0 will
// force prunning to occur.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetCachePruningInterval C.thinlto_codegen_set_cache_pruning_interval
func (self ThinltoCodeGenT) ThinltoCodegenSetCachePruningInterval(interval c.Int) {
}

// Sets the maximum cache size that can be persistent across build, in terms of
// percentage of the available space on the disk. Set to 100 to indicate
// no limit, 50 to indicate that the cache size will not be left over half the
// available space. A value over 100 will be reduced to 100, a value of 0 will
// be ignored. An unspecified default value will be applied.
//
// The formula looks like:
//  AvailableSpace = FreeSpace + ExistingCacheSize
//  NewCacheSize = AvailableSpace * P/100
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetFinalCacheSizeRelativeToAvailableSpace C.thinlto_codegen_set_final_cache_size_relative_to_available_space
func (self ThinltoCodeGenT) ThinltoCodegenSetFinalCacheSizeRelativeToAvailableSpace(percentage c.Uint) {
}

// Sets the expiration (in seconds) for an entry in the cache. An unspecified
// default value will be applied. A value of 0 will be ignored.
//
// \since LTO_API_VERSION=18
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetCacheEntryExpiration C.thinlto_codegen_set_cache_entry_expiration
func (self ThinltoCodeGenT) ThinltoCodegenSetCacheEntryExpiration(expiration c.Uint) {
}

// Sets the maximum size of the cache directory (in bytes). A value over the
// amount of available space on the disk will be reduced to the amount of
// available space. An unspecified default value will be applied. A value of 0
// will be ignored.
//
// \since LTO_API_VERSION=22
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetCacheSizeBytes C.thinlto_codegen_set_cache_size_bytes
func (self ThinltoCodeGenT) ThinltoCodegenSetCacheSizeBytes(max_size_bytes c.Uint) {
}

// Same as thinlto_codegen_set_cache_size_bytes, except the maximum size is in
// megabytes (2^20 bytes).
//
// \since LTO_API_VERSION=23
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetCacheSizeMegabytes C.thinlto_codegen_set_cache_size_megabytes
func (self ThinltoCodeGenT) ThinltoCodegenSetCacheSizeMegabytes(max_size_megabytes c.Uint) {
}

// Sets the maximum number of files in the cache directory. An unspecified
// default value will be applied. A value of 0 will be ignored.
//
// \since LTO_API_VERSION=22
//
// llgo:link ThinltoCodeGenT.ThinltoCodegenSetCacheSizeFiles C.thinlto_codegen_set_cache_size_files
func (self ThinltoCodeGenT) ThinltoCodegenSetCacheSizeFiles(max_size_files c.Uint) {
}
