// Code generated by llcppg; DO NOT EDIT.

package llvm

import "github.com/goplus/lib/c"

type OpaqueSectionIterator struct {
}

// @defgroup LLVMCObject Object file reading and writing
// @ingroup LLVMC
//
// @{
type SectionIteratorRef = *OpaqueSectionIterator
type OpaqueSymbolIterator struct {
}
type SymbolIteratorRef = *OpaqueSymbolIterator
type OpaqueRelocationIterator struct {
}
type RelocationIteratorRef = *OpaqueRelocationIterator
type BinaryType c.Uint

const (
	// < Archive file.
	BinaryTypeArchive BinaryType = 0
	// < Mach-O Universal Binary file.
	BinaryTypeMachOUniversalBinary BinaryType = 1
	// < COFF Import file.
	BinaryTypeCOFFImportFile BinaryType = 2
	// < LLVM IR.
	BinaryTypeIR BinaryType = 3
	// < Windows resource (.res) file.
	BinaryTypeWinRes BinaryType = 4
	// < COFF Object file.
	BinaryTypeCOFF BinaryType = 5
	// < ELF 32-bit, little endian.
	BinaryTypeELF32L BinaryType = 6
	// < ELF 32-bit, big endian.
	BinaryTypeELF32B BinaryType = 7
	// < ELF 64-bit, little endian.
	BinaryTypeELF64L BinaryType = 8
	// < ELF 64-bit, big endian.
	BinaryTypeELF64B BinaryType = 9
	// < MachO 32-bit, little endian.
	BinaryTypeMachO32L BinaryType = 10
	// < MachO 32-bit, big endian.
	BinaryTypeMachO32B BinaryType = 11
	// < MachO 64-bit, little endian.
	BinaryTypeMachO64L BinaryType = 12
	// < MachO 64-bit, big endian.
	BinaryTypeMachO64B BinaryType = 13
	// < Web Assembly.
	BinaryTypeWasm BinaryType = 14
	// < Offloading fatbinary.
	BinaryTypeOffload BinaryType = 15
	// < DirectX Binary Container.
	BinaryTypeDXcontainer BinaryType = 16
)

type OpaqueObjectFile struct {
}

// Deprecated: Use LLVMBinaryRef instead.
type ObjectFileRef = *OpaqueObjectFile

// Create a binary file from the given memory buffer.
//
// The exact type of the binary file will be inferred automatically, and the
// appropriate implementation selected.  The context may be NULL except if
// the resulting file is an LLVM IR file.
//
// The memory buffer is not consumed by this function. It is the responsibility
// of the caller to free it with \c LLVMDisposeMemoryBuffer.
//
// If NULL is returned, the \p ErrorMessage parameter is populated with the
// error's description.  It is then the caller's responsibility to free this
// message by calling \c LLVMDisposeMessage.
//
// @see llvm::object::createBinary
//
// llgo:link MemoryBufferRef.CreateBinary C.LLVMCreateBinary
func (self MemoryBufferRef) CreateBinary(Context ContextRef, ErrorMessage **c.Char) BinaryRef {
	return nil
}

// Dispose of a binary file.
//
// The binary file does not own its backing buffer. It is the responsibility
// of the caller to free it with \c LLVMDisposeMemoryBuffer.
//
// llgo:link BinaryRef.Dispose C.LLVMDisposeBinary
func (self BinaryRef) Dispose() {
}

// Retrieves a copy of the memory buffer associated with this object file.
//
// The returned buffer is merely a shallow copy and does not own the actual
// backing buffer of the binary. Nevertheless, it is the responsibility of the
// caller to free it with \c LLVMDisposeMemoryBuffer.
//
// @see llvm::object::getMemoryBufferRef
//
// llgo:link BinaryRef.CopyMemoryBuffer C.LLVMBinaryCopyMemoryBuffer
func (self BinaryRef) CopyMemoryBuffer() MemoryBufferRef {
	return nil
}

// Retrieve the specific type of a binary.
//
// @see llvm::object::Binary::getType
//
// llgo:link BinaryRef.Type C.LLVMBinaryGetType
func (self BinaryRef) Type() BinaryType {
	return 0
}

// llgo:link BinaryRef.MachOUniversalBinaryCopyObjectForArch C.LLVMMachOUniversalBinaryCopyObjectForArch
func (self BinaryRef) MachOUniversalBinaryCopyObjectForArch(Arch *c.Char, ArchLen c.SizeT, ErrorMessage **c.Char) BinaryRef {
	return self
}

// Retrieve a copy of the section iterator for this object file.
//
// If there are no sections, the result is NULL.
//
// The returned iterator is merely a shallow copy. Nevertheless, it is
// the responsibility of the caller to free it with
// \c LLVMDisposeSectionIterator.
//
// @see llvm::object::sections()
//
// llgo:link BinaryRef.ObjectFileCopySectionIterator C.LLVMObjectFileCopySectionIterator
func (self BinaryRef) ObjectFileCopySectionIterator() SectionIteratorRef {
	return nil
}

// Returns whether the given section iterator is at the end.
//
// @see llvm::object::section_end
//
// llgo:link BinaryRef.ObjectFileIsSectionIteratorAtEnd C.LLVMObjectFileIsSectionIteratorAtEnd
func (self BinaryRef) ObjectFileIsSectionIteratorAtEnd(SI SectionIteratorRef) Bool {
	return 0
}

// Retrieve a copy of the symbol iterator for this object file.
//
// If there are no symbols, the result is NULL.
//
// The returned iterator is merely a shallow copy. Nevertheless, it is
// the responsibility of the caller to free it with
// \c LLVMDisposeSymbolIterator.
//
// @see llvm::object::symbols()
//
// llgo:link BinaryRef.ObjectFileCopySymbolIterator C.LLVMObjectFileCopySymbolIterator
func (self BinaryRef) ObjectFileCopySymbolIterator() SymbolIteratorRef {
	return nil
}

// Returns whether the given symbol iterator is at the end.
//
// @see llvm::object::symbol_end
//
// llgo:link BinaryRef.ObjectFileIsSymbolIteratorAtEnd C.LLVMObjectFileIsSymbolIteratorAtEnd
func (self BinaryRef) ObjectFileIsSymbolIteratorAtEnd(SI SymbolIteratorRef) Bool {
	return 0
}

// llgo:link SectionIteratorRef.Dispose C.LLVMDisposeSectionIterator
func (self SectionIteratorRef) Dispose() {
}

// llgo:link SectionIteratorRef.MoveToNextSection C.LLVMMoveToNextSection
func (self SectionIteratorRef) MoveToNextSection() {
}

// llgo:link SectionIteratorRef.MoveToContainingSection C.LLVMMoveToContainingSection
func (self SectionIteratorRef) MoveToContainingSection(Sym SymbolIteratorRef) {
}

// llgo:link SymbolIteratorRef.Dispose C.LLVMDisposeSymbolIterator
func (self SymbolIteratorRef) Dispose() {
}

// llgo:link SymbolIteratorRef.MoveToNextSymbol C.LLVMMoveToNextSymbol
func (self SymbolIteratorRef) MoveToNextSymbol() {
}

// llgo:link SectionIteratorRef.SectionName C.LLVMGetSectionName
func (self SectionIteratorRef) SectionName() *c.Char {
	return nil
}

// llgo:link SectionIteratorRef.SectionSize C.LLVMGetSectionSize
func (self SectionIteratorRef) SectionSize() c.Uint64T {
	return 0
}

// llgo:link SectionIteratorRef.SectionContents C.LLVMGetSectionContents
func (self SectionIteratorRef) SectionContents() *c.Char {
	return nil
}

// llgo:link SectionIteratorRef.SectionAddress C.LLVMGetSectionAddress
func (self SectionIteratorRef) SectionAddress() c.Uint64T {
	return 0
}

// llgo:link SectionIteratorRef.SectionContainsSymbol C.LLVMGetSectionContainsSymbol
func (self SectionIteratorRef) SectionContainsSymbol(Sym SymbolIteratorRef) Bool {
	return 0
}

// llgo:link SectionIteratorRef.Relocations C.LLVMGetRelocations
func (self SectionIteratorRef) Relocations() RelocationIteratorRef {
	return nil
}

// llgo:link RelocationIteratorRef.Dispose C.LLVMDisposeRelocationIterator
func (self RelocationIteratorRef) Dispose() {
}

// llgo:link SectionIteratorRef.IsRelocationIteratorAtEnd C.LLVMIsRelocationIteratorAtEnd
func (self SectionIteratorRef) IsRelocationIteratorAtEnd(RI RelocationIteratorRef) Bool {
	return 0
}

// llgo:link RelocationIteratorRef.MoveToNextRelocation C.LLVMMoveToNextRelocation
func (self RelocationIteratorRef) MoveToNextRelocation() {
}

// llgo:link SymbolIteratorRef.SymbolName C.LLVMGetSymbolName
func (self SymbolIteratorRef) SymbolName() *c.Char {
	return nil
}

// llgo:link SymbolIteratorRef.SymbolAddress C.LLVMGetSymbolAddress
func (self SymbolIteratorRef) SymbolAddress() c.Uint64T {
	return 0
}

// llgo:link SymbolIteratorRef.SymbolSize C.LLVMGetSymbolSize
func (self SymbolIteratorRef) SymbolSize() c.Uint64T {
	return 0
}

// llgo:link RelocationIteratorRef.RelocationOffset C.LLVMGetRelocationOffset
func (self RelocationIteratorRef) RelocationOffset() c.Uint64T {
	return 0
}

// llgo:link RelocationIteratorRef.RelocationSymbol C.LLVMGetRelocationSymbol
func (self RelocationIteratorRef) RelocationSymbol() SymbolIteratorRef {
	return nil
}

// llgo:link RelocationIteratorRef.RelocationType C.LLVMGetRelocationType
func (self RelocationIteratorRef) RelocationType() c.Uint64T {
	return 0
}

// llgo:link RelocationIteratorRef.RelocationTypeName C.LLVMGetRelocationTypeName
func (self RelocationIteratorRef) RelocationTypeName() *c.Char {
	return nil
}

// llgo:link RelocationIteratorRef.RelocationValueString C.LLVMGetRelocationValueString
func (self RelocationIteratorRef) RelocationValueString() *c.Char {
	return nil
}

// Deprecated: Use LLVMCreateBinary instead.
//
// llgo:link MemoryBufferRef.CreateObjectFile C.LLVMCreateObjectFile
func (self MemoryBufferRef) CreateObjectFile() ObjectFileRef {
	return nil
}

// Deprecated: Use LLVMDisposeBinary instead.
//
// llgo:link ObjectFileRef.Dispose C.LLVMDisposeObjectFile
func (self ObjectFileRef) Dispose() {
}

// Deprecated: Use LLVMObjectFileCopySectionIterator instead.
//
// llgo:link ObjectFileRef.Sections C.LLVMGetSections
func (self ObjectFileRef) Sections() SectionIteratorRef {
	return nil
}

// Deprecated: Use LLVMObjectFileIsSectionIteratorAtEnd instead.
//
// llgo:link ObjectFileRef.IsSectionIteratorAtEnd C.LLVMIsSectionIteratorAtEnd
func (self ObjectFileRef) IsSectionIteratorAtEnd(SI SectionIteratorRef) Bool {
	return 0
}

// Deprecated: Use LLVMObjectFileCopySymbolIterator instead.
//
// llgo:link ObjectFileRef.Symbols C.LLVMGetSymbols
func (self ObjectFileRef) Symbols() SymbolIteratorRef {
	return nil
}

// Deprecated: Use LLVMObjectFileIsSymbolIteratorAtEnd instead.
//
// llgo:link ObjectFileRef.IsSymbolIteratorAtEnd C.LLVMIsSymbolIteratorAtEnd
func (self ObjectFileRef) IsSymbolIteratorAtEnd(SI SymbolIteratorRef) Bool {
	return 0
}
