// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// Represents an address in the executor process.
type OrcJITTargetAddress = c.Uint64T

// Represents an address in the executor process.
type OrcExecutorAddress = c.Uint64T

// Represents generic linkage flags for a symbol definition.
type JITSymbolGenericFlags c.Uint

const (
	JITSymbolGenericFlagsNone                           JITSymbolGenericFlags = 0
	JITSymbolGenericFlagsExported                       JITSymbolGenericFlags = 1
	JITSymbolGenericFlagsWeak                           JITSymbolGenericFlags = 2
	JITSymbolGenericFlagsCallable                       JITSymbolGenericFlags = 4
	JITSymbolGenericFlagsMaterializationSideEffectsOnly JITSymbolGenericFlags = 8
)

// Represents target specific flags for a symbol definition.
type JITSymbolTargetFlags = c.Uint8T

// Represents the linkage flags for a symbol definition.
type JITSymbolFlags struct {
	GenericFlags c.Uint8T
	TargetFlags  c.Uint8T
}

// Represents an evaluated symbol address and flags.
type JITEvaluatedSymbol struct {
	Address OrcExecutorAddress
	Flags   JITSymbolFlags
}
type OrcOpaqueExecutionSession struct {
}

// A reference to an orc::ExecutionSession instance.
type OrcExecutionSessionRef = *OrcOpaqueExecutionSession

// Error reporter function.
//
// llgo:type C
type OrcErrorReporterFunction = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 ErrorRef)
type OrcOpaqueSymbolStringPool struct {
}

// A reference to an orc::SymbolStringPool.
type OrcSymbolStringPoolRef = *OrcOpaqueSymbolStringPool
type OrcOpaqueSymbolStringPoolEntry struct {
}

// A reference to an orc::SymbolStringPool table entry.
type OrcSymbolStringPoolEntryRef = *OrcOpaqueSymbolStringPoolEntry

// Represents a pair of a symbol name and LLVMJITSymbolFlags.
type OrcCSymbolFlagsMapPair struct {
	Name  OrcSymbolStringPoolEntryRef
	Flags JITSymbolFlags
}

// Represents a list of (SymbolStringPtr, JITSymbolFlags) pairs that can be used
// to construct a SymbolFlagsMap.
type OrcCSymbolFlagsMapPairs = *OrcCSymbolFlagsMapPair

// Represents a pair of a symbol name and an evaluated symbol.
type OrcCSymbolMapPair struct {
	Name OrcSymbolStringPoolEntryRef
	Sym  JITEvaluatedSymbol
}

// Represents a list of (SymbolStringPtr, JITEvaluatedSymbol) pairs that can be
// used to construct a SymbolMap.
type OrcCSymbolMapPairs = *OrcCSymbolMapPair

// Represents a SymbolAliasMapEntry
type OrcCSymbolAliasMapEntry struct {
	Name  OrcSymbolStringPoolEntryRef
	Flags JITSymbolFlags
}

// Represents a pair of a symbol name and SymbolAliasMapEntry.
type OrcCSymbolAliasMapPair struct {
	Name  OrcSymbolStringPoolEntryRef
	Entry OrcCSymbolAliasMapEntry
}

// Represents a list of (SymbolStringPtr, (SymbolStringPtr, JITSymbolFlags))
// pairs that can be used to construct a SymbolFlagsMap.
type OrcCSymbolAliasMapPairs = *OrcCSymbolAliasMapPair
type OrcOpaqueJITDylib struct {
}

// A reference to an orc::JITDylib instance.
type OrcJITDylibRef = *OrcOpaqueJITDylib

// Represents a list of LLVMOrcSymbolStringPoolEntryRef and the associated
// length.
type OrcCSymbolsList struct {
	Symbols *OrcSymbolStringPoolEntryRef
	Length  c.SizeT
}

// Represents a pair of a JITDylib and LLVMOrcCSymbolsList.
type OrcCDependenceMapPair struct {
	JD    OrcJITDylibRef
	Names OrcCSymbolsList
}

// Represents a list of (JITDylibRef, (LLVMOrcSymbolStringPoolEntryRef*,
// size_t)) pairs that can be used to construct a SymbolDependenceMap.
type OrcCDependenceMapPairs = *OrcCDependenceMapPair

// A set of symbols that share dependencies.
type OrcCSymbolDependenceGroup struct {
	Symbols         OrcCSymbolsList
	Dependencies    OrcCDependenceMapPairs
	NumDependencies c.SizeT
}

// Lookup kind. This can be used by definition generators when deciding whether
// to produce a definition for a requested symbol.
//
// This enum should be kept in sync with llvm::orc::LookupKind.
type OrcLookupKind c.Uint

const (
	OrcLookupKindStatic OrcLookupKind = 0
	OrcLookupKindDLSym  OrcLookupKind = 1
)

// JITDylib lookup flags. This can be used by definition generators when
// deciding whether to produce a definition for a requested symbol.
//
// This enum should be kept in sync with llvm::orc::JITDylibLookupFlags.
type OrcJITDylibLookupFlags c.Uint

const (
	OrcJITDylibLookupFlagsMatchExportedSymbolsOnly OrcJITDylibLookupFlags = 0
	OrcJITDylibLookupFlagsMatchAllSymbols          OrcJITDylibLookupFlags = 1
)

// An element type for a JITDylib search order.
type OrcCJITDylibSearchOrderElement struct {
	JD            OrcJITDylibRef
	JDLookupFlags OrcJITDylibLookupFlags
}

// A JITDylib search order.
//
// The list is terminated with an element containing a null pointer for the JD
// field.
type OrcCJITDylibSearchOrder = *OrcCJITDylibSearchOrderElement

// Symbol lookup flags for lookup sets. This should be kept in sync with
// llvm::orc::SymbolLookupFlags.
type OrcSymbolLookupFlags c.Uint

const (
	OrcSymbolLookupFlagsRequiredSymbol         OrcSymbolLookupFlags = 0
	OrcSymbolLookupFlagsWeaklyReferencedSymbol OrcSymbolLookupFlags = 1
)

// An element type for a symbol lookup set.
type OrcCLookupSetElement struct {
	Name        OrcSymbolStringPoolEntryRef
	LookupFlags OrcSymbolLookupFlags
}

// A set of symbols to look up / generate.
//
// The list is terminated with an element containing a null pointer for the
// Name field.
//
// If a client creates an instance of this type then they are responsible for
// freeing it, and for ensuring that all strings have been retained over the
// course of its life. Clients receiving a copy from a callback are not
// responsible for managing lifetime or retain counts.
type OrcCLookupSet = *OrcCLookupSetElement
type OrcOpaqueMaterializationUnit struct {
}

// A reference to a uniquely owned orc::MaterializationUnit instance.
type OrcMaterializationUnitRef = *OrcOpaqueMaterializationUnit
type OrcOpaqueMaterializationResponsibility struct {
}

// A reference to a uniquely owned orc::MaterializationResponsibility instance.
//
// Ownership must be passed to a lower-level layer in a JIT stack.
type OrcMaterializationResponsibilityRef = *OrcOpaqueMaterializationResponsibility

// A MaterializationUnit materialize callback.
//
// Ownership of the Ctx and MR arguments passes to the callback which must
// adhere to the LLVMOrcMaterializationResponsibilityRef contract (see comment
// for that type).
//
// If this callback is called then the LLVMOrcMaterializationUnitDestroy
// callback will NOT be called.
//
// llgo:type C
type OrcMaterializationUnitMaterializeFunction = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 OrcMaterializationResponsibilityRef)

// A MaterializationUnit discard callback.
//
// Ownership of JD and Symbol remain with the caller: These arguments should
// not be disposed of or released.
//
// llgo:type C
type OrcMaterializationUnitDiscardFunction = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 OrcJITDylibRef, _llcppg_param3 OrcSymbolStringPoolEntryRef)

// A MaterializationUnit destruction callback.
//
// If a custom MaterializationUnit is destroyed before its Materialize
// function is called then this function will be called to provide an
// opportunity for the underlying program representation to be destroyed.
//
// llgo:type C
type OrcMaterializationUnitDestroyFunction = func(_llcppg_param1 unsafe.Pointer)
type OrcOpaqueResourceTracker struct {
}

// A reference to an orc::ResourceTracker instance.
type OrcResourceTrackerRef = *OrcOpaqueResourceTracker
type OrcOpaqueDefinitionGenerator struct {
}

// A reference to an orc::DefinitionGenerator.
type OrcDefinitionGeneratorRef = *OrcOpaqueDefinitionGenerator
type OrcOpaqueLookupState struct {
}

// An opaque lookup state object. Instances of this type can be captured to
// suspend a lookup while a custom generator function attempts to produce a
// definition.
//
// If a client captures a lookup state object then they must eventually call
// LLVMOrcLookupStateContinueLookup to restart the lookup. This is required
// in order to release memory allocated for the lookup state, even if errors
// have occurred while the lookup was suspended (if these errors have made the
// lookup impossible to complete then it will issue its own error before
// destruction).
type OrcLookupStateRef = *OrcOpaqueLookupState

// A custom generator function. This can be used to create a custom generator
// object using LLVMOrcCreateCustomCAPIDefinitionGenerator. The resulting
// object can be attached to a JITDylib, via LLVMOrcJITDylibAddGenerator, to
// receive callbacks when lookups fail to match existing definitions.
//
// GeneratorObj will contain the address of the custom generator object.
//
// Ctx will contain the context object passed to
// LLVMOrcCreateCustomCAPIDefinitionGenerator.
//
// LookupState will contain a pointer to an LLVMOrcLookupStateRef object. This
// can optionally be modified to make the definition generation process
// asynchronous: If the LookupStateRef value is copied, and the original
// LLVMOrcLookupStateRef set to null, the lookup will be suspended. Once the
// asynchronous definition process has been completed clients must call
// LLVMOrcLookupStateContinueLookup to continue the lookup (this should be
// done unconditionally, even if errors have occurred in the mean time, to
// free the lookup state memory and notify the query object of the failures).
// If LookupState is captured this function must return LLVMErrorSuccess.
//
// The Kind argument can be inspected to determine the lookup kind (e.g.
// as-if-during-static-link, or as-if-during-dlsym).
//
// The JD argument specifies which JITDylib the definitions should be generated
// into.
//
// The JDLookupFlags argument can be inspected to determine whether the original
// lookup included non-exported symbols.
//
// Finally, the LookupSet argument contains the set of symbols that could not
// be found in JD already (the set of generation candidates).
//
// llgo:type C
type OrcCAPIDefinitionGeneratorTryToGenerateFunction = func(_llcppg_param1 OrcDefinitionGeneratorRef, _llcppg_param2 unsafe.Pointer, _llcppg_param3 *OrcLookupStateRef, _llcppg_param4 OrcLookupKind, _llcppg_param5 OrcJITDylibRef, _llcppg_param6 OrcJITDylibLookupFlags, _llcppg_param7 OrcCLookupSet, _llcppg_param8 c.SizeT) ErrorRef

// Disposer for a custom generator.
//
// Will be called by ORC when the JITDylib that the generator is attached to
// is destroyed.
//
// llgo:type C
type OrcDisposeCAPIDefinitionGeneratorFunction = func(_llcppg_param1 unsafe.Pointer)

// Predicate function for SymbolStringPoolEntries.
//
// llgo:type C
type OrcSymbolPredicate = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 OrcSymbolStringPoolEntryRef) c.Int
type OrcOpaqueThreadSafeContext struct {
}

// A reference to an orc::ThreadSafeContext instance.
type OrcThreadSafeContextRef = *OrcOpaqueThreadSafeContext
type OrcOpaqueThreadSafeModule struct {
}

// A reference to an orc::ThreadSafeModule instance.
type OrcThreadSafeModuleRef = *OrcOpaqueThreadSafeModule

// A function for inspecting/mutating IR modules, suitable for use with
// LLVMOrcThreadSafeModuleWithModuleDo.
//
// llgo:type C
type OrcGenericIRModuleOperationFunction = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 ModuleRef) ErrorRef
type OrcOpaqueJITTargetMachineBuilder struct {
}

// A reference to an orc::JITTargetMachineBuilder instance.
type OrcJITTargetMachineBuilderRef = *OrcOpaqueJITTargetMachineBuilder
type OrcOpaqueObjectLayer struct {
}

// A reference to an orc::ObjectLayer instance.
type OrcObjectLayerRef = *OrcOpaqueObjectLayer
type OrcOpaqueObjectLinkingLayer struct {
}

// A reference to an orc::ObjectLinkingLayer instance.
type OrcObjectLinkingLayerRef = *OrcOpaqueObjectLinkingLayer
type OrcOpaqueIRTransformLayer struct {
}

// A reference to an orc::IRTransformLayer instance.
type OrcIRTransformLayerRef = *OrcOpaqueIRTransformLayer

// A function for applying transformations as part of an transform layer.
//
// Implementations of this type are responsible for managing the lifetime
// of the Module pointed to by ModInOut: If the LLVMModuleRef value is
// overwritten then the function is responsible for disposing of the incoming
// module. If the module is simply accessed/mutated in-place then ownership
// returns to the caller and the function does not need to do any lifetime
// management.
//
// Clients can call LLVMOrcLLJITGetIRTransformLayer to obtain the transform
// layer of a LLJIT instance, and use LLVMOrcIRTransformLayerSetTransform
// to set the function. This can be used to override the default transform
// layer.
//
// llgo:type C
type OrcIRTransformLayerTransformFunction = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 *OrcThreadSafeModuleRef, _llcppg_param3 OrcMaterializationResponsibilityRef) ErrorRef
type OrcOpaqueObjectTransformLayer struct {
}

// A reference to an orc::ObjectTransformLayer instance.
type OrcObjectTransformLayerRef = *OrcOpaqueObjectTransformLayer

// A function for applying transformations to an object file buffer.
//
// Implementations of this type are responsible for managing the lifetime
// of the memory buffer pointed to by ObjInOut: If the LLVMMemoryBufferRef
// value is overwritten then the function is responsible for disposing of the
// incoming buffer. If the buffer is simply accessed/mutated in-place then
// ownership returns to the caller and the function does not need to do any
// lifetime management.
//
// The transform is allowed to return an error, in which case the ObjInOut
// buffer should be disposed of and set to null.
//
// llgo:type C
type OrcObjectTransformLayerTransformFunction = func(_llcppg_param1 unsafe.Pointer, _llcppg_param2 *MemoryBufferRef) ErrorRef
type OrcOpaqueIndirectStubsManager struct {
}

// A reference to an orc::IndirectStubsManager instance.
type OrcIndirectStubsManagerRef = *OrcOpaqueIndirectStubsManager
type OrcOpaqueLazyCallThroughManager struct {
}

// A reference to an orc::LazyCallThroughManager instance.
type OrcLazyCallThroughManagerRef = *OrcOpaqueLazyCallThroughManager
type OrcOpaqueDumpObjects struct {
}

// A reference to an orc::DumpObjects object.
//
// Can be used to dump object files to disk with unique names. Useful as an
// ObjectTransformLayer transform.
type OrcDumpObjectsRef = *OrcOpaqueDumpObjects

// Callback type for ExecutionSession lookups.
//
// If Err is LLVMErrorSuccess then Result will contain a pointer to a
// list of ( SymbolStringPtr, JITEvaluatedSymbol ) pairs of length NumPairs.
//
// If Err is a failure value then Result and Ctx are undefined and should
// not be accessed. The Callback is responsible for handling the error
// value (e.g. by calling LLVMGetErrorMessage + LLVMDisposeErrorMessage).
//
// The caller retains ownership of the Result array and will release all
// contained symbol names. Clients are responsible for retaining any symbol
// names that they wish to hold after the function returns.
//
// llgo:type C
type OrcExecutionSessionLookupHandleResultFunction = func(_llcppg_param1 ErrorRef, _llcppg_param2 OrcCSymbolMapPairs, _llcppg_param3 c.SizeT, _llcppg_param4 unsafe.Pointer)

// Attach a custom error reporter function to the ExecutionSession.
//
// The error reporter will be called to deliver failure notices that can not be
// directly reported to a caller. For example, failure to resolve symbols in
// the JIT linker is typically reported via the error reporter (callers
// requesting definitions from the JIT will typically be delivered a
// FailureToMaterialize error instead).
//
// llgo:link OrcExecutionSessionRef.SetErrorReporter C.LLVMOrcExecutionSessionSetErrorReporter
func (self OrcExecutionSessionRef) SetErrorReporter(ReportError OrcErrorReporterFunction, Ctx unsafe.Pointer) {
}

// Return a reference to the SymbolStringPool for an ExecutionSession.
//
// Ownership of the pool remains with the ExecutionSession: The caller is
// not required to free the pool.
//
// llgo:link OrcExecutionSessionRef.SymbolStringPool C.LLVMOrcExecutionSessionGetSymbolStringPool
func (self OrcExecutionSessionRef) SymbolStringPool() OrcSymbolStringPoolRef {
	return nil
}

// Clear all unreferenced symbol string pool entries.
//
// This can be called at any time to release unused entries in the
// ExecutionSession's string pool. Since it locks the pool (preventing
// interning of any new strings) it is recommended that it only be called
// infrequently, ideally when the caller has reason to believe that some
// entries will have become unreferenced, e.g. after removing a module or
// closing a JITDylib.
//
// llgo:link OrcSymbolStringPoolRef.ClearDeadEntries C.LLVMOrcSymbolStringPoolClearDeadEntries
func (self OrcSymbolStringPoolRef) ClearDeadEntries() {
}

// Intern a string in the ExecutionSession's SymbolStringPool and return a
// reference to it. This increments the ref-count of the pool entry, and the
// returned value should be released once the client is done with it by
// calling LLVMOrcReleaseSymbolStringPoolEntry.
//
// Since strings are uniqued within the SymbolStringPool
// LLVMOrcSymbolStringPoolEntryRefs can be compared by value to test string
// equality.
//
// Note that this function does not perform linker-mangling on the string.
//
// llgo:link OrcExecutionSessionRef.Intern C.LLVMOrcExecutionSessionIntern
func (self OrcExecutionSessionRef) Intern(Name *c.Char) OrcSymbolStringPoolEntryRef {
	return nil
}

// Look up symbols in an execution session.
//
// This is a wrapper around the general ExecutionSession::lookup function.
//
// The SearchOrder argument contains a list of (JITDylibs, JITDylibSearchFlags)
// pairs that describe the search order. The JITDylibs will be searched in the
// given order to try to find the symbols in the Symbols argument.
//
// The Symbols argument should contain a null-terminated array of
// (SymbolStringPtr, SymbolLookupFlags) pairs describing the symbols to be
// searched for. This function takes ownership of the elements of the Symbols
// array. The Name fields of the Symbols elements are taken to have been
// retained by the client for this function. The client should *not* release the
// Name fields, but are still responsible for destroying the array itself.
//
// The HandleResult function will be called once all searched for symbols have
// been found, or an error occurs. The HandleResult function will be passed an
// LLVMErrorRef indicating success or failure, and (on success) a
// null-terminated LLVMOrcCSymbolMapPairs array containing the function result,
// and the Ctx value passed to the lookup function.
//
// The client is fully responsible for managing the lifetime of the Ctx object.
// A common idiom is to allocate the context prior to the lookup and deallocate
// it in the handler.
//
// THIS API IS EXPERIMENTAL AND LIKELY TO CHANGE IN THE NEAR FUTURE!
//
// llgo:link OrcExecutionSessionRef.Lookup C.LLVMOrcExecutionSessionLookup
func (self OrcExecutionSessionRef) Lookup(K OrcLookupKind, SearchOrder OrcCJITDylibSearchOrder, SearchOrderSize c.SizeT, Symbols OrcCLookupSet, SymbolsSize c.SizeT, HandleResult OrcExecutionSessionLookupHandleResultFunction, Ctx unsafe.Pointer) {
}

// Increments the ref-count for a SymbolStringPool entry.
//
// llgo:link OrcSymbolStringPoolEntryRef.Retain C.LLVMOrcRetainSymbolStringPoolEntry
func (self OrcSymbolStringPoolEntryRef) Retain() {
}

// Reduces the ref-count for of a SymbolStringPool entry.
//
// llgo:link OrcSymbolStringPoolEntryRef.Release C.LLVMOrcReleaseSymbolStringPoolEntry
func (self OrcSymbolStringPoolEntryRef) Release() {
}

// Return the c-string for the given symbol. This string will remain valid until
// the entry is freed (once all LLVMOrcSymbolStringPoolEntryRefs have been
// released).
//
// llgo:link OrcSymbolStringPoolEntryRef.Str C.LLVMOrcSymbolStringPoolEntryStr
func (self OrcSymbolStringPoolEntryRef) Str() *c.Char {
	return nil
}

// Reduces the ref-count of a ResourceTracker.
//
// llgo:link OrcResourceTrackerRef.Release C.LLVMOrcReleaseResourceTracker
func (self OrcResourceTrackerRef) Release() {
}

// Transfers tracking of all resources associated with resource tracker SrcRT
// to resource tracker DstRT.
//
//go:linkname OrcResourceTrackerTransferTo C.LLVMOrcResourceTrackerTransferTo
func OrcResourceTrackerTransferTo(SrcRT OrcResourceTrackerRef, DstRT OrcResourceTrackerRef)

// Remove all resources associated with the given tracker. See
// ResourceTracker::remove().
//
// llgo:link OrcResourceTrackerRef.Remove C.LLVMOrcResourceTrackerRemove
func (self OrcResourceTrackerRef) Remove() ErrorRef {
	return nil
}

// Dispose of a JITDylib::DefinitionGenerator. This should only be called if
// ownership has not been passed to a JITDylib (e.g. because some error
// prevented the client from calling LLVMOrcJITDylibAddGenerator).
//
// llgo:link OrcDefinitionGeneratorRef.Dispose C.LLVMOrcDisposeDefinitionGenerator
func (self OrcDefinitionGeneratorRef) Dispose() {
}

// Dispose of a MaterializationUnit.
//
// llgo:link OrcMaterializationUnitRef.Dispose C.LLVMOrcDisposeMaterializationUnit
func (self OrcMaterializationUnitRef) Dispose() {
}

// Create a custom MaterializationUnit.
//
// Name is a name for this MaterializationUnit to be used for identification
// and logging purposes (e.g. if this MaterializationUnit produces an
// object buffer then the name of that buffer will be derived from this name).
//
// The Syms list contains the names and linkages of the symbols provided by this
// unit. This function takes ownership of the elements of the Syms array. The
// Name fields of the array elements are taken to have been retained for this
// function. The client should *not* release the elements of the array, but is
// still responsible for destroying the array itself.
//
// The InitSym argument indicates whether or not this MaterializationUnit
// contains static initializers. If three are no static initializers (the common
// case) then this argument should be null. If there are static initializers
// then InitSym should be set to a unique name that also appears in the Syms
// list with the LLVMJITSymbolGenericFlagsMaterializationSideEffectsOnly flag
// set. This function takes ownership of the InitSym, which should have been
// retained twice on behalf of this function: once for the Syms entry and once
// for InitSym. If clients wish to use the InitSym value after this function
// returns they must retain it once more for themselves.
//
// If any of the symbols in the Syms list is looked up then the Materialize
// function will be called.
//
// If any of the symbols in the Syms list is overridden then the Discard
// function will be called.
//
// The caller owns the underling MaterializationUnit and is responsible for
// either passing it to a JITDylib (via LLVMOrcJITDylibDefine) or disposing
// of it by calling LLVMOrcDisposeMaterializationUnit.
//
//go:linkname OrcCreateCustomMaterializationUnit C.LLVMOrcCreateCustomMaterializationUnit
func OrcCreateCustomMaterializationUnit(Name *c.Char, Ctx unsafe.Pointer, Syms OrcCSymbolFlagsMapPairs, NumSyms c.SizeT, InitSym OrcSymbolStringPoolEntryRef, Materialize OrcMaterializationUnitMaterializeFunction, Discard OrcMaterializationUnitDiscardFunction, Destroy OrcMaterializationUnitDestroyFunction) OrcMaterializationUnitRef

// Create a MaterializationUnit to define the given symbols as pointing to
// the corresponding raw addresses.
//
// This function takes ownership of the elements of the Syms array. The Name
// fields of the array elements are taken to have been retained for this
// function. This allows the following pattern...
//
//   size_t NumPairs;
//   LLVMOrcCSymbolMapPairs Sym;
//   -- Build Syms array --
//   LLVMOrcMaterializationUnitRef MU =
//       LLVMOrcAbsoluteSymbols(Syms, NumPairs);
//
// ... without requiring cleanup of the elements of the Sym array afterwards.
//
// The client is still responsible for deleting the Sym array itself.
//
// If a client wishes to reuse elements of the Sym array after this call they
// must explicitly retain each of the elements for themselves.
//
// llgo:link OrcCSymbolMapPairs.OrcAbsoluteSymbols C.LLVMOrcAbsoluteSymbols
func (self OrcCSymbolMapPairs) OrcAbsoluteSymbols(NumPairs c.SizeT) OrcMaterializationUnitRef {
	return nil
}

// Create a MaterializationUnit to define lazy re-expots. These are callable
// entry points that call through to the given symbols.
//
// This function takes ownership of the CallableAliases array. The Name
// fields of the array elements are taken to have been retained for this
// function. This allows the following pattern...
//
//   size_t NumPairs;
//   LLVMOrcCSymbolAliasMapPairs CallableAliases;
//   -- Build CallableAliases array --
//   LLVMOrcMaterializationUnitRef MU =
//      LLVMOrcLazyReexports(LCTM, ISM, JD, CallableAliases, NumPairs);
//
// ... without requiring cleanup of the elements of the CallableAliases array afterwards.
//
// The client is still responsible for deleting the CallableAliases array itself.
//
// If a client wishes to reuse elements of the CallableAliases array after this call they
// must explicitly retain each of the elements for themselves.
//
// llgo:link OrcLazyCallThroughManagerRef.OrcLazyReexports C.LLVMOrcLazyReexports
func (self OrcLazyCallThroughManagerRef) OrcLazyReexports(ISM OrcIndirectStubsManagerRef, SourceRef OrcJITDylibRef, CallableAliases OrcCSymbolAliasMapPairs, NumPairs c.SizeT) OrcMaterializationUnitRef {
	return nil
}

// Disposes of the passed MaterializationResponsibility object.
//
// This should only be done after the symbols covered by the object have either
// been resolved and emitted (via
// LLVMOrcMaterializationResponsibilityNotifyResolved and
// LLVMOrcMaterializationResponsibilityNotifyEmitted) or failed (via
// LLVMOrcMaterializationResponsibilityFailMaterialization).
//
// llgo:link OrcMaterializationResponsibilityRef.Dispose C.LLVMOrcDisposeMaterializationResponsibility
func (self OrcMaterializationResponsibilityRef) Dispose() {
}

// Returns the target JITDylib that these symbols are being materialized into.
//
// llgo:link OrcMaterializationResponsibilityRef.TargetDylib C.LLVMOrcMaterializationResponsibilityGetTargetDylib
func (self OrcMaterializationResponsibilityRef) TargetDylib() OrcJITDylibRef {
	return nil
}

// Returns the ExecutionSession for this MaterializationResponsibility.
//
// llgo:link OrcMaterializationResponsibilityRef.ExecutionSession C.LLVMOrcMaterializationResponsibilityGetExecutionSession
func (self OrcMaterializationResponsibilityRef) ExecutionSession() OrcExecutionSessionRef {
	return nil
}

// Returns the symbol flags map for this responsibility instance.
//
// The length of the array is returned in NumPairs and the caller is responsible
// for the returned memory and needs to call LLVMOrcDisposeCSymbolFlagsMap.
//
// To use the returned symbols beyond the livetime of the
// MaterializationResponsibility requires the caller to retain the symbols
// explicitly.
//
// llgo:link OrcMaterializationResponsibilityRef.Symbols C.LLVMOrcMaterializationResponsibilityGetSymbols
func (self OrcMaterializationResponsibilityRef) Symbols(NumPairs *c.SizeT) OrcCSymbolFlagsMapPairs {
	return nil
}

// Disposes of the passed LLVMOrcCSymbolFlagsMap.
//
// Does not release the entries themselves.
//
// llgo:link OrcCSymbolFlagsMapPairs.OrcDisposeCSymbolFlagsMap C.LLVMOrcDisposeCSymbolFlagsMap
func (self OrcCSymbolFlagsMapPairs) OrcDisposeCSymbolFlagsMap() {
}

// Returns the initialization pseudo-symbol, if any. This symbol will also
// be present in the SymbolFlagsMap for this MaterializationResponsibility
// object.
//
// The returned symbol is not retained over any mutating operation of the
// MaterializationResponsbility or beyond the lifetime thereof.
//
// llgo:link OrcMaterializationResponsibilityRef.InitializerSymbol C.LLVMOrcMaterializationResponsibilityGetInitializerSymbol
func (self OrcMaterializationResponsibilityRef) InitializerSymbol() OrcSymbolStringPoolEntryRef {
	return nil
}

// Returns the names of any symbols covered by this
// MaterializationResponsibility object that have queries pending. This
// information can be used to return responsibility for unrequested symbols
// back to the JITDylib via the delegate method.
//
// llgo:link OrcMaterializationResponsibilityRef.RequestedSymbols C.LLVMOrcMaterializationResponsibilityGetRequestedSymbols
func (self OrcMaterializationResponsibilityRef) RequestedSymbols(NumSymbols *c.SizeT) *OrcSymbolStringPoolEntryRef {
	return nil
}

// Disposes of the passed LLVMOrcSymbolStringPoolEntryRef* .
//
// Does not release the symbols themselves.
//
//go:linkname OrcDisposeSymbols C.LLVMOrcDisposeSymbols
func OrcDisposeSymbols(Symbols *OrcSymbolStringPoolEntryRef)

// Notifies the target JITDylib that the given symbols have been resolved.
// This will update the given symbols' addresses in the JITDylib, and notify
// any pending queries on the given symbols of their resolution. The given
// symbols must be ones covered by this MaterializationResponsibility
// instance. Individual calls to this method may resolve a subset of the
// symbols, but all symbols must have been resolved prior to calling emit.
//
// This method will return an error if any symbols being resolved have been
// moved to the error state due to the failure of a dependency. If this
// method returns an error then clients should log it and call
// LLVMOrcMaterializationResponsibilityFailMaterialization. If no dependencies
// have been registered for the symbols covered by this
// MaterializationResponsibility then this method is guaranteed to return
// LLVMErrorSuccess.
//
// llgo:link OrcMaterializationResponsibilityRef.NotifyResolved C.LLVMOrcMaterializationResponsibilityNotifyResolved
func (self OrcMaterializationResponsibilityRef) NotifyResolved(Symbols OrcCSymbolMapPairs, NumPairs c.SizeT) ErrorRef {
	return nil
}

// Notifies the target JITDylib (and any pending queries on that JITDylib)
// that all symbols covered by this MaterializationResponsibility instance
// have been emitted.
//
// This function takes ownership of the symbols in the Dependencies struct.
// This allows the following pattern...
//
//   LLVMOrcSymbolStringPoolEntryRef Names[] = {...};
//   LLVMOrcCDependenceMapPair Dependence = {JD, {Names, sizeof(Names)}}
//   LLVMOrcMaterializationResponsibilityAddDependencies(JD, Name, &Dependence,
// 1);
//
// ... without requiring cleanup of the elements of the Names array afterwards.
//
// The client is still responsible for deleting the Dependencies.Names arrays,
// and the Dependencies array itself.
//
// This method will return an error if any symbols being resolved have been
// moved to the error state due to the failure of a dependency. If this
// method returns an error then clients should log it and call
// LLVMOrcMaterializationResponsibilityFailMaterialization.
// If no dependencies have been registered for the symbols covered by this
// MaterializationResponsibility then this method is guaranteed to return
// LLVMErrorSuccess.
//
// llgo:link OrcMaterializationResponsibilityRef.NotifyEmitted C.LLVMOrcMaterializationResponsibilityNotifyEmitted
func (self OrcMaterializationResponsibilityRef) NotifyEmitted(SymbolDepGroups *OrcCSymbolDependenceGroup, NumSymbolDepGroups c.SizeT) ErrorRef {
	return nil
}

// Attempt to claim responsibility for new definitions. This method can be
// used to claim responsibility for symbols that are added to a
// materialization unit during the compilation process (e.g. literal pool
// symbols). Symbol linkage rules are the same as for symbols that are
// defined up front: duplicate strong definitions will result in errors.
// Duplicate weak definitions will be discarded (in which case they will
// not be added to this responsibility instance).
//
// This method can be used by materialization units that want to add
// additional symbols at materialization time (e.g. stubs, compile
// callbacks, metadata)
//
// llgo:link OrcMaterializationResponsibilityRef.DefineMaterializing C.LLVMOrcMaterializationResponsibilityDefineMaterializing
func (self OrcMaterializationResponsibilityRef) DefineMaterializing(Pairs OrcCSymbolFlagsMapPairs, NumPairs c.SizeT) ErrorRef {
	return nil
}

// Notify all not-yet-emitted covered by this MaterializationResponsibility
// instance that an error has occurred.
// This will remove all symbols covered by this MaterializationResponsibility
// from the target JITDylib, and send an error to any queries waiting on
// these symbols.
//
// llgo:link OrcMaterializationResponsibilityRef.FailMaterialization C.LLVMOrcMaterializationResponsibilityFailMaterialization
func (self OrcMaterializationResponsibilityRef) FailMaterialization() {
}

// Transfers responsibility to the given MaterializationUnit for all
// symbols defined by that MaterializationUnit. This allows
// materializers to break up work based on run-time information (e.g.
// by introspecting which symbols have actually been looked up and
// materializing only those).
//
// llgo:link OrcMaterializationResponsibilityRef.Replace C.LLVMOrcMaterializationResponsibilityReplace
func (self OrcMaterializationResponsibilityRef) Replace(MU OrcMaterializationUnitRef) ErrorRef {
	return nil
}

// Delegates responsibility for the given symbols to the returned
// materialization responsibility. Useful for breaking up work between
// threads, or different kinds of materialization processes.
//
// The caller retains responsibility of the the passed
// MaterializationResponsibility.
//
// llgo:link OrcMaterializationResponsibilityRef.Delegate C.LLVMOrcMaterializationResponsibilityDelegate
func (self OrcMaterializationResponsibilityRef) Delegate(Symbols *OrcSymbolStringPoolEntryRef, NumSymbols c.SizeT, Result *OrcMaterializationResponsibilityRef) ErrorRef {
	return nil
}

// Create a "bare" JITDylib.
//
// The client is responsible for ensuring that the JITDylib's name is unique,
// e.g. by calling LLVMOrcExecutionSessionGetJTIDylibByName first.
//
// This call does not install any library code or symbols into the newly
// created JITDylib. The client is responsible for all configuration.
//
// llgo:link OrcExecutionSessionRef.CreateBareJITDylib C.LLVMOrcExecutionSessionCreateBareJITDylib
func (self OrcExecutionSessionRef) CreateBareJITDylib(Name *c.Char) OrcJITDylibRef {
	return nil
}

// Create a JITDylib.
//
// The client is responsible for ensuring that the JITDylib's name is unique,
// e.g. by calling LLVMOrcExecutionSessionGetJTIDylibByName first.
//
// If a Platform is attached to the ExecutionSession then
// Platform::setupJITDylib will be called to install standard platform symbols
// (e.g. standard library interposes). If no Platform is installed then this
// call is equivalent to LLVMExecutionSessionRefCreateBareJITDylib and will
// always return success.
//
// llgo:link OrcExecutionSessionRef.CreateJITDylib C.LLVMOrcExecutionSessionCreateJITDylib
func (self OrcExecutionSessionRef) CreateJITDylib(Result *OrcJITDylibRef, Name *c.Char) ErrorRef {
	return nil
}

// Returns the JITDylib with the given name, or NULL if no such JITDylib
// exists.
//
// llgo:link OrcExecutionSessionRef.JITDylibByName C.LLVMOrcExecutionSessionGetJITDylibByName
func (self OrcExecutionSessionRef) JITDylibByName(Name *c.Char) OrcJITDylibRef {
	return nil
}

// Return a reference to a newly created resource tracker associated with JD.
// The tracker is returned with an initial ref-count of 1, and must be released
// with LLVMOrcReleaseResourceTracker when no longer needed.
//
// llgo:link OrcJITDylibRef.CreateResourceTracker C.LLVMOrcJITDylibCreateResourceTracker
func (self OrcJITDylibRef) CreateResourceTracker() OrcResourceTrackerRef {
	return nil
}

// Return a reference to the default resource tracker for the given JITDylib.
// This operation will increase the retain count of the tracker: Clients should
// call LLVMOrcReleaseResourceTracker when the result is no longer needed.
//
// llgo:link OrcJITDylibRef.DefaultResourceTracker C.LLVMOrcJITDylibGetDefaultResourceTracker
func (self OrcJITDylibRef) DefaultResourceTracker() OrcResourceTrackerRef {
	return nil
}

// Add the given MaterializationUnit to the given JITDylib.
//
// If this operation succeeds then JITDylib JD will take ownership of MU.
// If the operation fails then ownership remains with the caller who should
// call LLVMOrcDisposeMaterializationUnit to destroy it.
//
// llgo:link OrcJITDylibRef.Define C.LLVMOrcJITDylibDefine
func (self OrcJITDylibRef) Define(MU OrcMaterializationUnitRef) ErrorRef {
	return nil
}

// Calls remove on all trackers associated with this JITDylib, see
// JITDylib::clear().
//
// llgo:link OrcJITDylibRef.Clear C.LLVMOrcJITDylibClear
func (self OrcJITDylibRef) Clear() ErrorRef {
	return nil
}

// Add a DefinitionGenerator to the given JITDylib.
//
// The JITDylib will take ownership of the given generator: The client is no
// longer responsible for managing its memory.
//
// llgo:link OrcJITDylibRef.AddGenerator C.LLVMOrcJITDylibAddGenerator
func (self OrcJITDylibRef) AddGenerator(DG OrcDefinitionGeneratorRef) {
}

// Create a custom generator.
//
// The F argument will be used to implement the DefinitionGenerator's
// tryToGenerate method (see
// LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction).
//
// Ctx is a context object that will be passed to F. This argument is
// permitted to be null.
//
// Dispose is the disposal function for Ctx. This argument is permitted to be
// null (in which case the client is responsible for the lifetime of Ctx).
//
//go:linkname OrcCreateCustomCAPIDefinitionGenerator C.LLVMOrcCreateCustomCAPIDefinitionGenerator
func OrcCreateCustomCAPIDefinitionGenerator(F OrcCAPIDefinitionGeneratorTryToGenerateFunction, Ctx unsafe.Pointer, Dispose OrcDisposeCAPIDefinitionGeneratorFunction) OrcDefinitionGeneratorRef

// Continue a lookup that was suspended in a generator (see
// LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction).
//
// llgo:link OrcLookupStateRef.ContinueLookup C.LLVMOrcLookupStateContinueLookup
func (self OrcLookupStateRef) ContinueLookup(Err ErrorRef) {
}

// Get a DynamicLibrarySearchGenerator that will reflect process symbols into
// the JITDylib. On success the resulting generator is owned by the client.
// Ownership is typically transferred by adding the instance to a JITDylib
// using LLVMOrcJITDylibAddGenerator,
//
// The GlobalPrefix argument specifies the character that appears on the front
// of linker-mangled symbols for the target platform (e.g. '_' on MachO).
// If non-null, this character will be stripped from the start of all symbol
// strings before passing the remaining substring to dlsym.
//
// The optional Filter and Ctx arguments can be used to supply a symbol name
// filter: Only symbols for which the filter returns true will be visible to
// JIT'd code. If the Filter argument is null then all process symbols will
// be visible to JIT'd code. Note that the symbol name passed to the Filter
// function is the full mangled symbol: The client is responsible for stripping
// the global prefix if present.
//
//go:linkname OrcCreateDynamicLibrarySearchGeneratorForProcess C.LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess
func OrcCreateDynamicLibrarySearchGeneratorForProcess(Result *OrcDefinitionGeneratorRef, GlobalPrefx c.Char, Filter OrcSymbolPredicate, FilterCtx unsafe.Pointer) ErrorRef

// Get a LLVMOrcCreateDynamicLibararySearchGeneratorForPath that will reflect
// library symbols into the JITDylib. On success the resulting generator is
// owned by the client. Ownership is typically transferred by adding the
// instance to a JITDylib using LLVMOrcJITDylibAddGenerator,
//
// The GlobalPrefix argument specifies the character that appears on the front
// of linker-mangled symbols for the target platform (e.g. '_' on MachO).
// If non-null, this character will be stripped from the start of all symbol
// strings before passing the remaining substring to dlsym.
//
// The optional Filter and Ctx arguments can be used to supply a symbol name
// filter: Only symbols for which the filter returns true will be visible to
// JIT'd code. If the Filter argument is null then all library symbols will
// be visible to JIT'd code. Note that the symbol name passed to the Filter
// function is the full mangled symbol: The client is responsible for stripping
// the global prefix if present.
//
// THIS API IS EXPERIMENTAL AND LIKELY TO CHANGE IN THE NEAR FUTURE!
//
//go:linkname OrcCreateDynamicLibrarySearchGeneratorForPath C.LLVMOrcCreateDynamicLibrarySearchGeneratorForPath
func OrcCreateDynamicLibrarySearchGeneratorForPath(Result *OrcDefinitionGeneratorRef, FileName *c.Char, GlobalPrefix c.Char, Filter OrcSymbolPredicate, FilterCtx unsafe.Pointer) ErrorRef

// Get a LLVMOrcCreateStaticLibrarySearchGeneratorForPath that will reflect
// static library symbols into the JITDylib. On success the resulting
// generator is owned by the client. Ownership is typically transferred by
// adding the instance to a JITDylib using LLVMOrcJITDylibAddGenerator,
//
// Call with the optional TargetTriple argument will succeed if the file at
// the given path is a static library or a MachO universal binary containing a
// static library that is compatible with the given triple. Otherwise it will
// return an error.
//
// THIS API IS EXPERIMENTAL AND LIKELY TO CHANGE IN THE NEAR FUTURE!
//
//go:linkname OrcCreateStaticLibrarySearchGeneratorForPath C.LLVMOrcCreateStaticLibrarySearchGeneratorForPath
func OrcCreateStaticLibrarySearchGeneratorForPath(Result *OrcDefinitionGeneratorRef, ObjLayer OrcObjectLayerRef, FileName *c.Char) ErrorRef

// Create a ThreadSafeContextRef containing a new LLVMContext.
//
// Ownership of the underlying ThreadSafeContext data is shared: Clients
// can and should dispose of their ThreadSafeContextRef as soon as they no
// longer need to refer to it directly. Other references (e.g. from
// ThreadSafeModules) will keep the underlying data alive as long as it is
// needed.
//
//go:linkname OrcCreateNewThreadSafeContext C.LLVMOrcCreateNewThreadSafeContext
func OrcCreateNewThreadSafeContext() OrcThreadSafeContextRef

// Create a ThreadSafeContextRef from a given LLVMContext, which must not be
// associated with any existing ThreadSafeContext.
//
// The underlying ThreadSafeContext will take ownership of the LLVMContext
// object, so clients should not free the LLVMContext passed to this
// function.
//
// Ownership of the underlying ThreadSafeContext data is shared: Clients
// can and should dispose of their ThreadSafeContextRef as soon as they no
// longer need to refer to it directly. Other references (e.g. from
// ThreadSafeModules) will keep the underlying data alive as long as it is
// needed.
//
// llgo:link ContextRef.OrcCreateNewThreadSafeContext C.LLVMOrcCreateNewThreadSafeContextFromLLVMContext
func (self ContextRef) OrcCreateNewThreadSafeContext() OrcThreadSafeContextRef {
	return nil
}

// Dispose of a ThreadSafeContext.
//
// llgo:link OrcThreadSafeContextRef.Dispose C.LLVMOrcDisposeThreadSafeContext
func (self OrcThreadSafeContextRef) Dispose() {
}

// Create a ThreadSafeModule wrapper around the given LLVM module. This takes
// ownership of the M argument which should not be disposed of or referenced
// after this function returns.
//
// Ownership of the ThreadSafeModule is unique: If it is transferred to the JIT
// (e.g. by LLVMOrcLLJITAddLLVMIRModule) then the client is no longer
// responsible for it. If it is not transferred to the JIT then the client
// should call LLVMOrcDisposeThreadSafeModule to dispose of it.
//
// llgo:link ModuleRef.OrcCreateNewThreadSafe C.LLVMOrcCreateNewThreadSafeModule
func (self ModuleRef) OrcCreateNewThreadSafe(TSCtx OrcThreadSafeContextRef) OrcThreadSafeModuleRef {
	return nil
}

// Dispose of a ThreadSafeModule. This should only be called if ownership has
// not been passed to LLJIT (e.g. because some error prevented the client from
// adding this to the JIT).
//
// llgo:link OrcThreadSafeModuleRef.Dispose C.LLVMOrcDisposeThreadSafeModule
func (self OrcThreadSafeModuleRef) Dispose() {
}

// Apply the given function to the module contained in this ThreadSafeModule.
//
// llgo:link OrcThreadSafeModuleRef.WithModuleDo C.LLVMOrcThreadSafeModuleWithModuleDo
func (self OrcThreadSafeModuleRef) WithModuleDo(F OrcGenericIRModuleOperationFunction, Ctx unsafe.Pointer) ErrorRef {
	return nil
}

// Create a JITTargetMachineBuilder by detecting the host.
//
// On success the client owns the resulting JITTargetMachineBuilder. It must be
// passed to a consuming operation (e.g.
// LLVMOrcLLJITBuilderSetJITTargetMachineBuilder) or disposed of by calling
// LLVMOrcDisposeJITTargetMachineBuilder.
//
//go:linkname OrcJITTargetMachineBuilderDetectHost C.LLVMOrcJITTargetMachineBuilderDetectHost
func OrcJITTargetMachineBuilderDetectHost(Result *OrcJITTargetMachineBuilderRef) ErrorRef

// Create a JITTargetMachineBuilder from the given TargetMachine template.
//
// This operation takes ownership of the given TargetMachine and destroys it
// before returing. The resulting JITTargetMachineBuilder is owned by the client
// and must be passed to a consuming operation (e.g.
// LLVMOrcLLJITBuilderSetJITTargetMachineBuilder) or disposed of by calling
// LLVMOrcDisposeJITTargetMachineBuilder.
//
// llgo:link TargetMachineRef.OrcJITTargetMachineBuilderCreateFrom C.LLVMOrcJITTargetMachineBuilderCreateFromTargetMachine
func (self TargetMachineRef) OrcJITTargetMachineBuilderCreateFrom() OrcJITTargetMachineBuilderRef {
	return nil
}

// Dispose of a JITTargetMachineBuilder.
//
// llgo:link OrcJITTargetMachineBuilderRef.Dispose C.LLVMOrcDisposeJITTargetMachineBuilder
func (self OrcJITTargetMachineBuilderRef) Dispose() {
}

// Returns the target triple for the given JITTargetMachineBuilder as a string.
//
// The caller owns the resulting string as must dispose of it by calling
// LLVMDisposeMessage
//
// llgo:link OrcJITTargetMachineBuilderRef.TargetTriple C.LLVMOrcJITTargetMachineBuilderGetTargetTriple
func (self OrcJITTargetMachineBuilderRef) TargetTriple() *c.Char {
	return nil
}

// Sets the target triple for the given JITTargetMachineBuilder to the given
// string.
//
// llgo:link OrcJITTargetMachineBuilderRef.SetTargetTriple C.LLVMOrcJITTargetMachineBuilderSetTargetTriple
func (self OrcJITTargetMachineBuilderRef) SetTargetTriple(TargetTriple *c.Char) {
}

// Add an object to an ObjectLayer to the given JITDylib.
//
// Adds a buffer representing an object file to the given JITDylib using the
// given ObjectLayer instance. This operation transfers ownership of the buffer
// to the ObjectLayer instance. The buffer should not be disposed of or
// referenced once this function returns.
//
// Resources associated with the given object will be tracked by the given
// JITDylib's default ResourceTracker.
//
// llgo:link OrcObjectLayerRef.AddObjectFile C.LLVMOrcObjectLayerAddObjectFile
func (self OrcObjectLayerRef) AddObjectFile(JD OrcJITDylibRef, ObjBuffer MemoryBufferRef) ErrorRef {
	return nil
}

// Add an object to an ObjectLayer using the given ResourceTracker.
//
// Adds a buffer representing an object file to the given ResourceTracker's
// JITDylib using the given ObjectLayer instance. This operation transfers
// ownership of the buffer to the ObjectLayer instance. The buffer should not
// be disposed of or referenced once this function returns.
//
// Resources associated with the given object will be tracked by
// ResourceTracker RT.
//
// llgo:link OrcObjectLayerRef.AddObjectFileWithRT C.LLVMOrcObjectLayerAddObjectFileWithRT
func (self OrcObjectLayerRef) AddObjectFileWithRT(RT OrcResourceTrackerRef, ObjBuffer MemoryBufferRef) ErrorRef {
	return nil
}

// Emit an object buffer to an ObjectLayer.
//
// Ownership of the responsibility object and object buffer pass to this
// function. The client is not responsible for cleanup.
//
// llgo:link OrcObjectLayerRef.Emit C.LLVMOrcObjectLayerEmit
func (self OrcObjectLayerRef) Emit(R OrcMaterializationResponsibilityRef, ObjBuffer MemoryBufferRef) {
}

// Dispose of an ObjectLayer.
//
// llgo:link OrcObjectLayerRef.Dispose C.LLVMOrcDisposeObjectLayer
func (self OrcObjectLayerRef) Dispose() {
}

// llgo:link OrcIRTransformLayerRef.Emit C.LLVMOrcIRTransformLayerEmit
func (self OrcIRTransformLayerRef) Emit(MR OrcMaterializationResponsibilityRef, TSM OrcThreadSafeModuleRef) {
}

// Set the transform function of the provided transform layer, passing through a
// pointer to user provided context.
//
// llgo:link OrcIRTransformLayerRef.SetTransform C.LLVMOrcIRTransformLayerSetTransform
func (self OrcIRTransformLayerRef) SetTransform(TransformFunction OrcIRTransformLayerTransformFunction, Ctx unsafe.Pointer) {
}

// Set the transform function on an LLVMOrcObjectTransformLayer.
//
// llgo:link OrcObjectTransformLayerRef.SetTransform C.LLVMOrcObjectTransformLayerSetTransform
func (self OrcObjectTransformLayerRef) SetTransform(TransformFunction OrcObjectTransformLayerTransformFunction, Ctx unsafe.Pointer) {
}

// Create a LocalIndirectStubsManager from the given target triple.
//
// The resulting IndirectStubsManager is owned by the client
// and must be disposed of by calling LLVMOrcDisposeDisposeIndirectStubsManager.
//
//go:linkname OrcCreateLocalIndirectStubsManager C.LLVMOrcCreateLocalIndirectStubsManager
func OrcCreateLocalIndirectStubsManager(TargetTriple *c.Char) OrcIndirectStubsManagerRef

// Dispose of an IndirectStubsManager.
//
// llgo:link OrcIndirectStubsManagerRef.Dispose C.LLVMOrcDisposeIndirectStubsManager
func (self OrcIndirectStubsManagerRef) Dispose() {
}

//go:linkname OrcCreateLocalLazyCallThroughManager C.LLVMOrcCreateLocalLazyCallThroughManager
func OrcCreateLocalLazyCallThroughManager(TargetTriple *c.Char, ES OrcExecutionSessionRef, ErrorHandlerAddr OrcJITTargetAddress, LCTM *OrcLazyCallThroughManagerRef) ErrorRef

// Dispose of an LazyCallThroughManager.
//
// llgo:link OrcLazyCallThroughManagerRef.Dispose C.LLVMOrcDisposeLazyCallThroughManager
func (self OrcLazyCallThroughManagerRef) Dispose() {
}

// Create a DumpObjects instance.
//
// DumpDir specifies the path to write dumped objects to. DumpDir may be empty
// in which case files will be dumped to the working directory.
//
// IdentifierOverride specifies a file name stem to use when dumping objects.
// If empty then each MemoryBuffer's identifier will be used (with a .o suffix
// added if not already present). If an identifier override is supplied it will
// be used instead, along with an incrementing counter (since all buffers will
// use the same identifier, the resulting files will be named <ident>.o,
// <ident>.2.o, <ident>.3.o, and so on). IdentifierOverride should not contain
// an extension, as a .o suffix will be added by DumpObjects.
//
//go:linkname OrcCreateDumpObjects C.LLVMOrcCreateDumpObjects
func OrcCreateDumpObjects(DumpDir *c.Char, IdentifierOverride *c.Char) OrcDumpObjectsRef

// Dispose of a DumpObjects instance.
//
// llgo:link OrcDumpObjectsRef.Dispose C.LLVMOrcDisposeDumpObjects
func (self OrcDumpObjectsRef) Dispose() {
}

// Dump the contents of the given MemoryBuffer.
//
// llgo:link OrcDumpObjectsRef.OrcDumpObjects_CallOperator C.LLVMOrcDumpObjects_CallOperator
func (self OrcDumpObjectsRef) OrcDumpObjects_CallOperator(ObjBuffer *MemoryBufferRef) ErrorRef {
	return nil
}
