// Code generated by llcppg; DO NOT EDIT.

package llvm

import "unsafe"

// llgo:type C
type MemoryManagerCreateContextCallback = func(_llcppg_param1 unsafe.Pointer) unsafe.Pointer

// llgo:type C
type MemoryManagerNotifyTerminatingCallback = func(_llcppg_param1 unsafe.Pointer)

// Create a ObjectLinkingLayer instance using the standard JITLink
// InProcessMemoryManager for memory management.
//
// llgo:link (*OrcOpaqueObjectLayer).OrcCreateObjectLinkingLayerWithInProcessMemoryManager C.LLVMOrcCreateObjectLinkingLayerWithInProcessMemoryManager
func (self *OrcOpaqueObjectLayer) OrcCreateObjectLinkingLayerWithInProcessMemoryManager(ES OrcExecutionSessionRef) ErrorRef {
	return nil
}

// Create a RTDyldObjectLinkingLayer instance using the standard
// SectionMemoryManager for memory management.
//
// llgo:link (*OrcOpaqueExecutionSession).OrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager C.LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager
func (self *OrcOpaqueExecutionSession) OrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManager() OrcObjectLayerRef {
	return nil
}

// Create a RTDyldObjectLinkingLayer instance using the standard
// SectionMemoryManager for memory management. If ReserveAlloc is true then
// a contiguous range of memory will be reserved for each object file.
//
// llgo:link (*OrcOpaqueExecutionSession).OrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManagerReserveAlloc C.LLVMOrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManagerReserveAlloc
func (self *OrcOpaqueExecutionSession) OrcCreateRTDyldObjectLinkingLayerWithSectionMemoryManagerReserveAlloc(ReserveAlloc Bool) OrcObjectLayerRef {
	return nil
}

// Create a RTDyldObjectLinkingLayer instance using MCJIT-memory-manager-like
// callbacks.
//
// This is intended to simplify transitions for existing MCJIT clients. The
// callbacks used are similar (but not identical) to the callbacks for
// LLVMCreateSimpleMCJITMemoryManager: Unlike MCJIT, RTDyldObjectLinkingLayer
// will create a new memory manager for each object linked by calling the given
// CreateContext callback. This allows for code removal by destroying each
// allocator individually. Every allocator will be destroyed (if it has not been
// already) at RTDyldObjectLinkingLayer destruction time, and the
// NotifyTerminating callback will be called to indicate that no further
// allocation contexts will be created.
//
// To implement MCJIT-like behavior clients can implement CreateContext,
// NotifyTerminating, and Destroy as:
//
//   void *CreateContext(void *CtxCtx) { return CtxCtx; }
//   void NotifyTerminating(void *CtxCtx) { MyOriginalDestroy(CtxCtx); }
//   void Destroy(void *Ctx) { }
//
// This scheme simply reuses the CreateContextCtx pointer as the one-and-only
// allocation context.
//
//go:linkname OrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks C.LLVMOrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks
func OrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks(ES OrcExecutionSessionRef, CreateContextCtx unsafe.Pointer, CreateContext MemoryManagerCreateContextCallback, NotifyTerminating MemoryManagerNotifyTerminatingCallback, AllocateCodeSection MemoryManagerAllocateCodeSectionCallback, AllocateDataSection MemoryManagerAllocateDataSectionCallback, FinalizeMemory MemoryManagerFinalizeMemoryCallback, Destroy MemoryManagerDestroyCallback) OrcObjectLayerRef

// Add the given listener to the given RTDyldObjectLinkingLayer.
//
// Note: Layer must be an RTDyldObjectLinkingLayer instance or
// behavior is undefined.
//
// llgo:link (*OrcOpaqueObjectLayer).OrcRTDyldObjectLinkingLayerRegisterJITEventListener C.LLVMOrcRTDyldObjectLinkingLayerRegisterJITEventListener
func (self *OrcOpaqueObjectLayer) OrcRTDyldObjectLinkingLayerRegisterJITEventListener(Listener JITEventListenerRef) {
}
