// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

const REMARKS_API_VERSION = 1

// The type of the emitted remark.
type RemarkType c.Uint

const (
	RemarkTypeUnknown           RemarkType = 0
	RemarkTypePassed            RemarkType = 1
	RemarkTypeMissed            RemarkType = 2
	RemarkTypeAnalysis          RemarkType = 3
	RemarkTypeAnalysisFPCommute RemarkType = 4
	RemarkTypeAnalysisAliasing  RemarkType = 5
	RemarkTypeFailure           RemarkType = 6
)

type RemarkOpaqueString struct {
}

// String containing a buffer and a length. The buffer is not guaranteed to be
// zero-terminated.
//
// \since REMARKS_API_VERSION=0
type RemarkStringRef = *RemarkOpaqueString
type RemarkOpaqueDebugLoc struct {
}

// DebugLoc containing File, Line and Column.
//
// \since REMARKS_API_VERSION=0
type RemarkDebugLocRef = *RemarkOpaqueDebugLoc
type RemarkOpaqueArg struct {
}

// Element of the "Args" list. The key might give more information about what
// the semantics of the value are, e.g. "Callee" will tell you that the value
// is a symbol that names a function.
//
// \since REMARKS_API_VERSION=0
type RemarkArgRef = *RemarkOpaqueArg
type RemarkOpaqueEntry struct {
}

// A remark emitted by the compiler.
//
// \since REMARKS_API_VERSION=0
type RemarkEntryRef = *RemarkOpaqueEntry
type RemarkOpaqueParser struct {
}
type RemarkParserRef = *RemarkOpaqueParser

// Returns the buffer holding the string.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkStringRef.Data C.LLVMRemarkStringGetData
func (self RemarkStringRef) Data() *c.Char {
	return nil
}

// Returns the size of the string.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkStringRef.Len C.LLVMRemarkStringGetLen
func (self RemarkStringRef) Len() c.Uint32T {
	return 0
}

// Return the path to the source file for a debug location.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkDebugLocRef.SourceFilePath C.LLVMRemarkDebugLocGetSourceFilePath
func (self RemarkDebugLocRef) SourceFilePath() RemarkStringRef {
	return nil
}

// Return the line in the source file for a debug location.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkDebugLocRef.SourceLine C.LLVMRemarkDebugLocGetSourceLine
func (self RemarkDebugLocRef) SourceLine() c.Uint32T {
	return 0
}

// Return the column in the source file for a debug location.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkDebugLocRef.SourceColumn C.LLVMRemarkDebugLocGetSourceColumn
func (self RemarkDebugLocRef) SourceColumn() c.Uint32T {
	return 0
}

// Returns the key of an argument. The key defines what the value is, and the
// same key can appear multiple times in the list of arguments.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkArgRef.Key C.LLVMRemarkArgGetKey
func (self RemarkArgRef) Key() RemarkStringRef {
	return nil
}

// Returns the value of an argument. This is a string that can contain newlines.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkArgRef.Value C.LLVMRemarkArgGetValue
func (self RemarkArgRef) Value() RemarkStringRef {
	return nil
}

// Returns the debug location that is attached to the value of this argument.
//
// If there is no debug location, the return value will be `NULL`.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkArgRef.DebugLoc C.LLVMRemarkArgGetDebugLoc
func (self RemarkArgRef) DebugLoc() RemarkDebugLocRef {
	return nil
}

// Free the resources used by the remark entry.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkEntryRef.Dispose C.LLVMRemarkEntryDispose
func (self RemarkEntryRef) Dispose() {
}

// The type of the remark. For example, it can allow users to only keep the
// missed optimizations from the compiler.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkEntryRef.Type C.LLVMRemarkEntryGetType
func (self RemarkEntryRef) Type() RemarkType {
	return 0
}

// Get the name of the pass that emitted this remark.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkEntryRef.PassName C.LLVMRemarkEntryGetPassName
func (self RemarkEntryRef) PassName() RemarkStringRef {
	return nil
}

// Get an identifier of the remark.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkEntryRef.RemarkName C.LLVMRemarkEntryGetRemarkName
func (self RemarkEntryRef) RemarkName() RemarkStringRef {
	return nil
}

// Get the name of the function being processed when the remark was emitted.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkEntryRef.FunctionName C.LLVMRemarkEntryGetFunctionName
func (self RemarkEntryRef) FunctionName() RemarkStringRef {
	return nil
}

// Returns the debug location that is attached to this remark.
//
// If there is no debug location, the return value will be `NULL`.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkEntryRef.DebugLoc C.LLVMRemarkEntryGetDebugLoc
func (self RemarkEntryRef) DebugLoc() RemarkDebugLocRef {
	return nil
}

// Return the hotness of the remark.
//
// A hotness of `0` means this value is not set.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkEntryRef.Hotness C.LLVMRemarkEntryGetHotness
func (self RemarkEntryRef) Hotness() c.Uint64T {
	return 0
}

// The number of arguments the remark holds.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkEntryRef.NumArgs C.LLVMRemarkEntryGetNumArgs
func (self RemarkEntryRef) NumArgs() c.Uint32T {
	return 0
}

// Get a new iterator to iterate over a remark's argument.
//
// If there are no arguments in \p Remark, the return value will be `NULL`.
//
// The lifetime of the returned value is bound to the lifetime of \p Remark.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkEntryRef.FirstArg C.LLVMRemarkEntryGetFirstArg
func (self RemarkEntryRef) FirstArg() RemarkArgRef {
	return nil
}

// Get the next argument in \p Remark from the position of \p It.
//
// Returns `NULL` if there are no more arguments available.
//
// The lifetime of the returned value is bound to the lifetime of \p Remark.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkArgRef.RemarkEntryGetNextArg C.LLVMRemarkEntryGetNextArg
func (self RemarkArgRef) RemarkEntryGetNextArg(Remark RemarkEntryRef) RemarkArgRef {
	return self
}

// Creates a remark parser that can be used to parse the buffer located in \p
// Buf of size \p Size bytes.
//
// \p Buf cannot be `NULL`.
//
// This function should be paired with LLVMRemarkParserDispose() to avoid
// leaking resources.
//
// \since REMARKS_API_VERSION=0
//
//go:linkname RemarkParserCreateYAML C.LLVMRemarkParserCreateYAML
func RemarkParserCreateYAML(Buf unsafe.Pointer, Size c.Uint64T) RemarkParserRef

// Creates a remark parser that can be used to parse the buffer located in \p
// Buf of size \p Size bytes.
//
// \p Buf cannot be `NULL`.
//
// This function should be paired with LLVMRemarkParserDispose() to avoid
// leaking resources.
//
// \since REMARKS_API_VERSION=1
//
//go:linkname RemarkParserCreateBitstream C.LLVMRemarkParserCreateBitstream
func RemarkParserCreateBitstream(Buf unsafe.Pointer, Size c.Uint64T) RemarkParserRef

// Returns the next remark in the file.
//
// The value pointed to by the return value needs to be disposed using a call to
// LLVMRemarkEntryDispose().
//
// All the entries in the returned value that are of LLVMRemarkStringRef type
// will become invalidated once a call to LLVMRemarkParserDispose is made.
//
// If the parser reaches the end of the buffer, the return value will be `NULL`.
//
// In the case of an error, the return value will be `NULL`, and:
//
// 1) LLVMRemarkParserHasError() will return `1`.
//
// 2) LLVMRemarkParserGetErrorMessage() will return a descriptive error
//    message.
//
// An error may occur if:
//
// 1) An argument is invalid.
//
// 2) There is a parsing error. This can occur on things like malformed YAML.
//
// 3) There is a Remark semantic error. This can occur on well-formed files with
//    missing or extra fields.
//
// Here is a quick example of the usage:
//
// ```
// LLVMRemarkParserRef Parser = LLVMRemarkParserCreateYAML(Buf, Size);
// LLVMRemarkEntryRef Remark = NULL;
// while ((Remark = LLVMRemarkParserGetNext(Parser))) {
//    // use Remark
//    LLVMRemarkEntryDispose(Remark); // Release memory.
// }
// bool HasError = LLVMRemarkParserHasError(Parser);
// LLVMRemarkParserDispose(Parser);
// ```
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkParserRef.Next C.LLVMRemarkParserGetNext
func (self RemarkParserRef) Next() RemarkEntryRef {
	return nil
}

// Returns `1` if the parser encountered an error while parsing the buffer.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkParserRef.HasError C.LLVMRemarkParserHasError
func (self RemarkParserRef) HasError() Bool {
	return 0
}

// Returns a null-terminated string containing an error message.
//
// In case of no error, the result is `NULL`.
//
// The memory of the string is bound to the lifetime of \p Parser. If
// LLVMRemarkParserDispose() is called, the memory of the string will be
// released.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkParserRef.ErrorMessage C.LLVMRemarkParserGetErrorMessage
func (self RemarkParserRef) ErrorMessage() *c.Char {
	return nil
}

// Releases all the resources used by \p Parser.
//
// \since REMARKS_API_VERSION=0
//
// llgo:link RemarkParserRef.Dispose C.LLVMRemarkParserDispose
func (self RemarkParserRef) Dispose() {
}

// Returns the version of the remarks library.
//
// \since REMARKS_API_VERSION=0
//
//go:linkname RemarkVersion C.LLVMRemarkVersion
func RemarkVersion() c.Uint32T
