// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	"unsafe"
)

// This function permanently loads the dynamic library at the given path.
// It is safe to call this function multiple times for the same library.
//
// @see sys::DynamicLibrary::LoadLibraryPermanently()
//
//go:linkname LoadLibraryPermanently C.LLVMLoadLibraryPermanently
func LoadLibraryPermanently(Filename *c.Char) Bool

// This function parses the given arguments using the LLVM command line parser.
// Note that the only stable thing about this function is its signature; you
// cannot rely on any particular set of command line arguments being interpreted
// the same way across LLVM versions.
//
// @see llvm::cl::ParseCommandLineOptions()
//
//go:linkname ParseCommandLineOptions C.LLVMParseCommandLineOptions
func ParseCommandLineOptions(argc c.Int, argv **c.Char, Overview *c.Char)

// This function will search through all previously loaded dynamic
// libraries for the symbol \p symbolName. If it is found, the address of
// that symbol is returned. If not, null is returned.
//
// @see sys::DynamicLibrary::SearchForAddressOfSymbol()
//
//go:linkname SearchForAddressOfSymbol C.LLVMSearchForAddressOfSymbol
func SearchForAddressOfSymbol(symbolName *c.Char) unsafe.Pointer

// This functions permanently adds the symbol \p symbolName with the
// value \p symbolValue.  These symbols are searched before any
// libraries.
//
// @see sys::DynamicLibrary::AddSymbol()
//
//go:linkname AddSymbol C.LLVMAddSymbol
func AddSymbol(symbolName *c.Char, symbolValue unsafe.Pointer)
