// Code generated by llcppg; DO NOT EDIT.

package llvm

import _ "unsafe"

//go:linkname InitializeAArch64TargetInfo C.LLVMInitializeAArch64TargetInfo
func InitializeAArch64TargetInfo()

//go:linkname InitializeAMDGPUTargetInfo C.LLVMInitializeAMDGPUTargetInfo
func InitializeAMDGPUTargetInfo()

//go:linkname InitializeARMTargetInfo C.LLVMInitializeARMTargetInfo
func InitializeARMTargetInfo()

//go:linkname InitializeAVRTargetInfo C.LLVMInitializeAVRTargetInfo
func InitializeAVRTargetInfo()

//go:linkname InitializeBPFTargetInfo C.LLVMInitializeBPFTargetInfo
func InitializeBPFTargetInfo()

//go:linkname InitializeHexagonTargetInfo C.LLVMInitializeHexagonTargetInfo
func InitializeHexagonTargetInfo()

//go:linkname InitializeLanaiTargetInfo C.LLVMInitializeLanaiTargetInfo
func InitializeLanaiTargetInfo()

//go:linkname InitializeLoongArchTargetInfo C.LLVMInitializeLoongArchTargetInfo
func InitializeLoongArchTargetInfo()

//go:linkname InitializeMipsTargetInfo C.LLVMInitializeMipsTargetInfo
func InitializeMipsTargetInfo()

//go:linkname InitializeMSP430TargetInfo C.LLVMInitializeMSP430TargetInfo
func InitializeMSP430TargetInfo()

//go:linkname InitializeNVPTXTargetInfo C.LLVMInitializeNVPTXTargetInfo
func InitializeNVPTXTargetInfo()

//go:linkname InitializePowerPCTargetInfo C.LLVMInitializePowerPCTargetInfo
func InitializePowerPCTargetInfo()

//go:linkname InitializeRISCVTargetInfo C.LLVMInitializeRISCVTargetInfo
func InitializeRISCVTargetInfo()

//go:linkname InitializeSparcTargetInfo C.LLVMInitializeSparcTargetInfo
func InitializeSparcTargetInfo()

//go:linkname InitializeSPIRVTargetInfo C.LLVMInitializeSPIRVTargetInfo
func InitializeSPIRVTargetInfo()

//go:linkname InitializeSystemZTargetInfo C.LLVMInitializeSystemZTargetInfo
func InitializeSystemZTargetInfo()

//go:linkname InitializeVETargetInfo C.LLVMInitializeVETargetInfo
func InitializeVETargetInfo()

//go:linkname InitializeWebAssemblyTargetInfo C.LLVMInitializeWebAssemblyTargetInfo
func InitializeWebAssemblyTargetInfo()

//go:linkname InitializeX86TargetInfo C.LLVMInitializeX86TargetInfo
func InitializeX86TargetInfo()

//go:linkname InitializeXCoreTargetInfo C.LLVMInitializeXCoreTargetInfo
func InitializeXCoreTargetInfo()

//go:linkname InitializeAArch64Target C.LLVMInitializeAArch64Target
func InitializeAArch64Target()

//go:linkname InitializeAMDGPUTarget C.LLVMInitializeAMDGPUTarget
func InitializeAMDGPUTarget()

//go:linkname InitializeARMTarget C.LLVMInitializeARMTarget
func InitializeARMTarget()

//go:linkname InitializeAVRTarget C.LLVMInitializeAVRTarget
func InitializeAVRTarget()

//go:linkname InitializeBPFTarget C.LLVMInitializeBPFTarget
func InitializeBPFTarget()

//go:linkname InitializeHexagonTarget C.LLVMInitializeHexagonTarget
func InitializeHexagonTarget()

//go:linkname InitializeLanaiTarget C.LLVMInitializeLanaiTarget
func InitializeLanaiTarget()

//go:linkname InitializeLoongArchTarget C.LLVMInitializeLoongArchTarget
func InitializeLoongArchTarget()

//go:linkname InitializeMipsTarget C.LLVMInitializeMipsTarget
func InitializeMipsTarget()

//go:linkname InitializeMSP430Target C.LLVMInitializeMSP430Target
func InitializeMSP430Target()

//go:linkname InitializeNVPTXTarget C.LLVMInitializeNVPTXTarget
func InitializeNVPTXTarget()

//go:linkname InitializePowerPCTarget C.LLVMInitializePowerPCTarget
func InitializePowerPCTarget()

//go:linkname InitializeRISCVTarget C.LLVMInitializeRISCVTarget
func InitializeRISCVTarget()

//go:linkname InitializeSparcTarget C.LLVMInitializeSparcTarget
func InitializeSparcTarget()

//go:linkname InitializeSPIRVTarget C.LLVMInitializeSPIRVTarget
func InitializeSPIRVTarget()

//go:linkname InitializeSystemZTarget C.LLVMInitializeSystemZTarget
func InitializeSystemZTarget()

//go:linkname InitializeVETarget C.LLVMInitializeVETarget
func InitializeVETarget()

//go:linkname InitializeWebAssemblyTarget C.LLVMInitializeWebAssemblyTarget
func InitializeWebAssemblyTarget()

//go:linkname InitializeX86Target C.LLVMInitializeX86Target
func InitializeX86Target()

//go:linkname InitializeXCoreTarget C.LLVMInitializeXCoreTarget
func InitializeXCoreTarget()

//go:linkname InitializeAArch64TargetMC C.LLVMInitializeAArch64TargetMC
func InitializeAArch64TargetMC()

//go:linkname InitializeAMDGPUTargetMC C.LLVMInitializeAMDGPUTargetMC
func InitializeAMDGPUTargetMC()

//go:linkname InitializeARMTargetMC C.LLVMInitializeARMTargetMC
func InitializeARMTargetMC()

//go:linkname InitializeAVRTargetMC C.LLVMInitializeAVRTargetMC
func InitializeAVRTargetMC()

//go:linkname InitializeBPFTargetMC C.LLVMInitializeBPFTargetMC
func InitializeBPFTargetMC()

//go:linkname InitializeHexagonTargetMC C.LLVMInitializeHexagonTargetMC
func InitializeHexagonTargetMC()

//go:linkname InitializeLanaiTargetMC C.LLVMInitializeLanaiTargetMC
func InitializeLanaiTargetMC()

//go:linkname InitializeLoongArchTargetMC C.LLVMInitializeLoongArchTargetMC
func InitializeLoongArchTargetMC()

//go:linkname InitializeMipsTargetMC C.LLVMInitializeMipsTargetMC
func InitializeMipsTargetMC()

//go:linkname InitializeMSP430TargetMC C.LLVMInitializeMSP430TargetMC
func InitializeMSP430TargetMC()

//go:linkname InitializeNVPTXTargetMC C.LLVMInitializeNVPTXTargetMC
func InitializeNVPTXTargetMC()

//go:linkname InitializePowerPCTargetMC C.LLVMInitializePowerPCTargetMC
func InitializePowerPCTargetMC()

//go:linkname InitializeRISCVTargetMC C.LLVMInitializeRISCVTargetMC
func InitializeRISCVTargetMC()

//go:linkname InitializeSparcTargetMC C.LLVMInitializeSparcTargetMC
func InitializeSparcTargetMC()

//go:linkname InitializeSPIRVTargetMC C.LLVMInitializeSPIRVTargetMC
func InitializeSPIRVTargetMC()

//go:linkname InitializeSystemZTargetMC C.LLVMInitializeSystemZTargetMC
func InitializeSystemZTargetMC()

//go:linkname InitializeVETargetMC C.LLVMInitializeVETargetMC
func InitializeVETargetMC()

//go:linkname InitializeWebAssemblyTargetMC C.LLVMInitializeWebAssemblyTargetMC
func InitializeWebAssemblyTargetMC()

//go:linkname InitializeX86TargetMC C.LLVMInitializeX86TargetMC
func InitializeX86TargetMC()

//go:linkname InitializeXCoreTargetMC C.LLVMInitializeXCoreTargetMC
func InitializeXCoreTargetMC()
