// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type CodeGenOptLevel c.Uint

const (
	CodeGenLevelNone       CodeGenOptLevel = 0
	CodeGenLevelLess       CodeGenOptLevel = 1
	CodeGenLevelDefault    CodeGenOptLevel = 2
	CodeGenLevelAggressive CodeGenOptLevel = 3
)

type RelocMode c.Uint

const (
	RelocDefault      RelocMode = 0
	RelocStatic       RelocMode = 1
	RelocPIC          RelocMode = 2
	RelocDynamicNoPic RelocMode = 3
	RelocROPI         RelocMode = 4
	RelocRWPI         RelocMode = 5
	RelocROPI_RWPI    RelocMode = 6
)

type CodeModel c.Uint

const (
	CodeModelDefault    CodeModel = 0
	CodeModelJITDefault CodeModel = 1
	CodeModelTiny       CodeModel = 2
	CodeModelSmall      CodeModel = 3
	CodeModelKernel     CodeModel = 4
	CodeModelMedium     CodeModel = 5
	CodeModelLarge      CodeModel = 6
)

type CodeGenFileType c.Uint

const (
	AssemblyFile CodeGenFileType = 0
	ObjectFile   CodeGenFileType = 1
)

type GlobalISelAbortMode c.Uint

const (
	GlobalISelAbortEnable          GlobalISelAbortMode = 0
	GlobalISelAbortDisable         GlobalISelAbortMode = 1
	GlobalISelAbortDisableWithDiag GlobalISelAbortMode = 2
)

type OpaqueTargetMachineOptions struct {
}

// @addtogroup LLVMCTarget
//
// @{
type TargetMachineOptionsRef = *OpaqueTargetMachineOptions
type OpaqueTargetMachine struct {
}
type TargetMachineRef = *OpaqueTargetMachine
type Target struct {
}
type TargetRef = *Target

// Returns the first llvm::Target in the registered targets list.
//
//go:linkname GetFirstTarget C.LLVMGetFirstTarget
func GetFirstTarget() TargetRef

// Returns the next llvm::Target given a previous one (or null if there's none)
//
// llgo:link TargetRef.Next C.LLVMGetNextTarget
func (self TargetRef) Next() TargetRef {
	return self
}

// ===-- Target ------------------------------------------------------------===
// Finds the target corresponding to the given name and stores it in \p T.
// Returns 0 on success.
//
//go:linkname GetTargetFromName C.LLVMGetTargetFromName
func GetTargetFromName(Name *c.Char) TargetRef

// Finds the target corresponding to the given triple and stores it in \p T.
// Returns 0 on success. Optionally returns any error in ErrorMessage.
// Use LLVMDisposeMessage to dispose the message.
//
//go:linkname GetTargetFromTriple C.LLVMGetTargetFromTriple
func GetTargetFromTriple(Triple *c.Char, T *TargetRef, ErrorMessage **c.Char) Bool

// Returns the name of a target. See llvm::Target::getName
//
// llgo:link TargetRef.Name C.LLVMGetTargetName
func (self TargetRef) Name() *c.Char {
	return nil
}

// Returns the description  of a target. See llvm::Target::getDescription
//
// llgo:link TargetRef.Description C.LLVMGetTargetDescription
func (self TargetRef) Description() *c.Char {
	return nil
}

// Returns if the target has a JIT
//
// llgo:link TargetRef.HasJIT C.LLVMTargetHasJIT
func (self TargetRef) HasJIT() Bool {
	return 0
}

// Returns if the target has a TargetMachine associated
//
// llgo:link TargetRef.HasTargetMachine C.LLVMTargetHasTargetMachine
func (self TargetRef) HasTargetMachine() Bool {
	return 0
}

// Returns if the target as an ASM backend (required for emitting output)
//
// llgo:link TargetRef.HasAsmBackend C.LLVMTargetHasAsmBackend
func (self TargetRef) HasAsmBackend() Bool {
	return 0
}

// ===-- Target Machine ----------------------------------------------------===
//
// Create a new set of options for an llvm::TargetMachine.
//
// The returned option structure must be released with
// LLVMDisposeTargetMachineOptions() after the call to
// LLVMCreateTargetMachineWithOptions().
//
//go:linkname CreateTargetMachineOptions C.LLVMCreateTargetMachineOptions
func CreateTargetMachineOptions() TargetMachineOptionsRef

// Dispose of an LLVMTargetMachineOptionsRef instance.
//
// llgo:link TargetMachineOptionsRef.Dispose C.LLVMDisposeTargetMachineOptions
func (self TargetMachineOptionsRef) Dispose() {
}

// llgo:link TargetMachineOptionsRef.SetCPU C.LLVMTargetMachineOptionsSetCPU
func (self TargetMachineOptionsRef) SetCPU(CPU *c.Char) {
}

// Set the list of features for the target machine.
//
// \param Features a comma-separated list of features.
//
// llgo:link TargetMachineOptionsRef.SetFeatures C.LLVMTargetMachineOptionsSetFeatures
func (self TargetMachineOptionsRef) SetFeatures(Features *c.Char) {
}

// llgo:link TargetMachineOptionsRef.SetABI C.LLVMTargetMachineOptionsSetABI
func (self TargetMachineOptionsRef) SetABI(ABI *c.Char) {
}

// llgo:link TargetMachineOptionsRef.SetCodeGenOptLevel C.LLVMTargetMachineOptionsSetCodeGenOptLevel
func (self TargetMachineOptionsRef) SetCodeGenOptLevel(Level CodeGenOptLevel) {
}

// llgo:link TargetMachineOptionsRef.SetRelocMode C.LLVMTargetMachineOptionsSetRelocMode
func (self TargetMachineOptionsRef) SetRelocMode(Reloc RelocMode) {
}

// llgo:link TargetMachineOptionsRef.SetCodeModel C.LLVMTargetMachineOptionsSetCodeModel
func (self TargetMachineOptionsRef) SetCodeModel(CodeModel CodeModel) {
}

// Create a new llvm::TargetMachine.
//
// \param T the target to create a machine for.
// \param Triple a triple describing the target machine.
// \param Options additional configuration (see
//                LLVMCreateTargetMachineOptions()).
//
// llgo:link TargetRef.CreateTargetMachineWithOptions C.LLVMCreateTargetMachineWithOptions
func (self TargetRef) CreateTargetMachineWithOptions(Triple *c.Char, Options TargetMachineOptionsRef) TargetMachineRef {
	return nil
}

// Creates a new llvm::TargetMachine. See llvm::Target::createTargetMachine
//
// llgo:link TargetRef.CreateTargetMachine C.LLVMCreateTargetMachine
func (self TargetRef) CreateTargetMachine(Triple *c.Char, CPU *c.Char, Features *c.Char, Level CodeGenOptLevel, Reloc RelocMode, CodeModel CodeModel) TargetMachineRef {
	return nil
}

// Dispose the LLVMTargetMachineRef instance generated by
// LLVMCreateTargetMachine.
//
// llgo:link TargetMachineRef.Dispose C.LLVMDisposeTargetMachine
func (self TargetMachineRef) Dispose() {
}

// Returns the Target used in a TargetMachine
//
// llgo:link TargetMachineRef.Target C.LLVMGetTargetMachineTarget
func (self TargetMachineRef) Target() TargetRef {
	return nil
}

// Returns the triple used creating this target machine. See
// llvm::TargetMachine::getTriple. The result needs to be disposed with
// LLVMDisposeMessage.
//
// llgo:link TargetMachineRef.Triple C.LLVMGetTargetMachineTriple
func (self TargetMachineRef) Triple() *c.Char {
	return nil
}

// Returns the cpu used creating this target machine. See
// llvm::TargetMachine::getCPU. The result needs to be disposed with
// LLVMDisposeMessage.
//
// llgo:link TargetMachineRef.CPU C.LLVMGetTargetMachineCPU
func (self TargetMachineRef) CPU() *c.Char {
	return nil
}

// Returns the feature string used creating this target machine. See
// llvm::TargetMachine::getFeatureString. The result needs to be disposed with
// LLVMDisposeMessage.
//
// llgo:link TargetMachineRef.FeatureString C.LLVMGetTargetMachineFeatureString
func (self TargetMachineRef) FeatureString() *c.Char {
	return nil
}

// Create a DataLayout based on the targetMachine.
//
// llgo:link TargetMachineRef.CreateTargetDataLayout C.LLVMCreateTargetDataLayout
func (self TargetMachineRef) CreateTargetDataLayout() TargetDataRef {
	return nil
}

// Set the target machine's ASM verbosity.
//
// llgo:link TargetMachineRef.SetTargetMachineAsmVerbosity C.LLVMSetTargetMachineAsmVerbosity
func (self TargetMachineRef) SetTargetMachineAsmVerbosity(VerboseAsm Bool) {
}

// Enable fast-path instruction selection.
//
// llgo:link TargetMachineRef.SetTargetMachineFastISel C.LLVMSetTargetMachineFastISel
func (self TargetMachineRef) SetTargetMachineFastISel(Enable Bool) {
}

// Enable global instruction selection.
//
// llgo:link TargetMachineRef.SetTargetMachineGlobalISel C.LLVMSetTargetMachineGlobalISel
func (self TargetMachineRef) SetTargetMachineGlobalISel(Enable Bool) {
}

// Set abort behaviour when global instruction selection fails to lower/select
// an instruction.
//
// llgo:link TargetMachineRef.SetTargetMachineGlobalISelAbort C.LLVMSetTargetMachineGlobalISelAbort
func (self TargetMachineRef) SetTargetMachineGlobalISelAbort(Mode GlobalISelAbortMode) {
}

// Enable the MachineOutliner pass.
//
// llgo:link TargetMachineRef.SetTargetMachineMachineOutliner C.LLVMSetTargetMachineMachineOutliner
func (self TargetMachineRef) SetTargetMachineMachineOutliner(Enable Bool) {
}

// Emits an asm or object file for the given module to the filename. This
// wraps several c++ only classes (among them a file stream). Returns any
// error in ErrorMessage. Use LLVMDisposeMessage to dispose the message.
//
// llgo:link TargetMachineRef.EmitToFile C.LLVMTargetMachineEmitToFile
func (self TargetMachineRef) EmitToFile(M ModuleRef, Filename *c.Char, codegen CodeGenFileType, ErrorMessage **c.Char) Bool {
	return 0
}

// Compile the LLVM IR stored in \p M and store the result in \p OutMemBuf.
//
// llgo:link TargetMachineRef.EmitToMemoryBuffer C.LLVMTargetMachineEmitToMemoryBuffer
func (self TargetMachineRef) EmitToMemoryBuffer(M ModuleRef, codegen CodeGenFileType, ErrorMessage **c.Char, OutMemBuf *MemoryBufferRef) Bool {
	return 0
}

// ===-- Triple ------------------------------------------------------------===
// Get a triple for the host machine as a string. The result needs to be
// disposed with LLVMDisposeMessage.
//
//go:linkname GetDefaultTargetTriple C.LLVMGetDefaultTargetTriple
func GetDefaultTargetTriple() *c.Char

// Normalize a target triple. The result needs to be disposed with
// LLVMDisposeMessage.
//
//go:linkname NormalizeTargetTriple C.LLVMNormalizeTargetTriple
func NormalizeTargetTriple(triple *c.Char) *c.Char

// Get the host CPU as a string. The result needs to be disposed with
// LLVMDisposeMessage.
//
//go:linkname GetHostCPUName C.LLVMGetHostCPUName
func GetHostCPUName() *c.Char

// Get the host CPU's features as a string. The result needs to be disposed
// with LLVMDisposeMessage.
//
//go:linkname GetHostCPUFeatures C.LLVMGetHostCPUFeatures
func GetHostCPUFeatures() *c.Char

// Adds the target-specific analysis passes to the pass manager.
//
// llgo:link TargetMachineRef.AddAnalysisPasses C.LLVMAddAnalysisPasses
func (self TargetMachineRef) AddAnalysisPasses(PM PassManagerRef) {
}
