// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// @defgroup LLVMCTarget Target information
// @ingroup LLVMC
//
// @{
type ByteOrdering c.Int

const (
	BigEndian    ByteOrdering = 0
	LittleEndian ByteOrdering = 1
)

type OpaqueTargetData struct {
}
type TargetDataRef = *OpaqueTargetData
type OpaqueTargetLibraryInfotData struct {
}
type TargetLibraryInfoRef = *OpaqueTargetLibraryInfotData

// Obtain the data layout for a module.
//
// @see Module::getDataLayout()
//
// llgo:link (*OpaqueModule).ModuleDataLayout C.LLVMGetModuleDataLayout
func (self *OpaqueModule) ModuleDataLayout() TargetDataRef {
	return nil
}

// Set the data layout for a module.
//
// @see Module::setDataLayout()
//
// llgo:link (*OpaqueModule).SetModuleDataLayout C.LLVMSetModuleDataLayout
func (self *OpaqueModule) SetModuleDataLayout(DL TargetDataRef) {
}

// Creates target data from a target layout string.
// See the constructor llvm::DataLayout::DataLayout.
//
//go:linkname CreateTargetData C.LLVMCreateTargetData
func CreateTargetData(StringRep *c.Char) TargetDataRef

// Deallocates a TargetData.
// See the destructor llvm::DataLayout::~DataLayout.
//
// llgo:link (*OpaqueTargetData).DisposeTargetData C.LLVMDisposeTargetData
func (self *OpaqueTargetData) DisposeTargetData() {
}

// Adds target library information to a pass manager. This does not take
// ownership of the target library info.
// See the method llvm::PassManagerBase::add.
//
// llgo:link (*OpaqueTargetLibraryInfotData).AddTargetLibraryInfo C.LLVMAddTargetLibraryInfo
func (self *OpaqueTargetLibraryInfotData) AddTargetLibraryInfo(PM PassManagerRef) {
}

// Converts target data to a target layout string. The string must be disposed
// with LLVMDisposeMessage.
// See the constructor llvm::DataLayout::DataLayout.
//
// llgo:link (*OpaqueTargetData).CopyStringRepOfTargetData C.LLVMCopyStringRepOfTargetData
func (self *OpaqueTargetData) CopyStringRepOfTargetData() *c.Char {
	return nil
}

// Returns the byte order of a target, either LLVMBigEndian or
// LLVMLittleEndian.
// See the method llvm::DataLayout::isLittleEndian.
//
// llgo:link (*OpaqueTargetData).ByteOrder C.LLVMByteOrder
func (self *OpaqueTargetData) ByteOrder() ByteOrdering {
	return 0
}

// Returns the pointer size in bytes for a target.
// See the method llvm::DataLayout::getPointerSize.
//
// llgo:link (*OpaqueTargetData).PointerSize C.LLVMPointerSize
func (self *OpaqueTargetData) PointerSize() c.Uint {
	return 0
}

// Returns the pointer size in bytes for a target for a specified
// address space.
// See the method llvm::DataLayout::getPointerSize.
//
// llgo:link (*OpaqueTargetData).PointerSizeForAS C.LLVMPointerSizeForAS
func (self *OpaqueTargetData) PointerSizeForAS(AS c.Uint) c.Uint {
	return 0
}

// Returns the integer type that is the same size as a pointer on a target.
// See the method llvm::DataLayout::getIntPtrType.
//
// llgo:link (*OpaqueTargetData).IntPtrType C.LLVMIntPtrType
func (self *OpaqueTargetData) IntPtrType() TypeRef {
	return nil
}

// Returns the integer type that is the same size as a pointer on a target.
// This version allows the address space to be specified.
// See the method llvm::DataLayout::getIntPtrType.
//
// llgo:link (*OpaqueTargetData).IntPtrTypeForAS C.LLVMIntPtrTypeForAS
func (self *OpaqueTargetData) IntPtrTypeForAS(AS c.Uint) TypeRef {
	return nil
}

// Returns the integer type that is the same size as a pointer on a target.
// See the method llvm::DataLayout::getIntPtrType.
//
// llgo:link (*OpaqueContext).IntPtrTypeInContext C.LLVMIntPtrTypeInContext
func (self *OpaqueContext) IntPtrTypeInContext(TD TargetDataRef) TypeRef {
	return nil
}

// Returns the integer type that is the same size as a pointer on a target.
// This version allows the address space to be specified.
// See the method llvm::DataLayout::getIntPtrType.
//
// llgo:link (*OpaqueContext).IntPtrTypeForASInContext C.LLVMIntPtrTypeForASInContext
func (self *OpaqueContext) IntPtrTypeForASInContext(TD TargetDataRef, AS c.Uint) TypeRef {
	return nil
}

// Computes the size of a type in bits for a target.
// See the method llvm::DataLayout::getTypeSizeInBits.
//
// llgo:link (*OpaqueTargetData).SizeOfTypeInBits C.LLVMSizeOfTypeInBits
func (self *OpaqueTargetData) SizeOfTypeInBits(Ty TypeRef) c.UlongLong {
	return 0
}

// Computes the storage size of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeStoreSize.
//
// llgo:link (*OpaqueTargetData).StoreSizeOfType C.LLVMStoreSizeOfType
func (self *OpaqueTargetData) StoreSizeOfType(Ty TypeRef) c.UlongLong {
	return 0
}

// Computes the ABI size of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeAllocSize.
//
// llgo:link (*OpaqueTargetData).ABISizeOfType C.LLVMABISizeOfType
func (self *OpaqueTargetData) ABISizeOfType(Ty TypeRef) c.UlongLong {
	return 0
}

// Computes the ABI alignment of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeABISize.
//
// llgo:link (*OpaqueTargetData).ABIAlignmentOfType C.LLVMABIAlignmentOfType
func (self *OpaqueTargetData) ABIAlignmentOfType(Ty TypeRef) c.Uint {
	return 0
}

// Computes the call frame alignment of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeABISize.
//
// llgo:link (*OpaqueTargetData).CallFrameAlignmentOfType C.LLVMCallFrameAlignmentOfType
func (self *OpaqueTargetData) CallFrameAlignmentOfType(Ty TypeRef) c.Uint {
	return 0
}

// Computes the preferred alignment of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeABISize.
//
// llgo:link (*OpaqueTargetData).PreferredAlignmentOfType C.LLVMPreferredAlignmentOfType
func (self *OpaqueTargetData) PreferredAlignmentOfType(Ty TypeRef) c.Uint {
	return 0
}

// Computes the preferred alignment of a global variable in bytes for a target.
// See the method llvm::DataLayout::getPreferredAlignment.
//
// llgo:link (*OpaqueTargetData).PreferredAlignmentOfGlobal C.LLVMPreferredAlignmentOfGlobal
func (self *OpaqueTargetData) PreferredAlignmentOfGlobal(GlobalVar ValueRef) c.Uint {
	return 0
}

// Computes the structure element that contains the byte offset for a target.
// See the method llvm::StructLayout::getElementContainingOffset.
//
// llgo:link (*OpaqueTargetData).ElementAtOffset C.LLVMElementAtOffset
func (self *OpaqueTargetData) ElementAtOffset(StructTy TypeRef, Offset c.UlongLong) c.Uint {
	return 0
}

// Computes the byte offset of the indexed struct element for a target.
// See the method llvm::StructLayout::getElementContainingOffset.
//
// llgo:link (*OpaqueTargetData).OffsetOfElement C.LLVMOffsetOfElement
func (self *OpaqueTargetData) OffsetOfElement(StructTy TypeRef, Element c.Uint) c.UlongLong {
	return 0
}
