// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

// @defgroup LLVMCTarget Target information
// @ingroup LLVMC
//
// @{
type ByteOrdering c.Uint

const (
	BigEndian    ByteOrdering = 0
	LittleEndian ByteOrdering = 1
)

type OpaqueTargetData struct {
}
type TargetDataRef = *OpaqueTargetData
type OpaqueTargetLibraryInfotData struct {
}
type TargetLibraryInfoRef = *OpaqueTargetLibraryInfotData

// Obtain the data layout for a module.
//
// @see Module::getDataLayout()
//
// llgo:link ModuleRef.GetModuleDataLayout C.LLVMGetModuleDataLayout
func (self ModuleRef) GetModuleDataLayout() TargetDataRef {
	return nil
}

// Set the data layout for a module.
//
// @see Module::setDataLayout()
//
// llgo:link ModuleRef.SetModuleDataLayout C.LLVMSetModuleDataLayout
func (self ModuleRef) SetModuleDataLayout(DL TargetDataRef) {
}

// Creates target data from a target layout string.
// See the constructor llvm::DataLayout::DataLayout.
//
//go:linkname CreateTargetData C.LLVMCreateTargetData
func CreateTargetData(StringRep *c.Char) TargetDataRef

// Deallocates a TargetData.
// See the destructor llvm::DataLayout::~DataLayout.
//
// llgo:link TargetDataRef.Dispose C.LLVMDisposeTargetData
func (self TargetDataRef) Dispose() {
}

// Adds target library information to a pass manager. This does not take
// ownership of the target library info.
// See the method llvm::PassManagerBase::add.
//
// llgo:link TargetLibraryInfoRef.Add C.LLVMAddTargetLibraryInfo
func (self TargetLibraryInfoRef) Add(PM PassManagerRef) {
}

// Converts target data to a target layout string. The string must be disposed
// with LLVMDisposeMessage.
// See the constructor llvm::DataLayout::DataLayout.
//
// llgo:link TargetDataRef.CopyStringRepOf C.LLVMCopyStringRepOfTargetData
func (self TargetDataRef) CopyStringRepOf() *c.Char {
	return nil
}

// Returns the byte order of a target, either LLVMBigEndian or
// LLVMLittleEndian.
// See the method llvm::DataLayout::isLittleEndian.
//
// llgo:link TargetDataRef.ByteOrder C.LLVMByteOrder
func (self TargetDataRef) ByteOrder() ByteOrdering {
	return 0
}

// Returns the pointer size in bytes for a target.
// See the method llvm::DataLayout::getPointerSize.
//
// llgo:link TargetDataRef.PointerSize C.LLVMPointerSize
func (self TargetDataRef) PointerSize() c.Uint {
	return 0
}

// Returns the pointer size in bytes for a target for a specified
// address space.
// See the method llvm::DataLayout::getPointerSize.
//
// llgo:link TargetDataRef.PointerSizeForAS C.LLVMPointerSizeForAS
func (self TargetDataRef) PointerSizeForAS(AS c.Uint) c.Uint {
	return 0
}

// Returns the integer type that is the same size as a pointer on a target.
// See the method llvm::DataLayout::getIntPtrType.
//
// llgo:link TargetDataRef.IntPtrType C.LLVMIntPtrType
func (self TargetDataRef) IntPtrType() TypeRef {
	return nil
}

// Returns the integer type that is the same size as a pointer on a target.
// This version allows the address space to be specified.
// See the method llvm::DataLayout::getIntPtrType.
//
// llgo:link TargetDataRef.IntPtrTypeForAS C.LLVMIntPtrTypeForAS
func (self TargetDataRef) IntPtrTypeForAS(AS c.Uint) TypeRef {
	return nil
}

// Returns the integer type that is the same size as a pointer on a target.
// See the method llvm::DataLayout::getIntPtrType.
//
// llgo:link ContextRef.IntPtrTypeIn C.LLVMIntPtrTypeInContext
func (self ContextRef) IntPtrTypeIn(TD TargetDataRef) TypeRef {
	return nil
}

// Returns the integer type that is the same size as a pointer on a target.
// This version allows the address space to be specified.
// See the method llvm::DataLayout::getIntPtrType.
//
// llgo:link ContextRef.IntPtrTypeForASIn C.LLVMIntPtrTypeForASInContext
func (self ContextRef) IntPtrTypeForASIn(TD TargetDataRef, AS c.Uint) TypeRef {
	return nil
}

// Computes the size of a type in bits for a target.
// See the method llvm::DataLayout::getTypeSizeInBits.
//
// llgo:link TargetDataRef.SizeOfTypeInBits C.LLVMSizeOfTypeInBits
func (self TargetDataRef) SizeOfTypeInBits(Ty TypeRef) c.UlongLong {
	return 0
}

// Computes the storage size of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeStoreSize.
//
// llgo:link TargetDataRef.StoreSizeOfType C.LLVMStoreSizeOfType
func (self TargetDataRef) StoreSizeOfType(Ty TypeRef) c.UlongLong {
	return 0
}

// Computes the ABI size of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeAllocSize.
//
// llgo:link TargetDataRef.ABISizeOfType C.LLVMABISizeOfType
func (self TargetDataRef) ABISizeOfType(Ty TypeRef) c.UlongLong {
	return 0
}

// Computes the ABI alignment of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeABISize.
//
// llgo:link TargetDataRef.ABIAlignmentOfType C.LLVMABIAlignmentOfType
func (self TargetDataRef) ABIAlignmentOfType(Ty TypeRef) c.Uint {
	return 0
}

// Computes the call frame alignment of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeABISize.
//
// llgo:link TargetDataRef.CallFrameAlignmentOfType C.LLVMCallFrameAlignmentOfType
func (self TargetDataRef) CallFrameAlignmentOfType(Ty TypeRef) c.Uint {
	return 0
}

// Computes the preferred alignment of a type in bytes for a target.
// See the method llvm::DataLayout::getTypeABISize.
//
// llgo:link TargetDataRef.PreferredAlignmentOfType C.LLVMPreferredAlignmentOfType
func (self TargetDataRef) PreferredAlignmentOfType(Ty TypeRef) c.Uint {
	return 0
}

// Computes the preferred alignment of a global variable in bytes for a target.
// See the method llvm::DataLayout::getPreferredAlignment.
//
// llgo:link TargetDataRef.PreferredAlignmentOfGlobal C.LLVMPreferredAlignmentOfGlobal
func (self TargetDataRef) PreferredAlignmentOfGlobal(GlobalVar ValueRef) c.Uint {
	return 0
}

// Computes the structure element that contains the byte offset for a target.
// See the method llvm::StructLayout::getElementContainingOffset.
//
// llgo:link TargetDataRef.ElementAtOffset C.LLVMElementAtOffset
func (self TargetDataRef) ElementAtOffset(StructTy TypeRef, Offset c.UlongLong) c.Uint {
	return 0
}

// Computes the byte offset of the indexed struct element for a target.
// See the method llvm::StructLayout::getElementContainingOffset.
//
// llgo:link TargetDataRef.OffsetOfElement C.LLVMOffsetOfElement
func (self TargetDataRef) OffsetOfElement(StructTy TypeRef, Element c.Uint) c.UlongLong {
	return 0
}
