// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type OpaqueTargetMachineOptions struct {
}

// @addtogroup LLVMCTarget
//
// @{
type TargetMachineOptionsRef = *OpaqueTargetMachineOptions
type OpaqueTargetMachine struct {
}
type TargetMachineRef = *OpaqueTargetMachine
type Target struct {
}
type TargetRef = *Target
type CodeGenOptLevel c.Int

const (
	CodeGenLevelNone       CodeGenOptLevel = 0
	CodeGenLevelLess       CodeGenOptLevel = 1
	CodeGenLevelDefault    CodeGenOptLevel = 2
	CodeGenLevelAggressive CodeGenOptLevel = 3
)

type RelocMode c.Int

const (
	RelocDefault      RelocMode = 0
	RelocStatic       RelocMode = 1
	RelocPIC          RelocMode = 2
	RelocDynamicNoPic RelocMode = 3
	RelocROPI         RelocMode = 4
	RelocRWPI         RelocMode = 5
	RelocROPI_RWPI    RelocMode = 6
)

type CodeModel c.Int

const (
	CodeModelDefault    CodeModel = 0
	CodeModelJITDefault CodeModel = 1
	CodeModelTiny       CodeModel = 2
	CodeModelSmall      CodeModel = 3
	CodeModelKernel     CodeModel = 4
	CodeModelMedium     CodeModel = 5
	CodeModelLarge      CodeModel = 6
)

type CodeGenFileType c.Int

const (
	AssemblyFile CodeGenFileType = 0
	ObjectFile   CodeGenFileType = 1
)

type GlobalISelAbortMode c.Int

const (
	GlobalISelAbortEnable          GlobalISelAbortMode = 0
	GlobalISelAbortDisable         GlobalISelAbortMode = 1
	GlobalISelAbortDisableWithDiag GlobalISelAbortMode = 2
)

// Returns the first llvm::Target in the registered targets list.
//
//go:linkname GetFirstTarget C.LLVMGetFirstTarget
func GetFirstTarget() TargetRef

// Returns the next llvm::Target given a previous one (or null if there's none)
//
// llgo:link (*Target).NextTarget C.LLVMGetNextTarget
func (self *Target) NextTarget() TargetRef {
	return self
}

// Finds the target corresponding to the given name and stores it in \p T.
// Returns 0 on success.
//
//go:linkname GetTargetFromName C.LLVMGetTargetFromName
func GetTargetFromName(Name *c.Char) TargetRef

// Finds the target corresponding to the given triple and stores it in \p T.
// Returns 0 on success. Optionally returns any error in ErrorMessage.
// Use LLVMDisposeMessage to dispose the message.
//
//go:linkname GetTargetFromTriple C.LLVMGetTargetFromTriple
func GetTargetFromTriple(Triple *c.Char, T *TargetRef, ErrorMessage **c.Char) Bool

// Returns the name of a target. See llvm::Target::getName
//
// llgo:link (*Target).TargetName C.LLVMGetTargetName
func (self *Target) TargetName() *c.Char {
	return nil
}

// Returns the description  of a target. See llvm::Target::getDescription
//
// llgo:link (*Target).TargetDescription C.LLVMGetTargetDescription
func (self *Target) TargetDescription() *c.Char {
	return nil
}

// Returns if the target has a JIT
//
// llgo:link (*Target).TargetHasJIT C.LLVMTargetHasJIT
func (self *Target) TargetHasJIT() Bool {
	return 0
}

// Returns if the target has a TargetMachine associated
//
// llgo:link (*Target).TargetHasTargetMachine C.LLVMTargetHasTargetMachine
func (self *Target) TargetHasTargetMachine() Bool {
	return 0
}

// Returns if the target as an ASM backend (required for emitting output)
//
// llgo:link (*Target).TargetHasAsmBackend C.LLVMTargetHasAsmBackend
func (self *Target) TargetHasAsmBackend() Bool {
	return 0
}

// Create a new set of options for an llvm::TargetMachine.
//
// The returned option structure must be released with
// LLVMDisposeTargetMachineOptions() after the call to
// LLVMCreateTargetMachineWithOptions().
//
//go:linkname CreateTargetMachineOptions C.LLVMCreateTargetMachineOptions
func CreateTargetMachineOptions() TargetMachineOptionsRef

// Dispose of an LLVMTargetMachineOptionsRef instance.
//
// llgo:link (*OpaqueTargetMachineOptions).DisposeTargetMachineOptions C.LLVMDisposeTargetMachineOptions
func (self *OpaqueTargetMachineOptions) DisposeTargetMachineOptions() {
}

// llgo:link (*OpaqueTargetMachineOptions).TargetMachineOptionsSetCPU C.LLVMTargetMachineOptionsSetCPU
func (self *OpaqueTargetMachineOptions) TargetMachineOptionsSetCPU(CPU *c.Char) {
}

// Set the list of features for the target machine.
//
// \param Features a comma-separated list of features.
//
// llgo:link (*OpaqueTargetMachineOptions).TargetMachineOptionsSetFeatures C.LLVMTargetMachineOptionsSetFeatures
func (self *OpaqueTargetMachineOptions) TargetMachineOptionsSetFeatures(Features *c.Char) {
}

// llgo:link (*OpaqueTargetMachineOptions).TargetMachineOptionsSetABI C.LLVMTargetMachineOptionsSetABI
func (self *OpaqueTargetMachineOptions) TargetMachineOptionsSetABI(ABI *c.Char) {
}

// llgo:link (*OpaqueTargetMachineOptions).TargetMachineOptionsSetCodeGenOptLevel C.LLVMTargetMachineOptionsSetCodeGenOptLevel
func (self *OpaqueTargetMachineOptions) TargetMachineOptionsSetCodeGenOptLevel(Level CodeGenOptLevel) {
}

// llgo:link (*OpaqueTargetMachineOptions).TargetMachineOptionsSetRelocMode C.LLVMTargetMachineOptionsSetRelocMode
func (self *OpaqueTargetMachineOptions) TargetMachineOptionsSetRelocMode(Reloc RelocMode) {
}

// llgo:link (*OpaqueTargetMachineOptions).TargetMachineOptionsSetCodeModel C.LLVMTargetMachineOptionsSetCodeModel
func (self *OpaqueTargetMachineOptions) TargetMachineOptionsSetCodeModel(CodeModel CodeModel) {
}

// Create a new llvm::TargetMachine.
//
// \param T the target to create a machine for.
// \param Triple a triple describing the target machine.
// \param Options additional configuration (see
//                LLVMCreateTargetMachineOptions()).
//
// llgo:link (*Target).CreateTargetMachineWithOptions C.LLVMCreateTargetMachineWithOptions
func (self *Target) CreateTargetMachineWithOptions(Triple *c.Char, Options TargetMachineOptionsRef) TargetMachineRef {
	return nil
}

// Creates a new llvm::TargetMachine. See llvm::Target::createTargetMachine
//
// llgo:link (*Target).CreateTargetMachine C.LLVMCreateTargetMachine
func (self *Target) CreateTargetMachine(Triple *c.Char, CPU *c.Char, Features *c.Char, Level CodeGenOptLevel, Reloc RelocMode, CodeModel CodeModel) TargetMachineRef {
	return nil
}

// Dispose the LLVMTargetMachineRef instance generated by
// LLVMCreateTargetMachine.
//
// llgo:link (*OpaqueTargetMachine).DisposeTargetMachine C.LLVMDisposeTargetMachine
func (self *OpaqueTargetMachine) DisposeTargetMachine() {
}

// Returns the Target used in a TargetMachine
//
// llgo:link (*OpaqueTargetMachine).TargetMachineTarget C.LLVMGetTargetMachineTarget
func (self *OpaqueTargetMachine) TargetMachineTarget() TargetRef {
	return nil
}

// Returns the triple used creating this target machine. See
// llvm::TargetMachine::getTriple. The result needs to be disposed with
// LLVMDisposeMessage.
//
// llgo:link (*OpaqueTargetMachine).TargetMachineTriple C.LLVMGetTargetMachineTriple
func (self *OpaqueTargetMachine) TargetMachineTriple() *c.Char {
	return nil
}

// Returns the cpu used creating this target machine. See
// llvm::TargetMachine::getCPU. The result needs to be disposed with
// LLVMDisposeMessage.
//
// llgo:link (*OpaqueTargetMachine).TargetMachineCPU C.LLVMGetTargetMachineCPU
func (self *OpaqueTargetMachine) TargetMachineCPU() *c.Char {
	return nil
}

// Returns the feature string used creating this target machine. See
// llvm::TargetMachine::getFeatureString. The result needs to be disposed with
// LLVMDisposeMessage.
//
// llgo:link (*OpaqueTargetMachine).TargetMachineFeatureString C.LLVMGetTargetMachineFeatureString
func (self *OpaqueTargetMachine) TargetMachineFeatureString() *c.Char {
	return nil
}

// Create a DataLayout based on the targetMachine.
//
// llgo:link (*OpaqueTargetMachine).CreateTargetDataLayout C.LLVMCreateTargetDataLayout
func (self *OpaqueTargetMachine) CreateTargetDataLayout() TargetDataRef {
	return nil
}

// Set the target machine's ASM verbosity.
//
// llgo:link (*OpaqueTargetMachine).SetTargetMachineAsmVerbosity C.LLVMSetTargetMachineAsmVerbosity
func (self *OpaqueTargetMachine) SetTargetMachineAsmVerbosity(VerboseAsm Bool) {
}

// Enable fast-path instruction selection.
//
// llgo:link (*OpaqueTargetMachine).SetTargetMachineFastISel C.LLVMSetTargetMachineFastISel
func (self *OpaqueTargetMachine) SetTargetMachineFastISel(Enable Bool) {
}

// Enable global instruction selection.
//
// llgo:link (*OpaqueTargetMachine).SetTargetMachineGlobalISel C.LLVMSetTargetMachineGlobalISel
func (self *OpaqueTargetMachine) SetTargetMachineGlobalISel(Enable Bool) {
}

// Set abort behaviour when global instruction selection fails to lower/select
// an instruction.
//
// llgo:link (*OpaqueTargetMachine).SetTargetMachineGlobalISelAbort C.LLVMSetTargetMachineGlobalISelAbort
func (self *OpaqueTargetMachine) SetTargetMachineGlobalISelAbort(Mode GlobalISelAbortMode) {
}

// Enable the MachineOutliner pass.
//
// llgo:link (*OpaqueTargetMachine).SetTargetMachineMachineOutliner C.LLVMSetTargetMachineMachineOutliner
func (self *OpaqueTargetMachine) SetTargetMachineMachineOutliner(Enable Bool) {
}

// Emits an asm or object file for the given module to the filename. This
// wraps several c++ only classes (among them a file stream). Returns any
// error in ErrorMessage. Use LLVMDisposeMessage to dispose the message.
//
// llgo:link (*OpaqueTargetMachine).TargetMachineEmitToFile C.LLVMTargetMachineEmitToFile
func (self *OpaqueTargetMachine) TargetMachineEmitToFile(M ModuleRef, Filename *c.Char, codegen CodeGenFileType, ErrorMessage **c.Char) Bool {
	return 0
}

// Compile the LLVM IR stored in \p M and store the result in \p OutMemBuf.
//
// llgo:link (*OpaqueTargetMachine).TargetMachineEmitToMemoryBuffer C.LLVMTargetMachineEmitToMemoryBuffer
func (self *OpaqueTargetMachine) TargetMachineEmitToMemoryBuffer(M ModuleRef, codegen CodeGenFileType, ErrorMessage **c.Char, OutMemBuf *MemoryBufferRef) Bool {
	return 0
}

// Get a triple for the host machine as a string. The result needs to be
// disposed with LLVMDisposeMessage.
//
//go:linkname GetDefaultTargetTriple C.LLVMGetDefaultTargetTriple
func GetDefaultTargetTriple() *c.Char

// Normalize a target triple. The result needs to be disposed with
// LLVMDisposeMessage.
//
//go:linkname NormalizeTargetTriple C.LLVMNormalizeTargetTriple
func NormalizeTargetTriple(triple *c.Char) *c.Char

// Get the host CPU as a string. The result needs to be disposed with
// LLVMDisposeMessage.
//
//go:linkname GetHostCPUName C.LLVMGetHostCPUName
func GetHostCPUName() *c.Char

// Get the host CPU's features as a string. The result needs to be disposed
// with LLVMDisposeMessage.
//
//go:linkname GetHostCPUFeatures C.LLVMGetHostCPUFeatures
func GetHostCPUFeatures() *c.Char

// Adds the target-specific analysis passes to the pass manager.
//
// llgo:link (*OpaqueTargetMachine).AddAnalysisPasses C.LLVMAddAnalysisPasses
func (self *OpaqueTargetMachine) AddAnalysisPasses(PM PassManagerRef) {
}
