// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type OpaquePassBuilderOptions struct {
}

// A set of options passed which are attached to the Pass Manager upon run.
//
// This corresponds to an llvm::LLVMPassBuilderOptions instance
//
// The details for how the different properties of this structure are used can
// be found in the source for LLVMRunPasses
type PassBuilderOptionsRef = *OpaquePassBuilderOptions

// Construct and run a set of passes over a module
//
// This function takes a string with the passes that should be used. The format
// of this string is the same as opt's -passes argument for the new pass
// manager. Individual passes may be specified, separated by commas. Full
// pipelines may also be invoked using `default<O3>` and friends. See opt for
// full reference of the Passes format.
//
// llgo:link ModuleRef.RunPasses C.LLVMRunPasses
func (self ModuleRef) RunPasses(Passes *c.Char, TM TargetMachineRef, Options PassBuilderOptionsRef) ErrorRef {
	return nil
}

// Construct and run a set of passes over a function.
//
// This function behaves the same as LLVMRunPasses, but operates on a single
// function instead of an entire module.
//
// llgo:link ValueRef.RunPassesOnFunction C.LLVMRunPassesOnFunction
func (self ValueRef) RunPassesOnFunction(Passes *c.Char, TM TargetMachineRef, Options PassBuilderOptionsRef) ErrorRef {
	return nil
}

// Create a new set of options for a PassBuilder
//
// Ownership of the returned instance is given to the client, and they are
// responsible for it. The client should call LLVMDisposePassBuilderOptions
// to free the pass builder options.
//
//go:linkname CreatePassBuilderOptions C.LLVMCreatePassBuilderOptions
func CreatePassBuilderOptions() PassBuilderOptionsRef

// Toggle adding the VerifierPass for the PassBuilder, ensuring all functions
// inside the module is valid.
//
// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetVerifyEach C.LLVMPassBuilderOptionsSetVerifyEach
func (self PassBuilderOptionsRef) PassBuilderOptionsSetVerifyEach(VerifyEach Bool) {
}

// Toggle debug logging when running the PassBuilder
//
// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetDebugLogging C.LLVMPassBuilderOptionsSetDebugLogging
func (self PassBuilderOptionsRef) PassBuilderOptionsSetDebugLogging(DebugLogging Bool) {
}

// Specify a custom alias analysis pipeline for the PassBuilder to be used
// instead of the default one. The string argument is not copied; the caller
// is responsible for ensuring it outlives the PassBuilderOptions instance.
//
// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetAAPipeline C.LLVMPassBuilderOptionsSetAAPipeline
func (self PassBuilderOptionsRef) PassBuilderOptionsSetAAPipeline(AAPipeline *c.Char) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetLoopInterleaving C.LLVMPassBuilderOptionsSetLoopInterleaving
func (self PassBuilderOptionsRef) PassBuilderOptionsSetLoopInterleaving(LoopInterleaving Bool) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetLoopVectorization C.LLVMPassBuilderOptionsSetLoopVectorization
func (self PassBuilderOptionsRef) PassBuilderOptionsSetLoopVectorization(LoopVectorization Bool) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetSLPVectorization C.LLVMPassBuilderOptionsSetSLPVectorization
func (self PassBuilderOptionsRef) PassBuilderOptionsSetSLPVectorization(SLPVectorization Bool) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetLoopUnrolling C.LLVMPassBuilderOptionsSetLoopUnrolling
func (self PassBuilderOptionsRef) PassBuilderOptionsSetLoopUnrolling(LoopUnrolling Bool) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetForgetAllSCEVInLoopUnroll C.LLVMPassBuilderOptionsSetForgetAllSCEVInLoopUnroll
func (self PassBuilderOptionsRef) PassBuilderOptionsSetForgetAllSCEVInLoopUnroll(ForgetAllSCEVInLoopUnroll Bool) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetLicmMssaOptCap C.LLVMPassBuilderOptionsSetLicmMssaOptCap
func (self PassBuilderOptionsRef) PassBuilderOptionsSetLicmMssaOptCap(LicmMssaOptCap c.Uint) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetLicmMssaNoAccForPromotionCap C.LLVMPassBuilderOptionsSetLicmMssaNoAccForPromotionCap
func (self PassBuilderOptionsRef) PassBuilderOptionsSetLicmMssaNoAccForPromotionCap(LicmMssaNoAccForPromotionCap c.Uint) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetCallGraphProfile C.LLVMPassBuilderOptionsSetCallGraphProfile
func (self PassBuilderOptionsRef) PassBuilderOptionsSetCallGraphProfile(CallGraphProfile Bool) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetMergeFunctions C.LLVMPassBuilderOptionsSetMergeFunctions
func (self PassBuilderOptionsRef) PassBuilderOptionsSetMergeFunctions(MergeFunctions Bool) {
}

// llgo:link PassBuilderOptionsRef.PassBuilderOptionsSetInlinerThreshold C.LLVMPassBuilderOptionsSetInlinerThreshold
func (self PassBuilderOptionsRef) PassBuilderOptionsSetInlinerThreshold(Threshold c.Int) {
}

// Dispose of a heap-allocated PassBuilderOptions instance
//
// llgo:link PassBuilderOptionsRef.DisposePassBuilderOptions C.LLVMDisposePassBuilderOptions
func (self PassBuilderOptionsRef) DisposePassBuilderOptions() {
}
