// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type OpaquePassBuilderOptions struct {
}

// A set of options passed which are attached to the Pass Manager upon run.
//
// This corresponds to an llvm::LLVMPassBuilderOptions instance
//
// The details for how the different properties of this structure are used can
// be found in the source for LLVMRunPasses
type PassBuilderOptionsRef = *OpaquePassBuilderOptions

// Construct and run a set of passes over a module
//
// This function takes a string with the passes that should be used. The format
// of this string is the same as opt's -passes argument for the new pass
// manager. Individual passes may be specified, separated by commas. Full
// pipelines may also be invoked using `default<O3>` and friends. See opt for
// full reference of the Passes format.
//
// llgo:link (*OpaqueModule).RunPasses C.LLVMRunPasses
func (self *OpaqueModule) RunPasses(Passes *c.Char, TM TargetMachineRef, Options PassBuilderOptionsRef) ErrorRef {
	return nil
}

// Construct and run a set of passes over a function.
//
// This function behaves the same as LLVMRunPasses, but operates on a single
// function instead of an entire module.
//
// llgo:link (*OpaqueValue).RunPassesOnFunction C.LLVMRunPassesOnFunction
func (self *OpaqueValue) RunPassesOnFunction(Passes *c.Char, TM TargetMachineRef, Options PassBuilderOptionsRef) ErrorRef {
	return nil
}

// Create a new set of options for a PassBuilder
//
// Ownership of the returned instance is given to the client, and they are
// responsible for it. The client should call LLVMDisposePassBuilderOptions
// to free the pass builder options.
//
//go:linkname CreatePassBuilderOptions C.LLVMCreatePassBuilderOptions
func CreatePassBuilderOptions() PassBuilderOptionsRef

// Toggle adding the VerifierPass for the PassBuilder, ensuring all functions
// inside the module is valid.
//
// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetVerifyEach C.LLVMPassBuilderOptionsSetVerifyEach
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetVerifyEach(VerifyEach Bool) {
}

// Toggle debug logging when running the PassBuilder
//
// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetDebugLogging C.LLVMPassBuilderOptionsSetDebugLogging
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetDebugLogging(DebugLogging Bool) {
}

// Specify a custom alias analysis pipeline for the PassBuilder to be used
// instead of the default one. The string argument is not copied; the caller
// is responsible for ensuring it outlives the PassBuilderOptions instance.
//
// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetAAPipeline C.LLVMPassBuilderOptionsSetAAPipeline
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetAAPipeline(AAPipeline *c.Char) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetLoopInterleaving C.LLVMPassBuilderOptionsSetLoopInterleaving
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetLoopInterleaving(LoopInterleaving Bool) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetLoopVectorization C.LLVMPassBuilderOptionsSetLoopVectorization
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetLoopVectorization(LoopVectorization Bool) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetSLPVectorization C.LLVMPassBuilderOptionsSetSLPVectorization
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetSLPVectorization(SLPVectorization Bool) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetLoopUnrolling C.LLVMPassBuilderOptionsSetLoopUnrolling
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetLoopUnrolling(LoopUnrolling Bool) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetForgetAllSCEVInLoopUnroll C.LLVMPassBuilderOptionsSetForgetAllSCEVInLoopUnroll
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetForgetAllSCEVInLoopUnroll(ForgetAllSCEVInLoopUnroll Bool) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetLicmMssaOptCap C.LLVMPassBuilderOptionsSetLicmMssaOptCap
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetLicmMssaOptCap(LicmMssaOptCap c.Uint) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetLicmMssaNoAccForPromotionCap C.LLVMPassBuilderOptionsSetLicmMssaNoAccForPromotionCap
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetLicmMssaNoAccForPromotionCap(LicmMssaNoAccForPromotionCap c.Uint) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetCallGraphProfile C.LLVMPassBuilderOptionsSetCallGraphProfile
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetCallGraphProfile(CallGraphProfile Bool) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetMergeFunctions C.LLVMPassBuilderOptionsSetMergeFunctions
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetMergeFunctions(MergeFunctions Bool) {
}

// llgo:link (*OpaquePassBuilderOptions).PassBuilderOptionsSetInlinerThreshold C.LLVMPassBuilderOptionsSetInlinerThreshold
func (self *OpaquePassBuilderOptions) PassBuilderOptionsSetInlinerThreshold(Threshold c.Int) {
}

// Dispose of a heap-allocated PassBuilderOptions instance
//
// llgo:link (*OpaquePassBuilderOptions).DisposePassBuilderOptions C.LLVMDisposePassBuilderOptions
func (self *OpaquePassBuilderOptions) DisposePassBuilderOptions() {
}
