// Code generated by llcppg; DO NOT EDIT.

package llvm

import (
	"github.com/goplus/lib/c"
	_ "unsafe"
)

type OpaquePassBuilderOptions struct {
}

// A set of options passed which are attached to the Pass Manager upon run.
//
// This corresponds to an llvm::LLVMPassBuilderOptions instance
//
// The details for how the different properties of this structure are used can
// be found in the source for LLVMRunPasses
type PassBuilderOptionsRef = *OpaquePassBuilderOptions

// Construct and run a set of passes over a module
//
// This function takes a string with the passes that should be used. The format
// of this string is the same as opt's -passes argument for the new pass
// manager. Individual passes may be specified, separated by commas. Full
// pipelines may also be invoked using `default<O3>` and friends. See opt for
// full reference of the Passes format.
//
// llgo:link ModuleRef.RunPasses C.LLVMRunPasses
func (self ModuleRef) RunPasses(Passes *c.Char, TM TargetMachineRef, Options PassBuilderOptionsRef) ErrorRef {
	return nil
}

// Construct and run a set of passes over a function.
//
// This function behaves the same as LLVMRunPasses, but operates on a single
// function instead of an entire module.
//
// llgo:link ValueRef.RunPassesOnFunction C.LLVMRunPassesOnFunction
func (self ValueRef) RunPassesOnFunction(Passes *c.Char, TM TargetMachineRef, Options PassBuilderOptionsRef) ErrorRef {
	return nil
}

// Create a new set of options for a PassBuilder
//
// Ownership of the returned instance is given to the client, and they are
// responsible for it. The client should call LLVMDisposePassBuilderOptions
// to free the pass builder options.
//
//go:linkname CreatePassBuilderOptions C.LLVMCreatePassBuilderOptions
func CreatePassBuilderOptions() PassBuilderOptionsRef

// Toggle adding the VerifierPass for the PassBuilder, ensuring all functions
// inside the module is valid.
//
// llgo:link PassBuilderOptionsRef.SetVerifyEach C.LLVMPassBuilderOptionsSetVerifyEach
func (self PassBuilderOptionsRef) SetVerifyEach(VerifyEach Bool) {
}

// Toggle debug logging when running the PassBuilder
//
// llgo:link PassBuilderOptionsRef.SetDebugLogging C.LLVMPassBuilderOptionsSetDebugLogging
func (self PassBuilderOptionsRef) SetDebugLogging(DebugLogging Bool) {
}

// Specify a custom alias analysis pipeline for the PassBuilder to be used
// instead of the default one. The string argument is not copied; the caller
// is responsible for ensuring it outlives the PassBuilderOptions instance.
//
// llgo:link PassBuilderOptionsRef.SetAAPipeline C.LLVMPassBuilderOptionsSetAAPipeline
func (self PassBuilderOptionsRef) SetAAPipeline(AAPipeline *c.Char) {
}

// llgo:link PassBuilderOptionsRef.SetLoopInterleaving C.LLVMPassBuilderOptionsSetLoopInterleaving
func (self PassBuilderOptionsRef) SetLoopInterleaving(LoopInterleaving Bool) {
}

// llgo:link PassBuilderOptionsRef.SetLoopVectorization C.LLVMPassBuilderOptionsSetLoopVectorization
func (self PassBuilderOptionsRef) SetLoopVectorization(LoopVectorization Bool) {
}

// llgo:link PassBuilderOptionsRef.SetSLPVectorization C.LLVMPassBuilderOptionsSetSLPVectorization
func (self PassBuilderOptionsRef) SetSLPVectorization(SLPVectorization Bool) {
}

// llgo:link PassBuilderOptionsRef.SetLoopUnrolling C.LLVMPassBuilderOptionsSetLoopUnrolling
func (self PassBuilderOptionsRef) SetLoopUnrolling(LoopUnrolling Bool) {
}

// llgo:link PassBuilderOptionsRef.SetForgetAllSCEVInLoopUnroll C.LLVMPassBuilderOptionsSetForgetAllSCEVInLoopUnroll
func (self PassBuilderOptionsRef) SetForgetAllSCEVInLoopUnroll(ForgetAllSCEVInLoopUnroll Bool) {
}

// llgo:link PassBuilderOptionsRef.SetLicmMssaOptCap C.LLVMPassBuilderOptionsSetLicmMssaOptCap
func (self PassBuilderOptionsRef) SetLicmMssaOptCap(LicmMssaOptCap c.Uint) {
}

// llgo:link PassBuilderOptionsRef.SetLicmMssaNoAccForPromotionCap C.LLVMPassBuilderOptionsSetLicmMssaNoAccForPromotionCap
func (self PassBuilderOptionsRef) SetLicmMssaNoAccForPromotionCap(LicmMssaNoAccForPromotionCap c.Uint) {
}

// llgo:link PassBuilderOptionsRef.SetCallGraphProfile C.LLVMPassBuilderOptionsSetCallGraphProfile
func (self PassBuilderOptionsRef) SetCallGraphProfile(CallGraphProfile Bool) {
}

// llgo:link PassBuilderOptionsRef.SetMergeFunctions C.LLVMPassBuilderOptionsSetMergeFunctions
func (self PassBuilderOptionsRef) SetMergeFunctions(MergeFunctions Bool) {
}

// llgo:link PassBuilderOptionsRef.SetInlinerThreshold C.LLVMPassBuilderOptionsSetInlinerThreshold
func (self PassBuilderOptionsRef) SetInlinerThreshold(Threshold c.Int) {
}

// Dispose of a heap-allocated PassBuilderOptions instance
//
// llgo:link PassBuilderOptionsRef.Dispose C.LLVMDisposePassBuilderOptions
func (self PassBuilderOptionsRef) Dispose() {
}
