// Code generated by llcppg; DO NOT EDIT.

package llvm

import "github.com/goplus/lib/c"

// @defgroup LLVMCSupportTypes Types and Enumerations
//
// @{
type Bool = c.Int
type OpaqueMemoryBuffer struct {
}

// Used to pass regions of memory through LLVM interfaces.
//
// @see llvm::MemoryBuffer
type MemoryBufferRef = *OpaqueMemoryBuffer
type OpaqueContext struct {
}

// The top-level container for all LLVM global data. See the LLVMContext class.
type ContextRef = *OpaqueContext
type OpaqueModule struct {
}

// The top-level container for all other LLVM Intermediate Representation (IR)
// objects.
//
// @see llvm::Module
type ModuleRef = *OpaqueModule
type OpaqueType struct {
}

// Each value in the LLVM IR has a type, an LLVMTypeRef.
//
// @see llvm::Type
type TypeRef = *OpaqueType
type OpaqueValue struct {
}

// Represents an individual value in LLVM IR.
//
// This models llvm::Value.
type ValueRef = *OpaqueValue
type OpaqueBasicBlock struct {
}

// Represents a basic block of instructions in LLVM IR.
//
// This models llvm::BasicBlock.
type BasicBlockRef = *OpaqueBasicBlock
type OpaqueMetadata struct {
}

// Represents an LLVM Metadata.
//
// This models llvm::Metadata.
type MetadataRef = *OpaqueMetadata
type OpaqueNamedMDNode struct {
}

// Represents an LLVM Named Metadata Node.
//
// This models llvm::NamedMDNode.
type NamedMDNodeRef = *OpaqueNamedMDNode
type OpaqueValueMetadataEntry struct {
}

// Represents an entry in a Global Object's metadata attachments.
//
// This models std::pair<unsigned, MDNode *>
type ValueMetadataEntry = OpaqueValueMetadataEntry
type OpaqueBuilder struct {
}

// Represents an LLVM basic block builder.
//
// This models llvm::IRBuilder.
type BuilderRef = *OpaqueBuilder
type OpaqueDIBuilder struct {
}

// Represents an LLVM debug info builder.
//
// This models llvm::DIBuilder.
type DIBuilderRef = *OpaqueDIBuilder
type OpaqueModuleProvider struct {
}

// Interface used to provide a module to JIT or interpreter.
// This is now just a synonym for llvm::Module, but we have to keep using the
// different type to keep binary compatibility.
type ModuleProviderRef = *OpaqueModuleProvider
type OpaquePassManager struct {
}

// @see llvm::PassManagerBase
type PassManagerRef = *OpaquePassManager
type OpaqueUse struct {
}

// Used to get the users and usees of a Value.
//
// @see llvm::Use
type UseRef = *OpaqueUse
type OpaqueOperandBundle struct {
}

// @see llvm::OperandBundleDef
type OperandBundleRef = *OpaqueOperandBundle
type OpaqueAttributeRef struct {
}

// Used to represent an attributes.
//
// @see llvm::Attribute
type AttributeRef = *OpaqueAttributeRef
type OpaqueDiagnosticInfo struct {
}

// @see llvm::DiagnosticInfo
type DiagnosticInfoRef = *OpaqueDiagnosticInfo
type Comdat struct {
}

// @see llvm::Comdat
type ComdatRef = *Comdat
type OpaqueModuleFlagEntry struct {
}

// @see llvm::Module::ModuleFlagEntry
type ModuleFlagEntry = OpaqueModuleFlagEntry
type OpaqueJITEventListener struct {
}

// @see llvm::JITEventListener
type JITEventListenerRef = *OpaqueJITEventListener
type OpaqueBinary struct {
}

// @see llvm::object::Binary
type BinaryRef = *OpaqueBinary
type OpaqueDbgRecord struct {
}

// @see llvm::DbgRecord
type DbgRecordRef = *OpaqueDbgRecord
